# -*- coding: utf-8 -*-
"""Ecolar_RBPF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13LyUvfme9fM4VElbkKgTpvsJiYOjLrjQ
"""

!pip install filterpy

!pip install control

!pip install ruptures

from google.colab import files
import numpy as np
import math as math
import matplotlib.pyplot as plt
import pandas as pd
from scipy.integrate import solve_ivp
import os
import importlib.util
from datetime import datetime
from typing import Dict, Any, List, Optional, Union
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import plotly.graph_objects as go
from statsmodels.tsa.stattools import kpss
from statsmodels.tsa.stattools import adfuller
from scipy.signal import detrend
import warnings
import numpy as np
import cvxpy as cp
from scipy.linalg import expm, block_diag
from scipy.optimize import minimize
import numpy as np
from sklearn.linear_model import LinearRegression
from scipy.interpolate import interp1d
from sklearn.preprocessing import StandardScaler
from xgboost import XGBRegressor
from sklearn.linear_model import Lasso
from sklearn.linear_model import Ridge
from sklearn.pipeline import make_pipeline
from statsmodels.graphics.tsaplots import plot_acf
from lightgbm import LGBMRegressor
from numpy.random import default_rng
import control
from scipy.linalg import expm

def filter_multi_column_changes(df, cols, time_col="Timestamp"): #We only keep rows where a changes in columns in col occurs
    df = df.sort_values(time_col).reset_index(drop=True)
    shifted = df[cols].shift(1)
    changed = (df[cols] != shifted).any(axis=1)
    return df[changed].reset_index(drop=True)

def find_and_split_gaps(
    df: pd.DataFrame,
    min_lag_seconds: int,
    time_col: str = "Timestamp"
) -> list[pd.DataFrame]:
    """
    Identifies time gaps in a DataFrame, prints a report, and splits the
    DataFrame into a list of continuous segments.
    """
    if time_col not in df.columns:
        raise ValueError(f"Time column '{time_col}' not found in the DataFrame.")

    # 1. Ensure data is sorted by timestamp
    df_sorted = df.copy()
    df_sorted[time_col] = pd.to_datetime(df_sorted[time_col])
    df_sorted = df_sorted.sort_values(by=time_col).reset_index(drop=True)

    # 2. Calculate the time difference between consecutive rows in seconds
    time_diffs = df_sorted[time_col].diff().dt.total_seconds()

    # 3. Find the indices where a new segment begins (i.e., after a gap)
    gap_indices = df_sorted.index[time_diffs > min_lag_seconds].tolist()

    # 4. Report the found gaps
    if not gap_indices:
        print(f"No gaps larger than {min_lag_seconds} seconds found.")
        return [df_sorted]  # Return the original sorted DataFrame in a list

    #print(f" Found {len(gap_indices)} gap(s) larger than {min_lag_seconds} seconds.")
    #print("-" * 60)
    for idx in gap_indices:
        gap_start_time = df_sorted.loc[idx - 1, time_col]
        gap_end_time = df_sorted.loc[idx, time_col]
        actual_gap = (gap_end_time - gap_start_time).total_seconds()

        #print(f"Gap detected between:\n  - Start: {gap_start_time}\n  - End:   {gap_end_time}")
        #print(f"  - Duration: {actual_gap:,.2f} seconds\n")
    #print("-" * 60)


    # 5. Decompose the DataFrame into a list of continuous DFs
    split_points = [0] + gap_indices + [len(df_sorted)]
    list_of_dfs = []

    # Create pairs of start/end indices for slicing
    for i in range(len(split_points) - 1):
        start_idx = split_points[i]
        end_idx = split_points[i+1]
        segment = df_sorted.iloc[start_idx:end_idx].reset_index(drop=True)
        list_of_dfs.append(segment)

    print(f"DataFrame has been split into {len(list_of_dfs)} continuous segments.")
    return list_of_dfs

def interpolate_to_grid(df, dt_seconds=60, time_col="Timestamp", interpolate_cols=None):
    df = df.copy()
    df[time_col] = pd.to_datetime(df[time_col])
    df = df.sort_values(time_col, ignore_index=True)

    # Original timestamps in epoch seconds
    t_orig = df[time_col].astype("int64") // 10**9
    start  = int(np.ceil(t_orig.iloc[0] / dt_seconds) * dt_seconds)
    end    = int(np.floor(t_orig.iloc[-1] / dt_seconds) * dt_seconds)
    t_new  = np.arange(start, end + 1, dt_seconds, dtype=np.int64)

    # New timestamp index
    new_timestamps = pd.to_datetime(t_new, unit="s")
    out = {time_col: new_timestamps}

    # Handle columns to interpolate
    if interpolate_cols is None:
        # Default to all numeric (excluding time_col)
        interpolate_cols = df.select_dtypes(include=np.number).columns.tolist()
        interpolate_cols = [c for c in interpolate_cols if c != time_col]

    for col in interpolate_cols:
        out[col] = np.interp(t_new, t_orig.to_numpy(), df[col].to_numpy())

    # Build interpolated DataFrame
    df_interp = pd.DataFrame(out)
    other_cols = [c for c in df.columns if c not in interpolate_cols + [time_col]]
    if other_cols:
        df_aux = df[[time_col] + other_cols].set_index(time_col)
        df_aux = df_aux.reindex(df_interp[time_col], method="ffill").reset_index(drop=True)
        df_interp[other_cols] = df_aux[other_cols]

    return df_interp

# ────────────────────────────────────────────────────────────────────────────
# 1) LOAD  +  PRE‑PROCESS (Robust 15-Min Aggregation)
# ────────────────────────────────────────────────────────────────────────────
dt_seconds = 1800  # 30 minutes
csv_path   = "final_merged_dataframe_full_DWD4.csv"

# 1. Load, Parse, Sort, and Filter Dates
df = pd.read_csv(csv_path, parse_dates=["Timestamp"]).sort_values("Timestamp", ignore_index=True)
df = df.loc[(df["Timestamp"] >= "2025-05-04 03:30") & (df["Timestamp"] <= "2025-06-14 23:00")].reset_index(drop=True)

# 2. Ensure Numeric Columns (Relays + PV)
relay_cols = ["Relay 4", "Relay 5"]
pv_cols    = ["my-pv1", "my-pv2", "my-pv3"]
for c in relay_cols + pv_cols:
    df[c] = pd.to_numeric(df[c], errors="coerce")

# 3. Calculate Power (Watts) on the original 5-min grid FIRST
#    We do this before resampling so we capture the true ON/OFF cycles.
df["heat_input"] = (df[pv_cols].sum(axis=1) + df[relay_cols].sum(axis=1)) * 1000.0

# 4. CRITICAL: Resample to 15-Minute Grid
#    - heat_input -> mean (Preserves Energy: Watts * Time)
#    - Temp2 -> first (The state at the beginning of the step)
#    - Outside/Other -> mean (Smooths boundary conditions)
df_15 = df.set_index("Timestamp").resample(f"{dt_seconds}s").agg({
    "Temp2": "first",
    "Sensor_outside": "mean",
    "Other_room_temp": "mean",
    "heat_input": "mean"
}).dropna().reset_index()

# 5. Gap Detection on the NEW 15-min grid
#    We check if we have any missing 15-min blocks.
#    (min_lag_seconds set to slightly larger than dt_seconds to catch gaps)
list_of_dfs = find_and_split_gaps(df=df_15, min_lag_seconds=dt_seconds + 60)
base_df = max(list_of_dfs, key=len)

# 6. Final Formatting
base_cols = ["Timestamp", "Temp2", "Sensor_outside", "Other_room_temp", "heat_input"]
base_df   = base_df[base_cols].copy().reset_index(drop=True)

print(f"--- Processing Complete ---")
print(f"Grid Step: {dt_seconds} seconds (15 min)")
print(f"Rows: {len(base_df)}")
print(f"Time range: {base_df['Timestamp'].min()} to {base_df['Timestamp'].max()}")
print("Head of Data:")
display(base_df.head())

# ─────────────────────────────────────────────────────────────────────────────
# 2) PREPARE DATA FOR OPTIMIZATION
# ─────────────────────────────────────────────────────────────────────────────

u_train    = base_df["heat_input"].to_numpy(dtype=float)      # The heater (Watts)
T_out_train= base_df["Sensor_outside"].to_numpy(dtype=float)  # Boundary 1 (Celsius)
T_or_train = base_df["Other_room_temp"].to_numpy(dtype=float) # Boundary 2 (Celsius)
y_train    = base_df["Temp2"].to_numpy(dtype=float)           # The Target (Celsius)
time_steps  = base_df["Timestamp"]
dt = dt_seconds  # seconds

# 3. Print shapes to confirm
print(f"Training Data Shapes:")
print(f"  u (Heater):      {u_train.shape}")
print(f"  T_out (Outside): {T_out_train.shape}")
print(f"  y (Target):      {y_train.shape}")
print(f"  dt:              {dt} seconds")

import plotly.graph_objects as go
from plotly.subplots import make_subplots

# Create a figure with a secondary y-axis (for the Heater Power)
fig = make_subplots(specs=[[{"secondary_y": True}]])

# 1. Indoor Temperature (Target) - Left Axis
fig.add_trace(
    go.Scatter(
        x=base_df["Timestamp"],
        y=base_df["Temp2"],
        name="Indoor Temp (Target)",
        mode='lines',
        line=dict(color='blue', width=2)
    ),
    secondary_y=False,
)

# 2. Outside Temperature (Disturbance) - Left Axis
fig.add_trace(
    go.Scatter(
        x=base_df["Timestamp"],
        y=base_df["Sensor_outside"],
        name="Outside Temp",
        mode='lines',
        line=dict(color='green', width=1.5, dash='dash')
    ),
    secondary_y=False,
)

# 3. Other Room Temperature (Disturbance) - Left Axis
fig.add_trace(
    go.Scatter(
        x=base_df["Timestamp"],
        y=base_df["Other_room_temp"],
        name="Other Room Temp",
        mode='lines',
        line=dict(color='orange', width=1.5, dash='dot')
    ),
    secondary_y=False,
)

# 4. Heater Power (Input) - RIGHT Axis
fig.add_trace(
    go.Scatter(
        x=base_df["Timestamp"],
        y=base_df["heat_input"],
        name="Heater Power (W)",
        mode='lines', # or 'lines+markers'
        line=dict(color='red', width=1),
        fill='tozeroy', # Optional: fills area under the heater curve
        opacity=0.3      # Semi-transparent so it doesn't block other lines
    ),
    secondary_y=True,
)

# Layout details
fig.update_layout(
    title_text="Training Data: Temperatures vs Heater Power",
    hovermode="x unified",  # Shows all values when you hover over a specific time
    legend=dict(
        orientation="h",
        yanchor="bottom",
        y=1.02,
        xanchor="right",
        x=1
    )
)

# Set x-axis title
fig.update_xaxes(title_text="Timestamp")

# Set y-axes titles
fig.update_yaxes(title_text="Temperature (°C)", secondary_y=False)
fig.update_yaxes(title_text="Power (Watts)", secondary_y=True)

fig.show()

import numpy as np
from scipy.optimize import minimize
from scipy.signal import cont2discrete

# ─────────────────────────────────────────────────────────────────────────────
# 4-state CT model: Air + Two Walls + Heater Node
# ─────────────────────────────────────────────────────────────────────────────

# Geometry / Constants
N_X0 = 3  # Number of hidden states (Wall_Out, Wall_In, Heater)

# Keys (10 parameters now)
POS_KEYS_4C = [
    "C_air", "C_wall_out", "C_wall_in", "C_heater",  # Capacities [J/K]
    "g_air_ow", "g_air_iw", "g_air_outside",         # Air connectivity [W/K]
    "g_wo_outside", "g_wi_other",                    # Walls -> Boundary [W/K]
    "g_air_heater"                                   # Heater -> Air [W/K]
]

def build_system_ct_4nodes(pos):
    """
    Return continuous-time (A_c, B_u, F_out, F_or, R) for the 4-state model.
    States: [T_air, T_wall_out, T_wall_in, T_heater]
    """
    # Unpack Capacities
    Ca  = float(pos["C_air"])
    Cwo = float(pos["C_wall_out"])
    Cwi = float(pos["C_wall_in"])
    Ch  = float(pos["C_heater"])

    # Unpack Conductances
    g_ao    = float(pos["g_air_ow"])
    g_ai    = float(pos["g_air_iw"])
    g_ao_ut = float(pos["g_air_outside"]) # Infiltration
    g_wo    = float(pos["g_wo_outside"])
    g_wi    = float(pos["g_wi_other"])
    g_ah    = float(pos["g_air_heater"])

    # Inverse Capacitance Matrix
    # Order: Air, Wall_Out, Wall_In, Heater
    Cinv = np.diag(1.0 / np.maximum([Ca, Cwo, Cwi, Ch], 1e-12))

    # Symmetric Conductance Matrix R (4x4)
    # 0: Air, 1: WO, 2: WI, 3: Heater
    R = np.zeros((4, 4), float)

    # Off-diagonals (Couplings)
    R[0, 1] = R[1, 0] = g_ao  # Air <-> Wall Out
    R[0, 2] = R[2, 0] = g_ai  # Air <-> Wall In
    R[0, 3] = R[3, 0] = g_ah  # Air <-> Heater

    # Diagonals (Sum of connections + leaks)
    R[0, 0] = -(g_ao + g_ai + g_ah + g_ao_ut) # Air loses to walls, heater, and outside
    R[1, 1] = -(g_ao + g_wo)                  # Wall Out loses to Air and Outside
    R[2, 2] = -(g_ai + g_wi)                  # Wall In loses to Air and Other Room
    R[3, 3] = -(g_ah)                         # Heater only loses to Air (assuming no back-loss)

    # Continuous-time state matrix
    A_c = Cinv @ R

    # Inputs
    # B_u: Electrical power u enters the HEATER node (State 3)
    B_u = Cinv @ np.array([[0.0, 0.0, 0.0, 1.0]]).T

    # F_out: Outside temp affects Air (infiltration) and Wall Out
    F_out  = Cinv @ np.array([[g_ao_ut, 0.0, 0.0, 0.0]]).T
    F_out += Cinv @ np.array([[0.0, g_wo, 0.0, 0.0]]).T

    # F_or: Other Room temp affects Wall In
    F_or = Cinv @ np.array([[0.0, 0.0, g_wi, 0.0]]).T

    return A_c, B_u, F_out, F_or, R

# ─────────────────────────────────────────────────────────────────────────────
# ZOH Discretization (Same logic, handles n=4 automatically)
# ─────────────────────────────────────────────────────────────────────────────
def c2d_zoh(A, B, dt):
    n = A.shape[0]
    m = B.shape[1]
    C_dummy = np.eye(n)
    D_dummy = np.zeros((n, m))
    Ad, Bd, _, _, _ = cont2discrete((A, B, C_dummy, D_dummy), dt, method='zoh')
    return Ad, Bd

def build_system_d_4nodes(pos, dt):
    """Bundle CT → DT system using ZOH discretization."""
    A_c, B_u, F_out, F_or, R = build_system_ct_4nodes(pos)

    # Stack inputs: [u, T_out, T_or]
    B = np.column_stack([B_u, F_out, F_or])

    Phi, Gamma = c2d_zoh(A_c, B, dt)
    return Phi, Gamma, R

# ─────────────────────────────────────────────────────────────────────────────
# Simulation / Loss / Bounds
# ─────────────────────────────────────────────────────────────────────────────
def z_to_params_4c(z):
    z = np.asarray(z, float)
    # First 10 are physical params
    pos_vals = z[:10]
    # Next 3 are hidden states [T_wo, T_wi, T_h]
    x0_h     = z[10:13]
    pos = {k: float(v) for k, v in zip(POS_KEYS_4C, pos_vals)}
    return pos, x0_h

def simulate_open_loop_4c(z, u, T_out, T_or, y, dt, return_states=False):
    pos, x0_h = z_to_params_4c(z)
    Phi, Gamma, R = build_system_d_4nodes(pos, dt)

    N = len(u)
    X = np.zeros((N, 4), float) # 4 States
    x = np.zeros(4, float)

    # Initial conditions
    x[0] = float(y[0])        # State 0: Air (measured)
    x[1:] = np.asarray(x0_h)  # States 1,2,3: Wall_O, Wall_I, Heater
    X[0] = x

    for k in range(N - 1):
        U_vec = np.array([u[k], T_out[k], T_or[k]], float)
        x = Phi @ x + Gamma @ U_vec

        # Stability check
        if not np.all(np.isfinite(x)) or np.any(np.abs(x) > 1e4):
            if return_states:
                return None, None, Phi, Gamma, R
            return None, Phi, Gamma, R
        X[k + 1] = x

    y_hat = X[:, 0] # Return Air Temp
    return (y_hat, X, Phi, Gamma, R) if return_states else (y_hat, Phi, Gamma, R)

def loss_open_loop_z_4c(z, u, T_out, T_or, y, dt, warmup_seconds=0.0):
    y_hat, Phi, Gamma, R = simulate_open_loop_4c(z, u, T_out, T_or, y, dt)
    if y_hat is None:
        return 1e12

    W = int(round(max(0.0, warmup_seconds) / dt))
    err = y_hat[1 + W:] - y[1 + W:]
    return float(np.mean(err * err))

def _set_bounds_4c():
    b = []
    # --- Capacities (J/K) ---
    b += [(1.8e4, 3.0e7)]   # C_air
    b += [(1.0e5, 2.0e7)]   # C_wall_out
    b += [(1.0e5, 2.0e7)]   # C_wall_in
    b += [(1.0e2, 5.0e5)]   # C_heater (New: Metal mass, smaller than air/walls)

    # --- Conductances (W/K) ---
    b += [(1.0, 9000.0)]    # g_air_ow
    b += [(1.0, 9000.0)]    # g_air_iw
    b += [(0.0, 20.0)]      # g_air_outside (Infiltration)
    b += [(10.0, 500.0)]    # g_wo_outside
    b += [(10.0, 500.0)]    # g_wi_other
    b += [(5.0, 5000.0)]    # g_air_heater (New: Radiator/Fan transfer rate)

    # --- Hidden Initial States ---
    # We now have 3 hidden states: [T_wo, T_wi, T_heater]
    # Heater usually starts somewhere between room temp and max temp
    b += [(-10.0, 40.0)] * 2 # Walls
    b += [(10.0, 80.0)]      # Heater core might start hotter or same as room

    return b

import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import minimize

# ─────────────────────────────────────────────────────────────────────────────
# 1) SETUP INITIAL GUESSES (4-NODE PHYSICS)
# ─────────────────────────────────────────────────────────────────────────────
# Updated Units list for 10 parameters
POS_UNITS_4C = [
    "J/K", "J/K", "J/K", "J/K",  # C_air, C_wo, C_wi, C_heater
    "W/K", "W/K", "W/K",         # g_ao, g_ai, g_inf
    "W/K", "W/K",                # g_wo_ext, g_wi_oth
    "W/K"                        # g_air_heater
]

area_ow   = 200.0   # m² (Outer Wall Area)
area_iw   = 30.36   # m² (Inner Wall Area)
alpha_in  = 8.0     # W/m²K (Indoor convection coefficient)

# Ensure dt is defined (mapped to your 15-min setting)
dt = dt_seconds     # 900.0
rho_air, cp_air = 1.225, 1007.0  # kg/m3, J/kgK
V_room  = 182.52                 # m3 (Volume)

# --- 1. Capacities [J/K] ---
C_air0    = rho_air * cp_air * V_room  # ~2.25e5
C_wo0     = 4.0e6                      # Heavy outer wall
C_wi0     = 3.0e6                      # Inner wall
C_heater0 = 5.0e4                      # NEW: Heater Mass (e.g., ~100kg iron/oil radiator)

# --- 2. Conductances [W/K] ---
# Geometry derived
g_air_ow0 = alpha_in * area_ow
g_air_iw0 = alpha_in * area_iw

# Wall -> Boundary (Derived from target U-values)
UA_out_target = 60.0
g_wo_outside0 = 1.0 / max(1.0/UA_out_target - 1.0/g_air_ow0, 1e-12)

UA_or_target  = 45.0
g_wi_other0   = 1.0 / max(1.0/UA_or_target - 1.0/g_air_iw0, 1e-12)

# New & Misc
g_air_outside0 = 2.0    # Infiltration
g_air_heater0  = 300.0  # NEW: Heater->Air coupling (High for fan/radiator)

# Pack Physical Parameters (10 values)
pos0_vals = np.array([
    C_air0, C_wo0, C_wi0, C_heater0,
    g_air_ow0, g_air_iw0, g_air_outside0,
    g_wo_outside0, g_wi_other0,
    g_air_heater0
], float)

# --- 3. Hidden Initial States [T_wo, T_wi, T_h] ---
# We have 3 hidden states now.
# Heuristic:
# 1. Wall Out starts at Outside Temp
# 2. Wall In starts at Indoor Temp
# 3. Heater starts at Indoor Temp (assuming it was off)
x0_hidden0 = np.array([T_out_train[0], y_train[0], y_train[0]], float)

# Combine into one vector z
z_start = np.concatenate([pos0_vals, x0_hidden0])

# Get Bounds (Using the 4c bounds function from previous block)
bounds = _set_bounds_4c()

# ─────────────────────────────────────────────────────────────────────────────
# 2) RUN OPTIMIZATION (4-NODE)
# ─────────────────────────────────────────────────────────────────────────────
print(f"Starting Optimization with {len(z_start)} parameters...")

res = minimize(
    fun=loss_open_loop_z_4c,
    x0=z_start,
    # Note: args must match the signature of loss_open_loop_z_4c
    args=(u_train, T_out_train, T_or_train, y_train, dt, 0.0),
    method="L-BFGS-B",
    bounds=bounds,
    options={"maxiter": 2000, "ftol": 1e-12, "disp": True}
)

print(f"\nOptimization Success: {res.success}")
print(f"Final MSE Loss: {res.fun:.6f}")

# ─────────────────────────────────────────────────────────────────────────────
# 3) VISUALIZE & REPORT
# ─────────────────────────────────────────────────────────────────────────────
# Run one final simulation with the best parameters
best_z = res.x
y_hat, X_states, Phi, Gamma, R = simulate_open_loop_4c(
    best_z, u_train, T_out_train, T_or_train, y_train, dt, return_states=True
)

# Extract physical names
best_pos, _ = z_to_params_4c(best_z)

# --- PLOTTING ---
plt.figure(figsize=(12, 10))

# Subplot 1: Temperature Fit (Air)
plt.subplot(3, 1, 1)
plt.plot(base_df["Timestamp"], y_train, 'k-', alpha=0.6, label="Measured (Air)")
plt.plot(base_df["Timestamp"], y_hat, 'r--', linewidth=2, label="Model Prediction (Air)")
plt.ylabel("Air Temp [°C]")
plt.title(f"4-State Model Fit (MSE: {res.fun:.4f})")
plt.legend()
plt.grid(True, alpha=0.3)

# Subplot 2: Wall Temperatures
plt.subplot(3, 1, 2)
# X_states indices: 0=Air, 1=Wall_Out, 2=Wall_In, 3=Heater
plt.plot(base_df["Timestamp"], X_states[:, 1], color='orange', label="Est. Wall Outer Core")
plt.plot(base_df["Timestamp"], X_states[:, 2], color='green', label="Est. Wall Inner Core")
plt.plot(base_df["Timestamp"], T_out_train, color='blue', alpha=0.2, label="Outside Temp (Ref)")
plt.ylabel("Wall Temp [°C]")
plt.legend(loc="upper right")
plt.grid(True, alpha=0.3)

# Subplot 3: Heater Temperature (The New State)
plt.subplot(3, 1, 3)
plt.plot(base_df["Timestamp"], X_states[:, 3], color='red', label="Est. Heater Core Temp")
# Overlay air for context
plt.plot(base_df["Timestamp"], y_hat, color='gray', linestyle=':', alpha=0.5, label="Air Temp (Context)")
plt.ylabel("Heater Temp [°C]")
plt.legend(loc="upper right")
plt.grid(True, alpha=0.3)
plt.xlabel("Timestamp")

plt.tight_layout()
plt.show()

# --- PRINT PARAMETERS ---
print("\n--- Identified Physical Parameters (4-Node) ---")
print(f"{'Parameter':<15} | {'Value':<12} | {'Unit'}")
print("-" * 40)
units = POS_UNITS_4C
for (k, v), u in zip(best_pos.items(), units):
    print(f"{k:<15} : {v:<12.4f}   {u}")

import numpy as np
from scipy.signal import cont2discrete

# ─────────────────────────────────────────────────────────────────────────────
# 1) SETTINGS & HYPERPARAMETERS
# ─────────────────────────────────────────────────────────────────────────────
Np = 30000                 # Number of Particles
dt_seconds = dt_seconds        # Time step (should be 900s / 15 mins)
sigma_y_pf = 0.1          # Measurement noise (Temp2)
print(f"RBPF running with dt: {dt_seconds}s")

# Baseline process noise (per-state) [Air, Wall_Out, Wall_In, Heater]
# Added 4th value for Heater noise
q_states = np.array([0.05, 0.05, 0.05, 0.05], float)

# Global SV (Random Walk on log alpha)
alpha_min, alpha_max = 0.01, 30.0
sigma_eta_post = 0.06

# Liu–West (log-space)
a_lw  = 0.99
h2_lw = 1.0 - a_lw**2

# Gating (Alpha-based)
g_min = 0.05      # Minimum learning rate
F_quiet = 0.30    # Bottom 30% = Quiet
F_burst = 0.80    # Top 20% = Burst

# Resampling
resample_frac = 0.5

# Mixture sampling counts
Nsamp_mixture_state = 1000

# ─────────────────────────────────────────────────────────────────────────────
# 2) HELPERS
# ─────────────────────────────────────────────────────────────────────────────
def systematic_resample(w, rng):
    N = w.size
    u0 = (rng.random() + np.arange(N)) / N
    cs = np.cumsum(w)
    idx = np.empty(N, int)
    i = j = 0
    while i < N:
        if u0[i] < cs[j]:
            idx[i] = j
            i += 1
        else:
            j += 1
    return idx

def wquantile(x, w, qs):
    x = np.asarray(x); w = np.asarray(w)
    i = np.argsort(x)
    xs, ws = x[i], w[i]
    cw = np.cumsum(ws)
    if cw[-1] > 0: cw /= cw[-1]
    else: cw = np.linspace(1/len(ws), 1, len(ws))
    return np.interp(qs, cw, xs)

def logsumexp(v):
    m = np.max(v)
    return m + np.log(np.sum(np.exp(v - m)))

def sample_from_weighted_gaussian_mixture(means, variances, weights, Nsamp, rng):
    weights = np.asarray(weights, float)
    cw = np.cumsum(weights)
    if cw[-1] > 0: cw /= cw[-1]
    else: cw = np.linspace(1/len(weights), 1, len(weights))
    u = (rng.random(Nsamp) + np.arange(Nsamp)) / Nsamp
    idx = np.searchsorted(cw, u, side='right')
    idx = np.clip(idx, 0, len(weights)-1)
    stds = np.sqrt(np.maximum(variances[idx], 1e-12))
    return means[idx] + stds * rng.standard_normal(Nsamp)

# --- UPDATED HELPER FOR 4 STATES ---
def get_continuous_matrices_4state(theta_arr):
    """
    Returns Continuous-time A_c and B_c for N particles (4-State Model).
    States: [T_air, T_wo, T_wi, T_heater]
    Output shapes: (Np, 4, 4) and (Np, 4, 3)
    """
    Np_loc = theta_arr.shape[0]

    # Unpack columns (Now 10 parameters)
    # 0:Ca, 1:Cwo, 2:Cwi, 3:Cheater,
    # 4:gao, 5:gai, 6:gao_ext, 7:gwo_ext, 8:gwi_oth, 9:gah
    Ca      = theta_arr[:, 0]
    Cwo     = theta_arr[:, 1]
    Cwi     = theta_arr[:, 2]
    Ch      = theta_arr[:, 3]
    gao     = theta_arr[:, 4]
    gai     = theta_arr[:, 5]
    gao_ext = theta_arr[:, 6]
    gwo_ext = theta_arr[:, 7]
    gwi_oth = theta_arr[:, 8]
    gah     = theta_arr[:, 9]

    # --- Build A_c (Dynamics 4x4) ---
    A = np.zeros((Np_loc, 4, 4))

    # Row 0: Air (Connects to WO, WI, Heater, Outside)
    A[:,0,0] = -(gao + gai + gah + gao_ext) / Ca
    A[:,0,1] = gao / Ca
    A[:,0,2] = gai / Ca
    A[:,0,3] = gah / Ca  # From Heater

    # Row 1: Wall Out (Connects to Air, Outside)
    A[:,1,0] = gao / Cwo
    A[:,1,1] = -(gao + gwo_ext) / Cwo

    # Row 2: Wall In (Connects to Air, Other Room)
    A[:,2,0] = gai / Cwi
    A[:,2,2] = -(gai + gwi_oth) / Cwi

    # Row 3: Heater (Connects to Air)
    A[:,3,0] = gah / Ch
    A[:,3,3] = -gah / Ch

    # --- Build B_c (Inputs 4x3) ---
    # Input Vector U: [u (Power), T_out, T_or]
    B = np.zeros((Np_loc, 4, 3))

    # Row 0: Air (Infiltration) - Note: Power no longer goes here directly
    B[:,0,1] = gao_ext / Ca      # T_out -> Air

    # Row 1: Wall Out (Outside Temp)
    B[:,1,1] = gwo_ext / Cwo     # T_out -> Wall Out

    # Row 2: Wall In (Other Room Temp)
    B[:,2,2] = gwi_oth / Cwi     # T_or -> Wall In

    # Row 3: Heater Node (Gets the Power Input)
    # Note: If 'eta' (efficiency) was removed, this is just 1.0/Ch.
    # If parameters included efficiency, it would be eta/Ch.
    # Assuming direct heating:
    B[:,3,0] = 1.0 / Ch          # u -> Heater Node

    return A, B

# ─────────────────────────────────────────────────────────────────────────────
# 3) DATA PREPARATION & INITIALIZATION
# ─────────────────────────────────────────────────────────────────────────────
# Extract arrays from base_df
Y_meas    = base_df["Temp2"].to_numpy(dtype=float)
u_arr     = base_df["heat_input"].to_numpy(dtype=float)
T_out_arr = base_df["Sensor_outside"].to_numpy(dtype=float)
T_or_arr  = base_df["Other_room_temp"].to_numpy(dtype=float)

N = len(Y_meas)
rng = np.random.default_rng(42)

# Measurement Matrix: We observe State 0 (Air)
# Now 1x4 because state vector is 4x1
C_y = np.array([[1, 0, 0, 0]], float)

# Parameter Definitions (Updated for 4 Nodes)
theta_names = [
    "C_air", "C_wo", "C_wi", "C_heater",
    "g_ao", "g_ai", "g_ao_ext", "g_wo_ext", "g_wi_other",
    "g_ah"
]
d_theta = len(theta_names)

# Define Ranges
_param_defaults = {
    "C_air":    (1.0e3, 8.0e6),
    "C_wo":     (1.0e3, 8.0e6),
    "C_wi":     (1.0e3, 8.0e6),
    "C_heater": (1.0e3, 5.0e5),    # Heater thermal mass
    "g_ao":     (0.1, 9000.0),
    "g_ai":     (0.1, 9000.0),
    "g_ao_ext": (0.1, 9000.0),
    "g_wo_ext": (0.1, 9000.0),
    "g_wi_other":(50, 900.0),
    "g_ah":     (5.0, 9000.0)      # Heater-Air coupling
}

theta_lo = np.empty(d_theta, float)
theta_hi = np.empty(d_theta, float)
theta_eps = 1e-20

for j, nm in enumerate(theta_names):
    spec = _param_defaults[nm]
    theta_lo[j] = max(float(spec[0]), theta_eps)
    theta_hi[j] = max(float(spec[1]), theta_eps)

# Initialize States [Air, Wall_Out, Wall_In, Heater]
T_start = float(Y_meas[0])
# Create (Np, 4) matrix
m = np.tile(np.array([T_start]*4, float), (Np, 1))
m += rng.normal(0, 0.5, size=m.shape)

# Covariance 4x4
P0 = np.diag([0.5**2, 2.0**2, 2.0**2, 5.0**2])
P  = np.tile(P0, (Np, 1, 1))

# Initialize Alpha
log_alpha = rng.normal(0.0, 0.1, size=Np)
log_alpha = np.clip(log_alpha, np.log(alpha_min), np.log(alpha_max))
alpha     = np.exp(log_alpha)

# Initialize Theta (Log-Uniform)
phi_lo = np.log(theta_lo)
phi_hi = np.log(theta_hi)
phi    = rng.uniform(low=phi_lo[None, :], high=phi_hi[None, :], size=(Np, d_theta))
theta  = np.exp(phi)

logw = np.full(Np, -np.log(Np), float)
Q0_diag = q_states**2
R = np.array([[sigma_y_pf**2]], float)

# Storage & Diagnostics
regime_flag = np.zeros(N, dtype=int)
z_std_innov = np.zeros(N)

n_bins_alpha = 30
log_alpha_min = np.log(alpha_min)
log_alpha_max = np.log(alpha_max)
alpha_bin_edges = np.linspace(log_alpha_min, log_alpha_max, n_bins_alpha + 1)
alpha_hist_counts = np.full(n_bins_alpha, 1.0, dtype=float)

q_lo, q_md, q_hi = 0.025, 0.50, 0.975
Ti_lo = np.zeros(N); Ti_md = np.zeros(N); Ti_hi = np.zeros(N)
Y_pred_mean = np.full(N, np.nan)
Y_pred_std  = np.full(N, np.nan)

Th_lo = np.zeros((N, d_theta))
Th_md = np.zeros((N, d_theta))
Th_hi = np.zeros((N, d_theta))

Alpha_lo = np.zeros(N)
Alpha_md = np.zeros(N)
Alpha_hi = np.zeros(N)

# ─────────────────────────────────────────────────────────────────────────────
# 4) MAIN RBPF LOOP (EULER SUB-STEPPING - 4 STATE)
# ─────────────────────────────────────────────────────────────────────────────
const_ll = -0.5 * np.log(2*np.pi)
I4_batch = np.eye(4)[None, :, :]  # Identity matrix 4x4

print(f"Starting RBPF on {N} samples with {Np} particles (4-State Sub-Stepping)...")

for k in range(1, N):
    # Inputs at k-1
    uk   = u_arr[k-1]
    Tok  = T_out_arr[k-1]
    Tork = T_or_arr[k-1]

    # Measurement at k
    yk = float(Y_meas[k])

    w_lin_prior = np.exp(logw - logsumexp(logw))

    # --- (A) Global SV Step ---
    log_alpha = log_alpha + rng.normal(0.0, sigma_eta_post, size=Np)
    log_alpha = np.clip(log_alpha, np.log(alpha_min), np.log(alpha_max))
    alpha     = np.exp(log_alpha)

    # --- (B) Alpha Gating Logic ---
    alpha_med_k = wquantile(alpha, w_lin_prior, [0.5])[0]
    log_alpha_med_k = np.log(np.clip(alpha_med_k, alpha_min, alpha_max))

    bin_idx = np.searchsorted(alpha_bin_edges, log_alpha_med_k, side='right') - 1
    bin_idx = np.clip(bin_idx, 0, n_bins_alpha - 1)
    alpha_hist_counts[bin_idx] += 1.0

    cdf_bins = np.cumsum(alpha_hist_counts)
    cdf_bins /= cdf_bins[-1]
    F_k = cdf_bins[bin_idx]

    if F_k <= F_quiet:
        g_alpha, regime_flag[k] = 1.0, 0
    elif F_k >= F_burst:
        g_alpha, regime_flag[k] = g_min, 1
    else:
        r = (F_burst - F_k) / (F_burst - F_quiet + 1e-12)
        g_alpha = g_min + (1.0 - g_min) * r
        regime_flag[k] = 0

    g_k = max(g_alpha, g_min)

    # --- (C) Liu-West Step (Parameter Update) ---
    phi = np.log(np.clip(theta, theta_eps, None))

    a_k  = 1.0 - g_k * (1.0 - a_lw)
    h2_k = g_k * h2_lw

    phi_bar_free = np.sum(phi * w_lin_prior[:, None], axis=0)
    diff_free    = phi - phi_bar_free[None, :]
    V_free       = diff_free.T @ (diff_free * w_lin_prior[:, None])
    V_free       = 0.5 * (V_free + V_free.T) + 1e-12 * np.eye(d_theta)

    L_free   = np.linalg.cholesky(V_free)
    eps_free = rng.standard_normal((Np, d_theta)) @ (np.sqrt(h2_k) * L_free.T)

    phi   = a_k * phi + (1.0 - a_k) * phi_bar_free[None, :] + eps_free
    phi   = np.clip(phi, phi_lo[None, :], phi_hi[None, :])
    theta = np.exp(phi)

    # --- (D) Kalman Predict Step (Sub-Stepped Euler) ---
    # 1. Get continuous matrices (4x4)
    A_c, B_c = get_continuous_matrices_4state(theta)

    # 2. Setup Sub-stepping (30 steps for stability with 15-min dt)
    dt_total = dt_seconds  # e.g., 900.0
    n_subs   = 30          # 30 * 30s = 900s (Very stable)
    dt_sub   = dt_total / n_subs

    # 3. Prepare Inputs (Np, 3)
    U_vec = np.column_stack([
        np.full(Np, uk),
        np.full(Np, Tok),
        np.full(Np, Tork)
    ])

    # 4. Integrate State (The "Micro-Loop")
    m_pred = m.copy()

    for _ in range(n_subs):
        # dx/dt = A*x + B*u (All 4x4 or 4x3)
        dx = np.einsum('nij,nj->ni', A_c, m_pred) + \
             np.einsum('nij,nj->ni', B_c, U_vec)
        m_pred += dx * dt_sub

    # 5. Predict Covariance P (One-shot Approximation)
    Phi_approx = I4_batch + (A_c * dt_total)

    # P = Phi * P * Phi'
    P_pred = np.einsum('nij,njk,nlk->nil', Phi_approx, P, Phi_approx)

    # Add Process Noise (Now 4-state diagonal)
    scale_sq = np.exp(2.0 * log_alpha)
    qdiag    = scale_sq[:, None] * Q0_diag[None, :]
    for s in range(4): # Loop over 4 states
        P_pred[:, s, s] += qdiag[:, s]

    # --- (E) Likelihood & Weight Update ---
    # y_hat = C * m_pred
    y_pred = (m_pred @ C_y.T).ravel()

    # S = C P C' + R
    S = np.einsum('ij,njk,kl->n', C_y, P_pred, C_y.T) + R[0, 0]
    S = np.maximum(S, 1e-12)

    innov = yk - y_pred
    ll    = const_ll - 0.5*np.log(S) - 0.5*(innov**2)/S
    logw  = logw + ll
    logw  = logw - logsumexp(logw)
    w_lin_post = np.exp(logw)

    # Save Stats
    mu_k  = np.sum(w_lin_prior * y_pred)
    var_k = np.sum(w_lin_prior * (y_pred**2 + S)) - mu_k**2
    Y_pred_mean[k] = mu_k
    Y_pred_std[k]  = np.sqrt(max(var_k, 1e-12))
    z_std_innov[k] = (yk - mu_k) / np.sqrt(max(var_k, 1e-12))

    # --- (F) Kalman Update Step ---
    K = (P_pred @ C_y.T) / S[:, None, None]  # (Np, 4, 1)
    m = m_pred + (K.reshape(Np, 4) * innov[:, None])

    KC = np.matmul(K, C_y)
    P  = np.matmul(I4_batch - KC, P_pred)

    # Store Air Temp Quantiles
    Ti_draws = sample_from_weighted_gaussian_mixture(
        m[:, 0], P[:, 0, 0], w_lin_post, Nsamp_mixture_state, rng
    )
    Ti_lo[k], Ti_md[k], Ti_hi[k] = np.quantile(Ti_draws, [q_lo, q_md, q_hi])

    # Parameter and Alpha quantiles
    for j in range(d_theta):
        Th_lo[k, j], Th_md[k, j], Th_hi[k, j] = wquantile(
            theta[:, j], w_lin_post, [q_lo, q_md, q_hi]
        )

    Alpha_lo[k], Alpha_md[k], Alpha_hi[k] = wquantile(
        alpha, w_lin_post, [q_lo, q_md, q_hi]
    )

    # --- (G) Resampling ---
    Neff = 1.0 / np.sum(w_lin_post**2)
    if Neff < resample_frac * Np:
        idx = systematic_resample(w_lin_post, rng)
        m   = m[idx]
        P   = P[idx]
        log_alpha = log_alpha[idx]
        alpha = alpha[idx]
        theta = theta[idx]
        logw[:] = -np.log(Np)

print("RBPF Complete.")

import matplotlib.pyplot as plt
import math

# ─────────────────────────────────────────────────────────────────────────────
# 1) PLOT PARAMETER TRAJECTORIES (Learning Curves)
# ─────────────────────────────────────────────────────────────────────────────
# We now have 10 parameters, so we need a larger grid (e.g., 4 rows x 3 cols = 12 slots)
n_params = len(theta_names)
n_cols = 3
n_rows = math.ceil(n_params / n_cols)

fig, axes = plt.subplots(n_rows, n_cols, figsize=(16, 12), sharex=True)
axes = axes.flatten()

timestamps = base_df["Timestamp"].iloc[:N]

for j, name in enumerate(theta_names):
    ax = axes[j]

    # Extract quantiles for this parameter
    p_lo = Th_lo[:, j]
    p_md = Th_md[:, j]
    p_hi = Th_hi[:, j]

    # Plot Confidence Interval (Shaded)
    ax.fill_between(timestamps, p_lo, p_hi, color='blue', alpha=0.2, label="95% CI")

    # Plot Median (Solid Line)
    ax.plot(timestamps, p_md, color='blue', linewidth=1.5, label="Median")

    ax.set_title(name)
    ax.grid(True, alpha=0.3)

# Hide any unused subplots (e.g., if we have 10 params in a 12-plot grid)
for k in range(n_params, len(axes)):
    axes[k].set_visible(False)

# Layout adjustments
handles, labels = axes[0].get_legend_handles_labels()
fig.legend(handles, labels, loc='upper right')
plt.suptitle(f"RBPF Parameter Estimation (Time Evolution) - 4 State Model", fontsize=16)
plt.tight_layout(rect=[0, 0.03, 1, 0.95])
plt.show()

# ─────────────────────────────────────────────────────────────────────────────
# 2) PLOT STOCHASTIC VOLATILITY (Alpha)
# ─────────────────────────────────────────────────────────────────────────────
plt.figure(figsize=(12, 4))
plt.plot(timestamps, Alpha_md, color='purple', linewidth=1.5)
plt.fill_between(timestamps, Alpha_lo, Alpha_hi, color='purple', alpha=0.2)
plt.ylabel("Alpha (Scale Factor)")
plt.title("Median Stochastic Volatility (Model Uncertainty Scaling)")
plt.grid(True, alpha=0.3)

# Highlight "Burst" regimes if you tracked them
burst_indices = np.where(regime_flag == 1)[0]
if len(burst_indices) > 0:
    plt.scatter(timestamps.iloc[burst_indices], Alpha_md[burst_indices],
                color='red', s=10, label="Burst Regime (High Learning)")
    plt.legend()

plt.show()

# ─────────────────────────────────────────────────────────────────────────────
# 3) PRINT FINAL PARAMETER ESTIMATES
# ─────────────────────────────────────────────────────────────────────────────
print("\n=== Final Parameter Estimates (Median at t=N) ===")
print(f"{'Parameter':<15} | {'Median':<12} | {'95% CI (Low - High)'}")
print("-" * 65)

for j, name in enumerate(theta_names):
    med = Th_md[-1, j]
    lo  = Th_lo[-1, j]
    hi  = Th_hi[-1, j]
    print(f"{name:<15} : {med:<12.4f} | ({lo:.4f} - {hi:.4f})")

import matplotlib.pyplot as plt
import numpy as np

# ─────────────────────────────────────────────────────────────────────────────
# 1) EXTRACT FINAL LEARNED PARAMETERS
# ─────────────────────────────────────────────────────────────────────────────
# We take the median parameters from the very last time step of the RBPF
theta_final = Th_md[-1, :]

print("=== Final Learned Parameters (for Open Loop Check) ===")
param_dict = {}
for i, name in enumerate(theta_names):
    val = theta_final[i]
    param_dict[name] = val
    print(f"  {name:<12} : {val:.4f}")

# ─────────────────────────────────────────────────────────────────────────────
# 2) RUN OPEN-LOOP SIMULATION (Validation - 4 State, Sub-Stepped)
# ─────────────────────────────────────────────────────────────────────────────
# We simulate the 4-state model from t=0 using ONLY these constant parameters.
# NOTE: We MUST use sub-stepping here too, or 15-min Euler will explode.

def simulate_open_loop_final_4state(theta_vec, u, T_out, T_or, y_start, dt_total):
    # Unpack 10 parameters
    # 0:Ca, 1:Cwo, 2:Cwi, 3:Ch, 4:gao, 5:gai, 6:gao_ext, 7:gwo_ext, 8:gwi_oth, 9:gah
    Ca, Cwo, Cwi, Ch, gao, gai, gao_ext, gwo_ext, gwi_oth, gah = theta_vec

    # --- Build Continuous Matrices A (4x4) and B (4x3) ---
    A = np.zeros((4,4))

    # Row 0: Air
    A[0,0] = -(gao + gai + gah + gao_ext) / Ca
    A[0,1] = gao / Ca
    A[0,2] = gai / Ca
    A[0,3] = gah / Ca

    # Row 1: Wall Out
    A[1,0] = gao / Cwo
    A[1,1] = -(gao + gwo_ext) / Cwo

    # Row 2: Wall In
    A[2,0] = gai / Cwi
    A[2,2] = -(gai + gwi_oth) / Cwi

    # Row 3: Heater
    A[3,0] = gah / Ch
    A[3,3] = -gah / Ch

    # Matrix B (Inputs: u, T_out, T_or)
    B = np.zeros((4,3))
    B[0,1] = gao_ext / Ca      # T_out -> Air
    B[1,1] = gwo_ext / Cwo     # T_out -> Wall Out
    B[2,2] = gwi_oth / Cwi     # T_or  -> Wall In
    B[3,0] = 1.0 / Ch          # u     -> Heater Node

    # --- Simulation Loop with Sub-Stepping ---
    N_sim = len(u)
    X_sim = np.zeros((N_sim, 4))

    # Initial State: Assume everything starts at measured air temp
    x = np.array([y_start, y_start, y_start, y_start])

    # Sub-step settings (match RBPF)
    n_subs = 30
    dt_sub = dt_total / n_subs

    for k in range(N_sim):
        X_sim[k] = x

        if k < N_sim - 1:
            # Current inputs
            U_vec = np.array([u[k], T_out[k], T_or[k]])

            # Micro-loop integration
            for _ in range(n_subs):
                dx = A @ x + B @ U_vec
                x += dx * dt_sub

    return X_sim[:, 0], X_sim # Return Air Temp, All States

# Run the simulation
# Use the global dt_seconds (900s)
y_open_loop, X_states_open = simulate_open_loop_final_4state(
    theta_final, u_arr, T_out_arr, T_or_arr, Y_meas[0], dt_seconds
)

# ─────────────────────────────────────────────────────────────────────────────
# 3) PLOT RESULTS (start from k = 1)
# ─────────────────────────────────────────────────────────────────────────────
fig, ax = plt.subplots(3, 1, figsize=(14, 12), sharex=True)

# Time index aligned with RBPF arrays
timestamps = base_df["Timestamp"].iloc[:N]

# We skip k=0 everywhere (Initialization artifact)
ts_plot      = timestamps.iloc[1:]
Y_meas_plot  = Y_meas[1:]
Ti_lo_plot   = Ti_lo[1:]
Ti_md_plot   = Ti_md[1:]
Ti_hi_plot   = Ti_hi[1:]
y_ol_plot    = y_open_loop[1:]
Alpha_md_plot = Alpha_md[1:]
Alpha_lo_plot = Alpha_lo[1:]
Alpha_hi_plot = Alpha_hi[1:]
regime_plot   = regime_flag[1:]

# --- PLOT 1: RBPF Tracking ---
ax[0].plot(ts_plot, Y_meas_plot, 'k-', alpha=0.4, label="Measured Data")
ax[0].plot(ts_plot, Ti_md_plot, 'b-', linewidth=1, label="RBPF Estimate")
ax[0].fill_between(ts_plot, Ti_lo_plot, Ti_hi_plot, color='blue', alpha=0.1, label="95% CI")
ax[0].set_ylabel("Temp [°C]")
ax[0].set_title("1. RBPF Tracking Performance (Online Learning)")
ax[0].legend(loc="upper right")
ax[0].grid(True, alpha=0.3)

# --- PLOT 2: Open-Loop Check ---
ax[1].plot(ts_plot, Y_meas_plot, 'k-', alpha=0.4, label="Measured Data")
ax[1].plot(ts_plot, y_ol_plot, 'r--', linewidth=2, label="Open-Loop Sim (Final Params)")
ax[1].set_ylabel("Temp [°C]")
ax[1].set_title("2. Open-Loop Simulation using Final Learned Parameters")
ax[1].legend(loc="upper right")
ax[1].grid(True, alpha=0.3)

# --- PLOT 3: Stochastic Volatility ---
ax[2].plot(ts_plot, Alpha_md_plot, color='purple', linewidth=1.5)
ax[2].fill_between(ts_plot, Alpha_lo_plot, Alpha_hi_plot, color='purple', alpha=0.2)
ax[2].set_ylabel("Alpha")
ax[2].set_title("3. Stochastic Volatility (Process Noise Scaling)")
ax[2].grid(True, alpha=0.3)

# Highlight Bursts
bursts_rel = np.where(regime_plot == 1)[0]
if len(bursts_rel) > 0:
    ax[2].scatter(ts_plot.iloc[bursts_rel], Alpha_md_plot[bursts_rel],
                  color='red', s=5, label="High Volatility Regime")
    ax[2].legend()

plt.tight_layout()
plt.show()

# --- PLOT 4: Hidden States (Walls + Heater) ---
plt.figure(figsize=(14, 6))

X_ow_plot   = X_states_open[1:, 1]
X_iw_plot   = X_states_open[1:, 2]
X_h_plot    = X_states_open[1:, 3] # Heater Temp
T_out_plot  = T_out_arr[1:]

plt.plot(ts_plot, X_ow_plot, color='orange', label="Outer Wall Core")
plt.plot(ts_plot, X_iw_plot, color='green', label="Inner Wall Core")
plt.plot(ts_plot, X_h_plot, color='red', linestyle='--', label="Heater Core (State 3)")
plt.plot(ts_plot, T_out_plot, color='cyan', alpha=0.3, linestyle=':', label="Outside Air (Ref)")

plt.title("Estimated Internal Temperatures (Open Loop Simulation)")
plt.ylabel("Temp [°C]")
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

import plotly.graph_objects as go
from plotly.subplots import make_subplots
import numpy as np

# ─────────────────────────────────────────────────────────────────────────────
# 1) DATA PREPARATION
# ─────────────────────────────────────────────────────────────────────────────
# Slices (skip k=0)
ts_plot     = base_df["Timestamp"].iloc[1:N]
y_meas_plot = Y_meas[1:]
ti_md_plot  = Ti_md[1:]
ti_hi_plot  = Ti_hi[1:]
ti_lo_plot  = Ti_lo[1:]
u_plot      = u_arr[1:]
alpha_plot  = Alpha_md[1:]

# Identify "Learning Freeze" points (Regime 1)
# These are points where the model detected a 'burst' and clamped parameter adaptation
freeze_indices = np.where(regime_flag[1:] == 1)[0]
ts_freeze      = ts_plot.iloc[freeze_indices]
alpha_freeze   = alpha_plot[freeze_indices]

# ─────────────────────────────────────────────────────────────────────────────
# 2) BUILD PLOTLY FIGURE
# ─────────────────────────────────────────────────────────────────────────────
fig = make_subplots(
    rows=3, cols=1,
    shared_xaxes=False, # Row 3 (Hist) has different X axis
    vertical_spacing=0.08,
    row_heights=[0.5, 0.25, 0.25], # 50% Main, 25% Alpha, 25% Hist
    specs=[[{"secondary_y": True}],  # Row 1: Dual Axis
           [{"secondary_y": False}], # Row 2: Alpha Series
           [{"secondary_y": False}]] # Row 3: Histogram
)

# --- ROW 1: TEMPERATURES & POWER ---

# Confidence Band
fig.add_trace(go.Scatter(
    x=ts_plot, y=ti_hi_plot, mode='lines', line=dict(width=0),
    showlegend=False, hoverinfo='skip'
), row=1, col=1)

fig.add_trace(go.Scatter(
    x=ts_plot, y=ti_lo_plot, mode='lines', line=dict(width=0),
    fill='tonexty', fillcolor='rgba(0, 0, 255, 0.15)',
    name='95% Uncertainty'
), row=1, col=1)

# Estimates & Measure
fig.add_trace(go.Scatter(
    x=ts_plot, y=ti_md_plot, mode='lines', name='Model Estimate',
    line=dict(color='blue', width=2)
), row=1, col=1)

fig.add_trace(go.Scatter(
    x=ts_plot, y=y_meas_plot, mode='lines', name='Measured',
    line=dict(color='black', width=1, dash='dot'), opacity=0.6
), row=1, col=1)

# Heater (Right Axis)
fig.add_trace(go.Scatter(
    x=ts_plot, y=u_plot, mode='lines', name='Heater (W)',
    line=dict(color='red', width=1), fill='tozeroy', opacity=0.2
), row=1, col=1, secondary_y=True)


# --- ROW 2: ALPHA TRAJECTORY + FREEZE MARKERS ---

# Alpha Line
fig.add_trace(go.Scatter(
    x=ts_plot, y=alpha_plot, mode='lines', name='Median Alpha',
    line=dict(color='purple', width=1.5)
), row=2, col=1)

# Freeze Markers
fig.add_trace(go.Scatter(
    x=ts_freeze, y=alpha_freeze,
    mode='markers', name='Learning Freeze',
    marker=dict(color='red', symbol='x', size=8, line=dict(width=1, color='white'))
), row=2, col=1)


# --- ROW 3: HISTOGRAM OF ALPHA MEDIANS ---

fig.add_trace(go.Histogram(
    x=alpha_plot,
    name='Alpha Distribution',
    marker_color='purple',
    opacity=0.7,
    nbinsx=50
), row=3, col=1)

# ─────────────────────────────────────────────────────────────────────────────
# 3) LAYOUT
# ─────────────────────────────────────────────────────────────────────────────
fig.update_layout(
    title_text="RBPF Analysis: Tracking, Volatility, and Regime Distribution",
    height=900,
    hovermode="x unified",
    showlegend=True,
    legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1)
)

# Axis Labels
fig.update_yaxes(title_text="Temp (°C)", row=1, col=1, secondary_y=False)
fig.update_yaxes(title_text="Power (W)", row=1, col=1, secondary_y=True, showgrid=False)
fig.update_yaxes(title_text="Alpha Scale", row=2, col=1)
fig.update_yaxes(title_text="Count", row=3, col=1)
fig.update_xaxes(title_text="Alpha Value", row=3, col=1)

# Align time axes for Row 1 & 2
fig.update_xaxes(matches='x', row=1, col=1)
fig.update_xaxes(matches='x', row=2, col=1)

fig.show()

# Cell 2: Build ARX design matrix (lags of y and exogenous inputs)
# Make plots a bit nicer
plt.rcParams["figure.figsize"] = (12, 4)
plt.rcParams["axes.grid"] = True

# Target and exogenous variables for ARX
y_col = "Temp2"
exog_cols = ["heat_input", "Sensor_outside", "Other_room_temp"]

# ARX lag order (m)
lag_order = 3  # for example
df = base_df.copy()

y = df[y_col].values.astype(float)
exogs = [df[c].values.astype(float) for c in exog_cols]

N = len(df)
m = lag_order
if N <= m:
    raise ValueError("Time series too short for given lag_order.")

# Collect lagged features in a list, then stack
X_list = []

# 1) Lags of y: y(t-1)...y(t-m)
for lag in range(1, m + 1):
    # from index (m-lag) up to (N-lag-1) inclusive -> length N-m
    X_list.append(y[m - lag : N - lag])

# 2) Lags of each exogenous input: u_j(t-1)...u_j(t-m)
for ex in exogs:
    for lag in range(1, m + 1):
        X_list.append(ex[m - lag : N - lag])

# Design matrix X (N_eff x n_features)
X = np.column_stack(X_list)

# Target y(t)
y_target = y[m:]

# Aligned dataframe (index from m onward)
df_eff = df.iloc[m:].copy()

print(f"Design matrix shape X: {X.shape}, target length: {len(y_target)}")
# Add intercept explicitly: [1, X]
X_with_intercept = np.column_stack([np.ones(len(X)), X])

# Solve y = X_with_intercept @ beta in least squares sense
beta_hat, residuals, rank, svals = np.linalg.lstsq(X_with_intercept, y_target, rcond=None)

intercept = beta_hat[0]
coef = beta_hat[1:]

print(f"Intercept: {intercept:.4f}")
print(f"Number of coefficients: {len(coef)}")

# Cell 4: Closed-loop (1-step-ahead) prediction

# Closed-loop predictions are just X_with_intercept @ beta_hat
y_hat_closed = X_with_intercept @ beta_hat

# True values aligned with y_hat_closed
y_true_closed = y_target.copy()
time_closed = df_eff.index

# Residuals (true - predicted)
residuals_closed = y_true_closed - y_hat_closed

print("Closed-loop prediction done.")
print(f"RMSE (closed-loop): {np.sqrt(np.mean((y_true_closed - y_hat_closed)**2)):.4f}")

# Cell 5: Open-loop (free-run) prediction

# We need to split coef into:
#   first m: lags of y
#   then for each exog, m coefficients
n_exog = len(exog_cols)
idx = 0

# Coefficients for y lags
a_y = coef[idx : idx + m]
idx += m

# Coefficients for exog lags: shape (n_exog, m)
b_ex = []
for _ in range(n_exog):
    b_ex.append(coef[idx : idx + m])
    idx += m
b_ex = np.array(b_ex)  # (n_exog, m)

# Prepare recursive simulation on full series
N = len(df)
y_full = df[y_col].values.astype(float)
exogs_full = [df[c].values.astype(float) for c in exog_cols]

# Allocate array for predictions
y_hat_full = np.zeros(N, dtype=float)

# Warm start: use true values for first m samples
y_hat_full[:m] = y_full[:m]

# Now simulate forward
for t in range(m, N):
    # y lags from predicted series
    y_lags = np.array([y_hat_full[t - lag] for lag in range(1, m + 1)])

    # exog lags from true series
    exog_lags_all = []
    for ex in exogs_full:
        exog_lags_all.append([ex[t - lag] for lag in range(1, m + 1)])
    exog_lags_all = np.array(exog_lags_all)  # (n_exog, m)

    # Linear prediction
    y_t_hat = intercept + a_y @ y_lags + np.sum(b_ex * exog_lags_all)
    y_hat_full[t] = y_t_hat

# Align open-loop outputs with y (starting at m)
y_hat_open = y_hat_full[m:]
y_true_open = y_full[m:]
time_open = df.index[m:]

print("Open-loop prediction done.")
print(f"RMSE (open-loop): {np.sqrt(np.mean((y_true_open - y_hat_open)**2)):.4f}")

import plotly.graph_objects as go
from plotly.subplots import make_subplots

# Create a figure with a secondary y-axis for the Heater
fig = make_subplots(specs=[[{"secondary_y": True}]])

# 1. Measured Temperature (Ground Truth)
fig.add_trace(
    go.Scatter(
        x=time_open,
        y=y_true_open,
        name="Measured Temp (True)",
        line=dict(color='black', width=1, dash='dot')
    ),
    secondary_y=False
)

# 2. Open-Loop Model Prediction
fig.add_trace(
    go.Scatter(
        x=time_open,
        y=y_hat_open,
        name="Open-Loop Prediction (Simulated)",
        line=dict(color='blue', width=2)
    ),
    secondary_y=False
)

# 3. Heater Power (Context)
# We access the heater column from the original dataframe using the same time index
# Checks if 'heat_input' exists in your dataframe (based on previous context)
if "heat_input" in df.columns:
    fig.add_trace(
        go.Scatter(
            x=time_open,
            y=df.loc[time_open, "heat_input"],
            name="Heater Power (W)",
            line=dict(color='red', width=1.5),
            opacity=0.3,
            fill='tozeroy' # Fills area to see ON/OFF clearly
        ),
        secondary_y=True
    )

# Formatting
fig.update_layout(
    title_text=f"Open-Loop Simulation Validation (RMSE: {np.sqrt(np.mean((y_true_open - y_hat_open)**2)):.4f})",
    hovermode="x unified",
    legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1)
)

fig.update_yaxes(title_text="Temperature (°C)", secondary_y=False)
fig.update_yaxes(title_text="Power (W)", secondary_y=True)

fig.show()

# Cell 6: Plot closed-loop (1-step-ahead) prediction vs true

plt.figure()
plt.plot(time_closed, y_true_closed, label="True Temp2", linewidth=1.0)
plt.plot(time_closed, y_hat_closed, label="ARX closed-loop (1-step-ahead)", linestyle="--", linewidth=1.0)
plt.title(f"ARX Closed-loop Prediction (lag_order = {lag_order})")
plt.xlabel("Time")
plt.ylabel("Temperature [°C]")
plt.legend()
plt.tight_layout()
plt.show()