# -*- coding: utf-8 -*-
"""Ecolar_RBPF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13LyUvfme9fM4VElbkKgTpvsJiYOjLrjQ
"""

!pip install filterpy

!pip install control

!pip install ruptures

from google.colab import files
import numpy as np
import math as math
import matplotlib.pyplot as plt
import pandas as pd
from scipy.integrate import solve_ivp
import os
import importlib.util
from datetime import datetime
from typing import Dict, Any, List, Optional, Union
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import plotly.graph_objects as go
from statsmodels.tsa.stattools import kpss
from statsmodels.tsa.stattools import adfuller
from scipy.signal import detrend
import warnings
import numpy as np
import cvxpy as cp
from scipy.linalg import expm, block_diag
from scipy.optimize import minimize
import numpy as np
from sklearn.linear_model import LinearRegression
from scipy.interpolate import interp1d
from sklearn.preprocessing import StandardScaler
from xgboost import XGBRegressor
from sklearn.linear_model import Lasso
from sklearn.linear_model import Ridge
from sklearn.pipeline import make_pipeline
from statsmodels.graphics.tsaplots import plot_acf
from lightgbm import LGBMRegressor
from numpy.random import default_rng
import control
from scipy.linalg import expm

def find_and_split_gaps(
    df: pd.DataFrame,
    min_lag_seconds: int,
    time_col: str = "Timestamp"
) -> list[pd.DataFrame]:
    """
    Identifies time gaps in a DataFrame, prints a report, and splits the
    DataFrame into a list of continuous segments.
    """
    if time_col not in df.columns:
        raise ValueError(f"Time column '{time_col}' not found in the DataFrame.")

    # 1. Ensure data is sorted by timestamp
    df_sorted = df.copy()
    df_sorted[time_col] = pd.to_datetime(df_sorted[time_col])
    df_sorted = df_sorted.sort_values(by=time_col).reset_index(drop=True)

    # 2. Calculate the time difference between consecutive rows in seconds
    time_diffs = df_sorted[time_col].diff().dt.total_seconds()

    # 3. Find the indices where a new segment begins (i.e., after a gap)
    gap_indices = df_sorted.index[time_diffs > min_lag_seconds].tolist()

    # 4. Report the found gaps
    if not gap_indices:
        print(f"No gaps larger than {min_lag_seconds} seconds found.")
        return [df_sorted]  # Return the original sorted DataFrame in a list

    #print(f" Found {len(gap_indices)} gap(s) larger than {min_lag_seconds} seconds.")
    #print("-" * 60)
    for idx in gap_indices:
        gap_start_time = df_sorted.loc[idx - 1, time_col]
        gap_end_time = df_sorted.loc[idx, time_col]
        actual_gap = (gap_end_time - gap_start_time).total_seconds()

        #print(f"Gap detected between:\n  - Start: {gap_start_time}\n  - End:   {gap_end_time}")
        #print(f"  - Duration: {actual_gap:,.2f} seconds\n")
    #print("-" * 60)


    # 5. Decompose the DataFrame into a list of continuous DFs
    split_points = [0] + gap_indices + [len(df_sorted)]
    list_of_dfs = []

    # Create pairs of start/end indices for slicing
    for i in range(len(split_points) - 1):
        start_idx = split_points[i]
        end_idx = split_points[i+1]
        segment = df_sorted.iloc[start_idx:end_idx].reset_index(drop=True)
        list_of_dfs.append(segment)

    print(f"DataFrame has been split into {len(list_of_dfs)} continuous segments.")
    return list_of_dfs

def interpolate_to_grid(df, dt_seconds=60, time_col="Timestamp", interpolate_cols=None):
    df = df.copy()
    df[time_col] = pd.to_datetime(df[time_col])
    df = df.sort_values(time_col, ignore_index=True)

    # Original timestamps in epoch seconds
    t_orig = df[time_col].astype("int64") // 10**9
    start  = int(np.ceil(t_orig.iloc[0] / dt_seconds) * dt_seconds)
    end    = int(np.floor(t_orig.iloc[-1] / dt_seconds) * dt_seconds)
    t_new  = np.arange(start, end + 1, dt_seconds, dtype=np.int64)

    # New timestamp index
    new_timestamps = pd.to_datetime(t_new, unit="s")
    out = {time_col: new_timestamps}

    # Handle columns to interpolate
    if interpolate_cols is None:
        # Default to all numeric (excluding time_col)
        interpolate_cols = df.select_dtypes(include=np.number).columns.tolist()
        interpolate_cols = [c for c in interpolate_cols if c != time_col]

    for col in interpolate_cols:
        out[col] = np.interp(t_new, t_orig.to_numpy(), df[col].to_numpy())

    # Build interpolated DataFrame
    df_interp = pd.DataFrame(out)
    other_cols = [c for c in df.columns if c not in interpolate_cols + [time_col]]
    if other_cols:
        df_aux = df[[time_col] + other_cols].set_index(time_col)
        df_aux = df_aux.reindex(df_interp[time_col], method="ffill").reset_index(drop=True)
        df_interp[other_cols] = df_aux[other_cols]

    return df_interp

# ────────────────────────────────────────────────────────────────────────────
# 1) LOAD  +  PRE‑PROCESS (Robust 15-Min Aggregation)
# ────────────────────────────────────────────────────────────────────────────
dt_seconds = 300  # 5 minutes 300s
csv_path   = "final_merged_dataframe_full_DWD4.csv"

# 1. Load, Parse, Sort, and Filter Dates
df = pd.read_csv(csv_path, parse_dates=["Timestamp"]).sort_values("Timestamp", ignore_index=True)
#df = df.loc[(df["Timestamp"] >= "2025-05-01 03:30") & (df["Timestamp"] <= "2025-05-29 23:00")].reset_index(drop=True) for paper
display(df)

df = df.loc[(df["Timestamp"] >= "2025-05-05 15:30") & (df["Timestamp"] <= "2025-05-30 23:00")].reset_index(drop=True)
# 2. Ensure Numeric Columns (Relays + PV)
relay_cols = ["Relay 4", "Relay 5"]
pv_cols    = ["my-pv1", "my-pv2", "my-pv3"]
for c in relay_cols + pv_cols:
    df[c] = pd.to_numeric(df[c], errors="coerce")

# 3. Calculate Power (Watts) on the original 5-min grid FIRST
#    We do this before resampling so we capture the true ON/OFF cycles.
df["heat_input"] = (df[pv_cols].sum(axis=1) + df[relay_cols].sum(axis=1)) * 1000.0

# 4.: Resample
df_15 = df.set_index("Timestamp").resample(f"{dt_seconds}s").agg({
    "Temp2": "mean",
    "Sensor_outside": "mean",
    "Other_room_temp": "mean",
    "heat_input": "first"
}).dropna().reset_index()

# 5. Gap Detection
list_of_dfs = find_and_split_gaps(df=df_15, min_lag_seconds=dt_seconds + 60)
base_df = max(list_of_dfs, key=len)

# 6. Final Formatting
base_cols = ["Timestamp", "Temp2", "Sensor_outside", "Other_room_temp", "heat_input"]
base_df   = base_df[base_cols].copy().reset_index(drop=True)

print(f"--- Processing Complete ---")
print(f"Grid Step: {dt_seconds} seconds (15 min)")
print(f"Rows: {len(base_df)}")
print(f"Time range: {base_df['Timestamp'].min()} to {base_df['Timestamp'].max()}")
print("Head of Data:")
display(base_df.head())

# ─────────────────────────────────────────────────────────────────────────────
# 2) PREPARE DATA FOR OPTIMIZATION
# ─────────────────────────────────────────────────────────────────────────────

u_train    = base_df["heat_input"].to_numpy(dtype=float)      # The heater (Watts)
T_out_train= base_df["Sensor_outside"].to_numpy(dtype=float)  # Boundary 1 (Celsius)
T_or_train = base_df["Other_room_temp"].to_numpy(dtype=float) # Boundary 2 (Celsius)
y_train    = base_df["Temp2"].to_numpy(dtype=float)           # The Target (Celsius)
time_steps  = base_df["Timestamp"]
dt = dt_seconds  # seconds

# 3. Print shapes to confirm
print(f"Training Data Shapes:")
print(f"  u (Heater):      {u_train.shape}")
print(f"  T_out (Outside): {T_out_train.shape}")
print(f"  y (Target):      {y_train.shape}")
print(f"  dt:              {dt} seconds")

import plotly.graph_objects as go
from plotly.subplots import make_subplots

# Create a figure with a secondary y-axis (for the Heater Power)
fig = make_subplots(specs=[[{"secondary_y": True}]])

# 1. Indoor Temperature (Target) - Left Axis
fig.add_trace(
    go.Scatter(
        x=base_df["Timestamp"],
        y=base_df["Temp2"],
        name="Indoor Temp (Target)",
        mode='lines',
        line=dict(color='blue', width=2)
    ),
    secondary_y=False,
)

# 2. Outside Temperature (Disturbance) - Left Axis
fig.add_trace(
    go.Scatter(
        x=base_df["Timestamp"],
        y=base_df["Sensor_outside"],
        name="Outside Temp",
        mode='lines',
        line=dict(color='green', width=1.5, dash='dash')
    ),
    secondary_y=False,
)

# 3. Other Room Temperature (Disturbance) - Left Axis
fig.add_trace(
    go.Scatter(
        x=base_df["Timestamp"],
        y=base_df["Other_room_temp"],
        name="Other Room Temp",
        mode='lines',
        line=dict(color='orange', width=1.5, dash='dot')
    ),
    secondary_y=False,
)

# 4. Heater Power (Input) - RIGHT Axis
fig.add_trace(
    go.Scatter(
        x=base_df["Timestamp"],
        y=base_df["heat_input"],
        name="Heater Power (W)",
        mode='lines', # or 'lines+markers'
        line=dict(color='red', width=1),
        fill='tozeroy', # Optional: fills area under the heater curve
        opacity=0.3      # Semi-transparent so it doesn't block other lines
    ),
    secondary_y=True,
)

# Layout details
fig.update_layout(
    title_text="Training Data: Temperatures vs Heater Power",
    hovermode="x unified",  # Shows all values when you hover over a specific time
    legend=dict(
        orientation="h",
        yanchor="bottom",
        y=1.02,
        xanchor="right",
        x=1
    )
)

# Set x-axis title
fig.update_xaxes(title_text="Timestamp")

# Set y-axes titles
fig.update_yaxes(title_text="Temperature (°C)", secondary_y=False)
fig.update_yaxes(title_text="Power (Watts)", secondary_y=True)

fig.show()

import numpy as np
from scipy.optimize import minimize
from scipy.signal import cont2discrete

# ─────────────────────────────────────────────────────────────────────────────
# 4-state CT model: Air + Two Walls + Heater Node (10 Parameters)
# ─────────────────────────────────────────────────────────────────────────────

# Keys (10 parameters now)
POS_KEYS_4C = [
    "C_air", "C_wall_out", "C_wall_in", "C_heater",  # Capacities [J/K]
    "g_air_ow", "g_air_iw", "g_air_outside",         # Air connectivity [W/K]
    "g_wo_outside", "g_wi_other",                    # Walls -> Boundary [W/K]
    "g_air_heater"                                   # Heater -> Air [W/K]
]

def build_system_ct_4nodes(pos):
    """
    Return continuous-time (A_c, B_u, F_out, F_or, R) for the 4-state model.
    States: [T_air, T_wall_out, T_wall_in, T_heater]
    """
    # Unpack Capacities
    Ca  = float(pos["C_air"])
    Cwo = float(pos["C_wall_out"])
    Cwi = float(pos["C_wall_in"])
    Ch  = float(pos["C_heater"])

    # Unpack Conductances
    g_ao    = float(pos["g_air_ow"])
    g_ai    = float(pos["g_air_iw"])
    g_ao_ut = float(pos["g_air_outside"]) # Infiltration
    g_wo    = float(pos["g_wo_outside"])
    g_wi    = float(pos["g_wi_other"])
    g_ah    = float(pos["g_air_heater"])

    # Inverse Capacitance Matrix
    # Order: Air, Wall_Out, Wall_In, Heater
    Cinv = np.diag(1.0 / np.maximum([Ca, Cwo, Cwi, Ch], 1e-12))

    # Symmetric Conductance Matrix R (4x4)
    # 0: Air, 1: WO, 2: WI, 3: Heater
    R = np.zeros((4, 4), float)

    # Off-diagonals (Couplings)
    R[0, 1] = R[1, 0] = g_ao  # Air <-> Wall Out
    R[0, 2] = R[2, 0] = g_ai  # Air <-> Wall In
    R[0, 3] = R[3, 0] = g_ah  # Air <-> Heater

    # Diagonals (Sum of connections + leaks)
    R[0, 0] = -(g_ao + g_ai + g_ah + g_ao_ut) # Air loses to walls, heater, and outside
    R[1, 1] = -(g_ao + g_wo)                  # Wall Out loses to Air and Outside
    R[2, 2] = -(g_ai + g_wi)                  # Wall In loses to Air and Other Room
    R[3, 3] = -(g_ah)                         # Heater only loses to Air (assuming no back-loss)

    # Continuous-time state matrix
    A_c = Cinv @ R

    # Inputs
    # B_u: Electrical power u enters the HEATER node (State 3)
    B_u = Cinv @ np.array([[0.0, 0.0, 0.0, 1.0]]).T

    # F_out: Outside temp affects Air (infiltration) and Wall Out
    F_out  = Cinv @ np.array([[g_ao_ut, 0.0, 0.0, 0.0]]).T
    F_out += Cinv @ np.array([[0.0, g_wo, 0.0, 0.0]]).T

    # F_or: Other Room temp affects Wall In
    F_or = Cinv @ np.array([[0.0, 0.0, g_wi, 0.0]]).T

    return A_c, B_u, F_out, F_or, R

# ─────────────────────────────────────────────────────────────────────────────
# ZOH Discretization (Same logic, handles n=4 automatically)
# ─────────────────────────────────────────────────────────────────────────────
def c2d_zoh(A, B, dt):
    n = A.shape[0]
    m = B.shape[1]
    C_dummy = np.eye(n)
    D_dummy = np.zeros((n, m))
    Ad, Bd, _, _, _ = cont2discrete((A, B, C_dummy, D_dummy), dt, method='zoh')
    return Ad, Bd

def build_system_d_4nodes(pos, dt):
    """Bundle CT → DT system using ZOH discretization."""
    A_c, B_u, F_out, F_or, R = build_system_ct_4nodes(pos)

    # Stack inputs: [u, T_out, T_or]
    B = np.column_stack([B_u, F_out, F_or])

    Phi, Gamma = c2d_zoh(A_c, B, dt)
    return Phi, Gamma, R

# ─────────────────────────────────────────────────────────────────────────────
# Simulation / Loss / Bounds
# ─────────────────────────────────────────────────────────────────────────────
def z_to_params_4c(z):
    """Converts the 10-element parameter vector z into the parameter dictionary."""
    z = np.asarray(z, float)
    # z now contains only the 10 physical parameters
    pos_vals = z[:10]
    pos = {k: float(v) for k, v in zip(POS_KEYS_4C, pos_vals)}
    return pos

def simulate_open_loop_4c(z, u, T_out, T_or, y, dt, return_states=False):
    """
    Open-loop simulation using ZOH.
    Initial state is fixed by a physical heuristic.
    """
    # z contains only 10 physical parameters now
    pos = z_to_params_4c(z)
    Phi, Gamma, R = build_system_d_4nodes(pos, dt)

    N = len(u)
    X = np.zeros((N, 4), float) # 4 States

    # --- FIXED INITIAL CONDITIONS (Heuristic) ---
    # T_air[0] = y[0] (Measured)
    # T_wall_out[0] = T_out[0] (Outside temp)
    # T_wall_in[0] = y[0] (Room temp)
    # T_heater[0] = y[0] (Room temp)
    x = np.array([y[0], T_out[0], y[0], y[0]], float)
    X[0] = x

    for k in range(N - 1):
        U_vec = np.array([u[k], T_out[k], T_or[k]], float)
        x = Phi @ x + Gamma @ U_vec

        # Stability check
        if not np.all(np.isfinite(x)) or np.any(np.abs(x) > 1e4):
            if return_states:
                return None, None, Phi, Gamma, R
            return None, Phi, Gamma, R
        X[k + 1] = x

    y_hat = X[:, 0] # Return Air Temp
    return (y_hat, X, Phi, Gamma, R) if return_states else (y_hat, Phi, Gamma, R)

def loss_open_loop_z_4c(z, u, T_out, T_or, y, dt, warmup_seconds=0.0):
    """
    Loss function for optimization. Note: z is only the 10 physical parameters.
    The initial state is determined inside simulate_open_loop_4c.
    """
    y_hat, Phi, Gamma, R = simulate_open_loop_4c(z, u, T_out, T_or, y, dt)
    if y_hat is None:
        return 1e12

    W = int(round(max(0.0, warmup_seconds) / dt))
    # We always skip the first point y[0] because it's used for initialization
    err = y_hat[1 + W:] - y[1 + W:]
    return float(np.mean(err * err))

def _set_bounds_4c():
    """Returns bounds for the 10 physical parameters only."""
    b = []
    # --- Capacities (J/K) ---
    b += [(1.8e4, 3.0e7)]   # C_air
    b += [(1.0e5, 2.0e7)]   # C_wall_out
    b += [(1.0e5, 2.0e7)]   # C_wall_in
    b += [(1.0e2, 5.0e5)]   # C_heater

    # --- Conductances (W/K) ---
    b += [(1.0, 9000.0)]    # g_air_ow
    b += [(1.0, 9000.0)]    # g_air_iw
    b += [(0.0, 20.0)]      # g_air_outside
    b += [(10.0, 9000.0)]   # g_wo_outside
    b += [(10.0, 9000.0)]   # g_wi_other
    b += [(5.0, 5000.0)]    # g_air_heater

    return b

import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import minimize

# Assuming the modified helper functions (z_to_params_4c, simulate_open_loop_4c, _set_bounds_4c, loss_open_loop_z_4c)
# from the previous step are accessible.

# ─────────────────────────────────────────────────────────────────────────────
# 1) SETUP INITIAL GUESSES (4-NODE PHYSICS - 10 Parameters)
# ─────────────────────────────────────────────────────────────────────────────
# Updated Units list for 10 parameters
POS_UNITS_4C = [
    "J/K", "J/K", "J/K", "J/K",  # C_air, C_wo, C_wi, C_heater
    "W/K", "W/K", "W/K",         # g_ao, g_ai, g_inf
    "W/K", "W/K",                # g_wo_ext, g_wi_oth
    "W/K"                        # g_air_heater
]

# --- Geometry / Constants (Ensure these variables are defined in the environment) ---
# dt = dt_seconds
# rho_air, cp_air = 1.225, 1007.0
# V_room = 182.52
# area_ow = 200.0, area_iw = 30.36, alpha_in = 8.0, UA_out_target = 60.0, UA_or_target = 45.0
# T_out_train, y_train are available NumPy arrays.

dt = dt_seconds  # Example: 900.0 (Assuming dt_seconds is defined)
rho_air, cp_air = 1.225, 1007.0
V_room  = 182.52
area_ow   = 200.0
area_iw   = 30.36
alpha_in  = 8.0
UA_out_target = 60.0
UA_or_target  = 45.0


# --- 1. Capacities [J/K] ---
C_air0    = rho_air * cp_air * V_room
C_wo0     = 4.0e6
C_wi0     = 3.0e6
C_heater0 = 5.0e4

# --- 2. Conductances [W/K] ---
g_air_ow0 = alpha_in * area_ow
g_air_iw0 = alpha_in * area_iw
g_wo_outside0 = 1.0 / max(1.0/UA_out_target - 1.0/g_air_ow0, 1e-12)
g_wi_other0   = 1.0 / max(1.0/UA_or_target - 1.0/g_air_iw0, 1e-12)
g_air_outside0 = 2.0
g_air_heater0  = 300.0

# Pack Physical Parameters (10 values)
pos0_vals = np.array([
    C_air0, C_wo0, C_wi0, C_heater0,
    g_air_ow0, g_air_iw0, g_air_outside0,
    g_wo_outside0, g_wi_other0,
    g_air_heater0
], float)

# --- 3. Initial State is NO LONGER OPTIMIZED. ---
# The optimization vector z_start now ONLY contains the 10 physical parameters.
z_start = pos0_vals.copy()

# Get Bounds (Uses the updated _set_bounds_4c with only 10 items)
bounds = _set_bounds_4c()

# ─────────────────────────────────────────────────────────────────────────────
# 2) RUN OPTIMIZATION (4-NODE)
# ─────────────────────────────────────────────────────────────────────────────
# T_out_train, T_or_train, y_train are available from prior steps.
print(f"Starting Optimization with {len(z_start)} physical parameters...")

res = minimize(
    fun=loss_open_loop_z_4c,
    x0=z_start,
    # Note: Initial state is handled inside simulate_open_loop_4c using the heuristic.
    args=(u_train, T_out_train, T_or_train, y_train, dt, 0.0),
    method="L-BFGS-B",
    bounds=bounds,
    options={"maxiter": 2000, "ftol": 1e-12, "disp": True}
)

print(f"\nOptimization Success: {res.success}")
print(f"Final MSE Loss: {res.fun:.6f}")

# ─────────────────────────────────────────────────────────────────────────────
# 3) VISUALIZE & REPORT
# ─────────────────────────────────────────────────────────────────────────────
# Run one final simulation with the best parameters
best_z = res.x
# The simulation function now internally uses the heuristic for the initial state.
y_hat, X_states, Phi, Gamma, R = simulate_open_loop_4c(
    best_z, u_train, T_out_train, T_or_train, y_train, dt, return_states=True
)

# Extract physical names (z_to_params_4c now only returns the dict)
best_pos = z_to_params_4c(best_z)

# --- PLOTTING ---
plt.figure(figsize=(12, 10))

# Subplot 1: Temperature Fit (Air)
plt.subplot(3, 1, 1)
plt.plot(base_df["Timestamp"], y_train, 'k-', alpha=0.6, label="Measured (Air)")
plt.plot(base_df["Timestamp"], y_hat, 'r--', linewidth=2, label="Model Prediction (Air)")
plt.ylabel("Air Temp [°C]")
plt.title(f"4-State Model Fit (MSE: {res.fun:.4f})")
plt.legend()
plt.grid(True, alpha=0.3)

# Subplot 2: Wall Temperatures
plt.subplot(3, 1, 2)
# X_states indices: 0=Air, 1=Wall_Out, 2=Wall_In, 3=Heater
plt.plot(base_df["Timestamp"], X_states[:, 1], color='orange', label="Est. Wall Outer Core")
plt.plot(base_df["Timestamp"], X_states[:, 2], color='green', label="Est. Wall Inner Core")
plt.plot(base_df["Timestamp"], T_out_train, color='blue', alpha=0.2, label="Outside Temp (Ref)")
plt.ylabel("Wall Temp [°C]")
plt.legend(loc="upper right")
plt.grid(True, alpha=0.3)

# Subplot 3: Heater Temperature (The New State)
plt.subplot(3, 1, 3)
plt.plot(base_df["Timestamp"], X_states[:, 3], color='red', label="Est. Heater Core Temp")
# Overlay air for context
plt.plot(base_df["Timestamp"], y_hat, color='gray', linestyle=':', alpha=0.5, label="Air Temp (Context)")
plt.ylabel("Heater Temp [°C]")
plt.legend(loc="upper right")
plt.grid(True, alpha=0.3)
plt.xlabel("Timestamp")

plt.tight_layout()
plt.show()

# --- PRINT PARAMETERS ---
print("\n--- Identified Physical Parameters (4-Node) ---")
print(f"{'Parameter':<15} | {'Value':<12} | {'Unit'}")
print("-" * 40)
units = POS_UNITS_4C
for (k, v), u in zip(best_pos.items(), units):
    print(f"{k:<15} : {v:<12.4f}   {u}")

import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import minimize
from scipy.signal import cont2discrete

# │───────────────────────────────────────────────────────────────
# 1) SETTINGS & HYPERPARAMETERS
# │────────────────────────────────────────────────────────────────
Np = 20000          # Number of Particles
dt_seconds = dt_seconds        # Time step (should be 900s / 15 mins)
sigma_y_pf = 0.1          # Measurement noise (Temp2) 0.1 for opti
print(f"RBPF running with dt: {dt_seconds}s")

# Baseline process noise (per-state) [Air, Wall_Out, Wall_In, Heater]
# Added 4th value for Heater noise
q_states = np.array([0.03, 0.03, 0.03, 0.03], float)

# Global SV (Random Walk on log alpha)
alpha_min, alpha_max = 0.01, 15.0 #0.01, 15.0
sigma_eta_post = 0.05

# Liu–West (log-space)
a_lw   = 0.99
h2_lw = 1.0 - a_lw**2

# Gating (Alpha-based)
g_min = 0.05       # Minimum learning rate
F_quiet = 0.4     # Bottom 40% = Quiet
F_burst = 0.95     # Top 5% = Burst

# Resampling
resample_frac = 0.5

# Mixture sampling counts
Nsamp_mixture_state = 2000

# │────────────────────────────────────────────────────────────────
# 2) HELPERS
# │────────────────────────────────────────────────────────────────
def systematic_resample(w, rng):
    N = w.size
    u0 = (rng.random() + np.arange(N)) / N
    cs = np.cumsum(w)
    idx = np.empty(N, int)
    i = j = 0
    while i < N:
        if u0[i] < cs[j]:
            idx[i] = j
            i += 1
        else:
            j += 1
    return idx

def wquantile(x, w, qs):
    x = np.asarray(x); w = np.asarray(w)
    i = np.argsort(x)
    xs, ws = x[i], w[i]
    cw = np.cumsum(ws)
    if cw[-1] > 0: cw /= cw[-1]
    else: cw = np.linspace(1/len(ws), 1, len(ws))
    return np.interp(qs, cw, xs)

def logsumexp(v):
    m = np.max(v)
    return m + np.log(np.sum(np.exp(v - m)))

def sample_from_weighted_gaussian_mixture(means, variances, weights, Nsamp, rng):
    weights = np.asarray(weights, float)
    cw = np.cumsum(weights)
    if cw[-1] > 0: cw /= cw[-1]
    else: cw = np.linspace(1/len(weights), 1, len(weights))
    u = (rng.random(Nsamp) + np.arange(Nsamp)) / Nsamp
    idx = np.searchsorted(cw, u, side='right')
    idx = np.clip(idx, 0, len(weights)-1)
    stds = np.sqrt(np.maximum(variances[idx], 1e-12))
    return means[idx] + stds * rng.standard_normal(Nsamp)

# --- UPDATED HELPER FOR 4 STATES ---
def get_continuous_matrices_4state(theta_arr):
    """
    Returns Continuous-time A_c and B_c for N particles (4-State Model).
    States: [T_air, T_wo, T_wi, T_heater]
    Output shapes: (Np, 4, 4) and (Np, 4, 3)
    """
    Np_loc = theta_arr.shape[0]

    # Unpack columns (Now 10 parameters)
    # 0:Ca, 1:Cwo, 2:Cwi, 3:Cheater,
    # 4:gao, 5:gai, 6:gao_ext, 7:gwo_ext, 8:gwi_oth, 9:gah
    Ca      = theta_arr[:, 0]
    Cwo     = theta_arr[:, 1]
    Cwi     = theta_arr[:, 2]
    Ch      = theta_arr[:, 3]
    gao     = theta_arr[:, 4]
    gai     = theta_arr[:, 5]
    gao_ext = theta_arr[:, 6]
    gwo_ext = theta_arr[:, 7]
    gwi_oth = theta_arr[:, 8]
    gah     = theta_arr[:, 9]

    # --- Build A_c (Dynamics 4x4) ---
    A = np.zeros((Np_loc, 4, 4))

    # Row 0: Air (Connects to WO, WI, Heater, Outside)
    A[:,0,0] = -(gao + gai + gah + gao_ext) / Ca
    A[:,0,1] = gao / Ca
    A[:,0,2] = gai / Ca
    A[:,0,3] = gah / Ca   # From Heater

    # Row 1: Wall Out (Connects to Air, Outside)
    A[:,1,0] = gao / Cwo
    A[:,1,1] = -(gao + gwo_ext) / Cwo

    # Row 2: Wall In (Connects to Air, Other Room)
    A[:,2,0] = gai / Cwi
    A[:,2,2] = -(gai + gwi_oth) / Cwi

    # Row 3: Heater (Connects to Air)
    A[:,3,0] = gah / Ch
    A[:,3,3] = -gah / Ch

    # --- Build B_c (Inputs 4x3) ---
    # Input Vector U: [u (Power), T_out, T_or]
    B = np.zeros((Np_loc, 4, 3))

    # Row 0: Air (Infiltration) - Note: Power no longer goes here directly
    B[:,0,1] = gao_ext / Ca      # T_out -> Air

    # Row 1: Wall Out (Outside Temp)
    B[:,1,1] = gwo_ext / Cwo     # T_out -> Wall Out

    # Row 2: Wall In (Other Room Temp)
    B[:,2,2] = gwi_oth / Cwi     # T_or -> Wall In

    # Row 3: Heater Node (Gets the Power Input)
    B[:,3,0] = 1.0 / Ch          # u -> Heater Node

    return A, B

# │────────────────────────────────────────────────────────────────
# 3) DATA PREPARATION & INITIALIZATION
# │────────────────────────────────────────────────────────────────
# Extract arrays from base_df
Y_meas     = base_df["Temp2"].to_numpy(dtype=float)
u_arr      = base_df["heat_input"].to_numpy(dtype=float)
T_out_arr = base_df["Sensor_outside"].to_numpy(dtype=float)
T_or_arr   = base_df["Other_room_temp"].to_numpy(dtype=float)

N = len(Y_meas)
rng = np.random.default_rng(42)

# Measurement Matrix: We observe State 0 (Air)
C_y = np.array([[1, 0, 0, 0]], float)

# Parameter Definitions (10)
theta_names = [
    "C_air", "C_wo", "C_wi", "C_heater",
    "g_ao", "g_ai", "g_ao_ext", "g_wo_ext", "g_wi_other",
    "g_ah"
]
d_theta = len(theta_names)

# Define Ranges (omitted for brevity, assuming they are defined correctly)
_param_defaults = {
    "C_air":      (1.8e4, 8.0e6),
    "C_wo":      (1.0e5, 2.0e7),
    "C_wi":      (1.0e5, 2.0e7),
    "C_heater": (1e2, 5.0e5),
    "g_ao":      (1, 9000.0),
    "g_ai":      (1, 9000.0),
    "g_ao_ext": (0, 9000.0),
    "g_wo_ext": (10, 9000.0),
    "g_wi_other":(10, 9000.0),
    "g_ah":      (5.0, 5000.0)
}

theta_lo = np.empty(d_theta, float)
theta_hi = np.empty(d_theta, float)
theta_eps = 1e-20
for j, nm in enumerate(theta_names):
    spec = _param_defaults[nm]
    theta_lo[j] = max(float(spec[0]), theta_eps)
    theta_hi[j] = max(float(spec[1]), theta_eps)

# --- UPDATED STATE INITIALIZATION LOGIC ---
T_air_start = float(Y_meas[0])
T_out_start = float(T_out_arr[0]) # Get initial outside temperature

# Initialize the mean state vector for all particles using the heuristic:
# [T_air_start, T_out_start, T_air_start, T_air_start]
m_initial_mean = np.array([T_air_start, T_out_start, T_air_start, T_air_start], float)

# Create (Np, 4) matrix m initialized around this mean
m = np.tile(m_initial_mean, (Np, 1))
m += rng.normal(0, 0.5, size=m.shape) # Add initial noise

# Covariance 4x4
P0 = np.diag([0.5**2, 2.0**2, 2.0**2, 5.0**2])
P   = np.tile(P0, (Np, 1, 1))

# Initialize Alpha (omitted for brevity, remains unchanged)
log_alpha = rng.normal(0.0, 0.1, size=Np)
log_alpha = np.clip(log_alpha, np.log(alpha_min), np.log(alpha_max))
alpha      = np.exp(log_alpha)

# Initialize Theta (Log-Uniform - omitted for brevity, remains unchanged)
phi_lo = np.log(theta_lo)
phi_hi = np.log(theta_hi)
phi      = rng.uniform(low=phi_lo[None, :], high=phi_hi[None, :], size=(Np, d_theta))
theta    = np.exp(phi)

logw = np.full(Np, -np.log(Np), float)
Q0_diag = q_states**2
R = np.array([[sigma_y_pf**2]], float)

# Storage & Diagnostics (omitted for brevity, remains unchanged)
regime_flag = np.zeros(N, dtype=int)
z_std_innov = np.zeros(N)

n_bins_alpha = 30
log_alpha_min = np.log(alpha_min)
log_alpha_max = np.log(alpha_max)
alpha_bin_edges = np.linspace(log_alpha_min, log_alpha_max, n_bins_alpha + 1)
alpha_hist_counts = np.full(n_bins_alpha, 1.0, dtype=float)

q_lo, q_md, q_hi = 0.025, 0.50, 0.975
Ti_lo = np.zeros(N); Ti_md = np.zeros(N); Ti_hi = np.zeros(N)
Y_pred_mean = np.full(N, np.nan)
Y_pred_std   = np.full(N, np.nan)

Th_lo = np.zeros((N, d_theta))
Th_md = np.zeros((N, d_theta))
Th_hi = np.zeros((N, d_theta))

Alpha_lo = np.zeros(N)
Alpha_md = np.zeros(N)
Alpha_hi = np.zeros(N)

# │────────────────────────────────────────────────────────────────
# 4) MAIN RBPF LOOP (EULER SUB-STEPPING - 4 STATE)
# │────────────────────────────────────────────────────────────────
const_ll = -0.5 * np.log(2*np.pi)
I4_batch = np.eye(4)[None, :, :]    # Identity matrix 4x4

print(f"Starting RBPF on {N} samples with {Np} particles (4-State Sub-Stepping)...")

for k in range(1, N):
    # Inputs at k-1
    uk   = u_arr[k-1]
    Tok   = T_out_arr[k-1]
    Tork = T_or_arr[k-1]

    # Measurement at k
    yk = float(Y_meas[k])

    w_lin_prior = np.exp(logw - logsumexp(logw))

    # --- (A) Global SV Step --- (Unchanged)
    log_alpha = log_alpha + rng.normal(0.0, sigma_eta_post, size=Np)
    log_alpha = np.clip(log_alpha, np.log(alpha_min), np.log(alpha_max))
    alpha     = np.exp(log_alpha)

    # --- (B) Alpha Gating Logic --- (Unchanged)
    alpha_med_k = wquantile(alpha, w_lin_prior, [0.5])[0]
    log_alpha_med_k = np.log(np.clip(alpha_med_k, alpha_min, alpha_max))

    bin_idx = np.searchsorted(alpha_bin_edges, log_alpha_med_k, side='right') - 1
    bin_idx = np.clip(bin_idx, 0, n_bins_alpha - 1)
    alpha_hist_counts[bin_idx] += 1.0

    cdf_bins = np.cumsum(alpha_hist_counts)
    cdf_bins /= cdf_bins[-1]
    F_k = cdf_bins[bin_idx]

    if F_k <= F_quiet:
        g_alpha, regime_flag[k] = 1.0, 0
    elif F_k >= F_burst:
        g_alpha, regime_flag[k] = g_min, 1
    else:
        r = (F_burst - F_k) / (F_burst - F_quiet + 1e-12)
        g_alpha = g_min + (1.0 - g_min) * r
        regime_flag[k] = 0

    g_k = max(g_alpha, g_min)

    # --- (C) Liu-West Step (Parameter Update) --- (Unchanged)
    phi = np.log(np.clip(theta, theta_eps, None))

    a_k   = 1.0 - g_k * (1.0 - a_lw)
    h2_k = g_k * h2_lw

    phi_bar_free = np.sum(phi * w_lin_prior[:, None], axis=0)
    diff_free     = phi - phi_bar_free[None, :]
    V_free      = diff_free.T @ (diff_free * w_lin_prior[:, None])
    V_free      = 0.5 * (V_free + V_free.T) + 1e-12 * np.eye(d_theta)

    L_free   = np.linalg.cholesky(V_free)
    eps_free = rng.standard_normal((Np, d_theta)) @ (np.sqrt(h2_k) * L_free.T)

    phi   = a_k * phi + (1.0 - a_k) * phi_bar_free[None, :] + eps_free
    phi   = np.clip(phi, phi_lo[None, :], phi_hi[None, :])
    theta = np.exp(phi)

    # --- (D) Kalman Predict Step (Sub-Stepped Euler) --- (Unchanged)
    # 1. Get continuous matrices (4x4)
    A_c, B_c = get_continuous_matrices_4state(theta)

    # 2. Setup Sub-stepping
    dt_total = dt_seconds
    n_subs   = 15
    dt_sub   = dt_total / n_subs

    # 3. Prepare Inputs (Np, 3)
    U_vec = np.column_stack([
        np.full(Np, uk),
        np.full(Np, Tok),
        np.full(Np, Tork)
    ])

    # 4. Integrate State (The "Micro-Loop")
    m_pred = m.copy()

    for _ in range(n_subs):
        # dx/dt = A*x + B*u (All 4x4 or 4x3)
        dx = np.einsum('nij,nj->ni', A_c, m_pred) + \
             np.einsum('nij,nj->ni', B_c, U_vec)
        m_pred += dx * dt_sub

    # 5. Predict Covariance P (One-shot Approximation)
    Phi_approx = I4_batch + (A_c * dt_total)

    # P = Phi * P * Phi'
    P_pred = np.einsum('nij,njk,nlk->nil', Phi_approx, P, Phi_approx)

    # Add Process Noise (Now 4-state diagonal)
    scale_sq = np.exp(2.0 * log_alpha)
    qdiag    = scale_sq[:, None] * Q0_diag[None, :]
    for s in range(4): # Loop over 4 states
        P_pred[:, s, s] += qdiag[:, s]

    # --- (E) Likelihood & Weight Update --- (Unchanged)
    # y_hat = C * m_pred
    y_pred = (m_pred @ C_y.T).ravel()

    # S = C P C' + R
    S = np.einsum('ij,njk,kl->n', C_y, P_pred, C_y.T) + R[0, 0]
    S = np.maximum(S, 1e-12)

    innov = yk - y_pred
    ll    = const_ll - 0.5*np.log(S) - 0.5*(innov**2)/S
    logw  = logw + ll
    logw  = logw - logsumexp(logw)
    w_lin_post = np.exp(logw)

    # Save Stats
    mu_k   = np.sum(w_lin_prior * y_pred)
    var_k = np.sum(w_lin_prior * (y_pred**2 + S)) - mu_k**2
    Y_pred_mean[k] = mu_k
    Y_pred_std[k]   = np.sqrt(max(var_k, 1e-12))
    z_std_innov[k] = (yk - mu_k) / np.sqrt(max(var_k, 1e-12))

    # --- (F) Kalman Update Step --- (Unchanged)
    K = (P_pred @ C_y.T) / S[:, None, None]    # (Np, 4, 1)
    m = m_pred + (K.reshape(Np, 4) * innov[:, None])

    KC = np.matmul(K, C_y)
    P   = np.matmul(I4_batch - KC, P_pred)

    # Store Air Temp Quantiles (Unchanged)
    Ti_draws = sample_from_weighted_gaussian_mixture(
        m[:, 0], P[:, 0, 0], w_lin_post, Nsamp_mixture_state, rng
    )
    Ti_lo[k], Ti_md[k], Ti_hi[k] = np.quantile(Ti_draws, [q_lo, q_md, q_hi])

    # Parameter and Alpha quantiles (Unchanged)
    for j in range(d_theta):
        Th_lo[k, j], Th_md[k, j], Th_hi[k, j] = wquantile(
            theta[:, j], w_lin_post, [q_lo, q_md, q_hi]
        )

    Alpha_lo[k], Alpha_md[k], Alpha_hi[k] = wquantile(
        alpha, w_lin_post, [q_lo, q_md, q_hi]
    )

    # --- (G) Resampling --- (Unchanged)
    Neff = 1.0 / np.sum(w_lin_post**2)
    if Neff < resample_frac * Np:
        idx = systematic_resample(w_lin_post, rng)
        m   = m[idx]
        P   = P[idx]
        log_alpha = log_alpha[idx]
        alpha = alpha[idx]
        theta = theta[idx]
        logw[:] = -np.log(Np)

print("RBPF Complete.")

import matplotlib.pyplot as plt
import math

# ─────────────────────────────────────────────────────────────────────────────
# 1) PLOT PARAMETER TRAJECTORIES (Learning Curves)
# ─────────────────────────────────────────────────────────────────────────────
# We now have 10 parameters, so we need a larger grid (e.g., 4 rows x 3 cols = 12 slots)
n_params = len(theta_names)
n_cols = 3
n_rows = math.ceil(n_params / n_cols)

fig, axes = plt.subplots(n_rows, n_cols, figsize=(16, 12), sharex=True)
axes = axes.flatten()

timestamps = base_df["Timestamp"].iloc[:N]

for j, name in enumerate(theta_names):
    ax = axes[j]

    # Extract quantiles for this parameter
    p_lo = Th_lo[:, j]
    p_md = Th_md[:, j]
    p_hi = Th_hi[:, j]

    # Plot Confidence Interval (Shaded)
    ax.fill_between(timestamps, p_lo, p_hi, color='blue', alpha=0.2, label="95% CI")

    # Plot Median (Solid Line)
    ax.plot(timestamps, p_md, color='blue', linewidth=1.5, label="Median")

    ax.set_title(name)
    ax.grid(True, alpha=0.3)

# Hide any unused subplots (e.g., if we have 10 params in a 12-plot grid)
for k in range(n_params, len(axes)):
    axes[k].set_visible(False)

# Layout adjustments
handles, labels = axes[0].get_legend_handles_labels()
fig.legend(handles, labels, loc='upper right')
plt.suptitle(f"RBPF Parameter Estimation (Time Evolution) - 4 State Model", fontsize=16)
plt.tight_layout(rect=[0, 0.03, 1, 0.95])
plt.show()

# ─────────────────────────────────────────────────────────────────────────────
# 3) PRINT FINAL PARAMETER ESTIMATES
# ─────────────────────────────────────────────────────────────────────────────
print("\n=== Final Parameter Estimates (Median at t=N) ===")
print(f"{'Parameter':<15} | {'Median':<12} | {'95% CI (Low - High)'}")
print("-" * 65)

for j, name in enumerate(theta_names):
    med = Th_md[-1, j]
    lo  = Th_lo[-1, j]
    hi  = Th_hi[-1, j]
    print(f"{name:<15} : {med:<12.4f} | ({lo:.4f} - {hi:.4f})")

import numpy as np
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# ─────────────────────────────────────────────────────────────────────────────
# 1) CALCULATE COVERAGE METRICS
# ─────────────────────────────────────────────────────────────────────────────
# Align arrays (Skip k=0 as usual)
y_true = Y_meas[1:]
y_est  = Ti_md[1:]   # Median estimate
y_lb   = Ti_lo[1:]   # 2.5% Quantile
y_ub   = Ti_hi[1:]   # 97.5% Quantile
time_v = base_df["Timestamp"].iloc[1:]

# Boolean mask: Is observation inside the 95% CI?
is_covered = (y_true >= y_lb) & (y_true <= y_ub)

# Metrics
coverage_pct = np.mean(is_covered) * 100.0
avg_width    = np.mean(y_ub - y_lb)
rmse_closed  = np.sqrt(np.mean((y_true - y_est)**2))
num_violations = np.sum(~is_covered)

print(f"=== Closed-Loop RBPF Coverage Analysis ===")
print(f"Target Confidence Level: 95.0%")
print(f"Actual Coverage:         {coverage_pct:.2f}%")
print(f"Average CI Width:        {avg_width:.3f} °C")
print(f"Closed-Loop RMSE:        {rmse_closed:.3f} °C")
print(f"Violations:              {num_violations} out of {len(y_true)} steps")

# Check Calibration Status
if coverage_pct < 90.0:
    print(">> STATUS: OVER-CONFIDENT. (Filter bounds are too tight. Process noise might be too low).")
elif coverage_pct > 98.0:
    print(">> STATUS: UNDER-CONFIDENT. (Filter bounds are too wide. Process noise might be too high).")
else:
    print(">> STATUS: WELL CALIBRATED. (Coverage is close to 95%).")

# ─────────────────────────────────────────────────────────────────────────────
# 2) VISUALIZATION
# ─────────────────────────────────────────────────────────────────────────────
fig = make_subplots(
    rows=2, cols=1,
    row_heights=[0.7, 0.3],
    vertical_spacing=0.1,
    subplot_titles=("RBPF Confidence Intervals vs Measurement", "Residual Histogram")
)

# --- Top Plot: Bands and Violations ---

# 1. Confidence Band (Grey Area)
fig.add_trace(go.Scatter(
    x=time_v, y=y_ub,
    mode='lines', line=dict(width=0),
    showlegend=False, hoverinfo='skip'
), row=1, col=1)

fig.add_trace(go.Scatter(
    x=time_v, y=y_lb,
    mode='lines', line=dict(width=0),
    fill='tonexty', fillcolor='rgba(100, 100, 100, 0.2)',
    name='95% CI Band'
), row=1, col=1)

# 2. Median Estimate
fig.add_trace(go.Scatter(
    x=time_v, y=y_est,
    mode='lines', name='RBPF Median',
    line=dict(color='blue', width=1.5)
), row=1, col=1)

# 3. Measurements (Dots)
fig.add_trace(go.Scatter(
    x=time_v, y=y_true,
    mode='markers', name='Measurement',
    marker=dict(color='black', size=3, opacity=0.5)
), row=1, col=1)

# 4. Highlight Violations (Red X)
# Get indices where coverage failed
violation_idx = np.where(~is_covered)[0]
if len(violation_idx) > 0:
    fig.add_trace(go.Scatter(
        x=time_v.iloc[violation_idx],
        y=y_true[violation_idx],
        mode='markers', name='Outside Bounds',
        marker=dict(color='red', symbol='x', size=6, line=dict(width=1, color='red'))
    ), row=1, col=1)

# --- Bottom Plot: Residual Histogram ---
residuals = y_true - y_est
fig.add_trace(go.Histogram(
    x=residuals,
    nbinsx=50,
    name='Residuals',
    marker_color='blue',
    opacity=0.7
), row=2, col=1)

# Update Layout
fig.update_layout(
    title_text=f"RBPF Calibration Check (Coverage: {coverage_pct:.1f}%)",
    height=800,
    hovermode="x unified",
    showlegend=True
)

fig.update_xaxes(title_text="Time", row=1, col=1)
fig.update_yaxes(title_text="Temperature (°C)", row=1, col=1)
fig.update_xaxes(title_text="Residual Error (°C)", row=2, col=1)
fig.update_yaxes(title_text="Count", row=2, col=1)

fig.show()

import matplotlib.pyplot as plt
import numpy as np

# ─────────────────────────────────────────────────────────────────────────────
# 1) EXTRACT FINAL LEARNED PARAMETERS
# ─────────────────────────────────────────────────────────────────────────────
# We take the median parameters from the very last time step of the RBPF
theta_final = Th_md[-1, :]

print("=== Final Learned Parameters (for Open Loop Check) ===")
param_dict = {}
for i, name in enumerate(theta_names):
    val = theta_final[i]
    param_dict[name] = val
    print(f"  {name:<12} : {val:.4f}")

# ─────────────────────────────────────────────────────────────────────────────
# 2) RUN OPEN-LOOP SIMULATION (Validation - 4 State, Sub-Stepped)
# ─────────────────────────────────────────────────────────────────────────────
# We simulate the 4-state model from t=0 using ONLY these constant parameters.
# NOTE: We MUST use sub-stepping here too, or 15-min Euler will explode.

def simulate_open_loop_final_4state(theta_vec, u, T_out, T_or, y_start, dt_total):
    # Unpack 10 parameters
    # 0:Ca, 1:Cwo, 2:Cwi, 3:Ch, 4:gao, 5:gai, 6:gao_ext, 7:gwo_ext, 8:gwi_oth, 9:gah
    Ca, Cwo, Cwi, Ch, gao, gai, gao_ext, gwo_ext, gwi_oth, gah = theta_vec

    # --- Build Continuous Matrices A (4x4) and B (4x3) ---
    A = np.zeros((4,4))

    # Row 0: Air
    A[0,0] = -(gao + gai + gah + gao_ext) / Ca
    A[0,1] = gao / Ca
    A[0,2] = gai / Ca
    A[0,3] = gah / Ca

    # Row 1: Wall Out
    A[1,0] = gao / Cwo
    A[1,1] = -(gao + gwo_ext) / Cwo

    # Row 2: Wall In
    A[2,0] = gai / Cwi
    A[2,2] = -(gai + gwi_oth) / Cwi

    # Row 3: Heater
    A[3,0] = gah / Ch
    A[3,3] = -gah / Ch

    # Matrix B (Inputs: u, T_out, T_or)
    B = np.zeros((4,3))
    B[0,1] = gao_ext / Ca      # T_out -> Air
    B[1,1] = gwo_ext / Cwo     # T_out -> Wall Out
    B[2,2] = gwi_oth / Cwi     # T_or  -> Wall In
    B[3,0] = 1.0 / Ch          # u     -> Heater Node

    # --- Simulation Loop with Sub-Stepping ---
    N_sim = len(u)
    X_sim = np.zeros((N_sim, 4))

    # --- CORRECTED INITIALIZATION ---
    # We use the first value of the PASSED T_out array
    T_out_start = T_out[0]

    # [T_air, T_wo, T_wi, T_h]
    # T_wo initialized to T_out_start, others to y_start
    x = np.array([y_start, T_out_start, y_start, y_start], dtype=float)

    # Sub-step settings (match RBPF)
    n_subs = 30
    dt_sub = dt_total / n_subs

    for k in range(N_sim):
        X_sim[k] = x

        if k < N_sim - 1:
            # Current inputs
            U_vec = np.array([u[k], T_out[k], T_or[k]])

            # Micro-loop integration
            for _ in range(n_subs):
                dx = A @ x + B @ U_vec
                x += dx * dt_sub

    return X_sim[:, 0], X_sim # Return Air Temp, All States

# Run the simulation
# Use the global dt_seconds (900s)
y_open_loop, X_states_open = simulate_open_loop_final_4state(
    theta_final, u_arr, T_out_arr, T_or_arr, Y_meas[0], dt_seconds
)

# ─────────────────────────────────────────────────────────────────────────────
# 3) PLOT RESULTS (start from k = 1)
# ─────────────────────────────────────────────────────────────────────────────
fig, ax = plt.subplots(3, 1, figsize=(14, 12), sharex=True)

# Time index aligned with RBPF arrays
timestamps = base_df["Timestamp"].iloc[:N]

# We skip k=0 everywhere (Initialization artifact)
ts_plot      = timestamps.iloc[1:]
Y_meas_plot  = Y_meas[1:]
Ti_lo_plot   = Ti_lo[1:]
Ti_md_plot   = Ti_md[1:]
Ti_hi_plot   = Ti_hi[1:]
y_ol_plot    = y_open_loop[1:]
Alpha_md_plot = Alpha_md[1:]
Alpha_lo_plot = Alpha_lo[1:]
Alpha_hi_plot = Alpha_hi[1:]
regime_plot   = regime_flag[1:]

# --- PLOT 1: RBPF Tracking ---
ax[0].plot(ts_plot, Y_meas_plot, 'k-', alpha=0.4, label="Measured Data")
ax[0].plot(ts_plot, Ti_md_plot, 'b-', linewidth=1, label="RBPF Estimate")
ax[0].fill_between(ts_plot, Ti_lo_plot, Ti_hi_plot, color='blue', alpha=0.1, label="95% CI")
ax[0].set_ylabel("Temp [°C]")
ax[0].set_title("1. RBPF Tracking Performance (Online Learning)")
ax[0].legend(loc="upper right")
ax[0].grid(True, alpha=0.3)

# --- PLOT 2: Open-Loop Check ---
ax[1].plot(ts_plot, Y_meas_plot, 'k-', alpha=0.4, label="Measured Data")
ax[1].plot(ts_plot, y_ol_plot, 'r--', linewidth=2, label="Open-Loop Sim (Final Params)")
ax[1].set_ylabel("Temp [°C]")
ax[1].set_title("2. Open-Loop Simulation using Final Learned Parameters")
ax[1].legend(loc="upper right")
ax[1].grid(True, alpha=0.3)

# --- PLOT 3: Stochastic Volatility ---
ax[2].plot(ts_plot, Alpha_md_plot, color='purple', linewidth=1.5)
ax[2].fill_between(ts_plot, Alpha_lo_plot, Alpha_hi_plot, color='purple', alpha=0.2)
ax[2].set_ylabel("Alpha")
ax[2].set_title("3. Stochastic Volatility (Process Noise Scaling)")
ax[2].grid(True, alpha=0.3)

# Highlight Bursts
bursts_rel = np.where(regime_plot == 1)[0]
if len(bursts_rel) > 0:
    ax[2].scatter(ts_plot.iloc[bursts_rel], Alpha_md_plot[bursts_rel],
                  color='red', s=5, label="High Volatility Regime")
    ax[2].legend()

plt.tight_layout()
plt.show()

# --- PLOT 4: Hidden States (Walls + Heater) ---
plt.figure(figsize=(14, 6))

X_ow_plot   = X_states_open[1:, 1]
X_iw_plot   = X_states_open[1:, 2]
X_h_plot    = X_states_open[1:, 3] # Heater Temp
T_out_plot  = T_out_arr[1:]

plt.plot(ts_plot, X_ow_plot, color='orange', label="Outer Wall Core")
plt.plot(ts_plot, X_iw_plot, color='green', label="Inner Wall Core")
plt.plot(ts_plot, X_h_plot, color='red', linestyle='--', label="Heater Core (State 3)")
plt.plot(ts_plot, T_out_plot, color='cyan', alpha=0.3, linestyle=':', label="Outside Air (Ref)")

plt.title("Estimated Internal Temperatures (Open Loop Simulation)")
plt.ylabel("Temp [°C]")
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

import plotly.graph_objects as go
from plotly.subplots import make_subplots
import numpy as np

# ─────────────────────────────────────────────────────────────────────────────
# 1) DATA PREPARATION
# ─────────────────────────────────────────────────────────────────────────────
# Slices (skip k=0)
ts_plot     = base_df["Timestamp"].iloc[1:N]
y_meas_plot = Y_meas[1:]
ti_md_plot  = Ti_md[1:]
ti_hi_plot  = Ti_hi[1:]
ti_lo_plot  = Ti_lo[1:]
u_plot      = u_arr[1:]
alpha_plot  = Alpha_md[1:]

# Identify "Learning Freeze" points (Regime 1)
# These are points where the model detected a 'burst' and clamped parameter adaptation
freeze_indices = np.where(regime_flag[1:] == 1)[0]
ts_freeze      = ts_plot.iloc[freeze_indices]
alpha_freeze   = alpha_plot[freeze_indices]

# ─────────────────────────────────────────────────────────────────────────────
# 2) BUILD PLOTLY FIGURE
# ─────────────────────────────────────────────────────────────────────────────
fig = make_subplots(
    rows=3, cols=1,
    shared_xaxes=False, # Row 3 (Hist) has different X axis
    vertical_spacing=0.08,
    row_heights=[0.5, 0.25, 0.25], # 50% Main, 25% Alpha, 25% Hist
    specs=[[{"secondary_y": True}],  # Row 1: Dual Axis
           [{"secondary_y": False}], # Row 2: Alpha Series
           [{"secondary_y": False}]] # Row 3: Histogram
)

# --- ROW 1: TEMPERATURES & POWER ---

# Confidence Band
fig.add_trace(go.Scatter(
    x=ts_plot, y=ti_hi_plot, mode='lines', line=dict(width=0),
    showlegend=False, hoverinfo='skip'
), row=1, col=1)

fig.add_trace(go.Scatter(
    x=ts_plot, y=ti_lo_plot, mode='lines', line=dict(width=0),
    fill='tonexty', fillcolor='rgba(0, 0, 255, 0.15)',
    name='95% Uncertainty'
), row=1, col=1)

# Estimates & Measure
fig.add_trace(go.Scatter(
    x=ts_plot, y=ti_md_plot, mode='lines', name='Model Estimate',
    line=dict(color='blue', width=2)
), row=1, col=1)

fig.add_trace(go.Scatter(
    x=ts_plot, y=y_meas_plot, mode='lines', name='Measured',
    line=dict(color='black', width=1, dash='dot'), opacity=0.6
), row=1, col=1)

# Heater (Right Axis)
fig.add_trace(go.Scatter(
    x=ts_plot, y=u_plot, mode='lines', name='Heater (W)',
    line=dict(color='red', width=1), fill='tozeroy', opacity=0.2
), row=1, col=1, secondary_y=True)


# --- ROW 2: ALPHA TRAJECTORY + FREEZE MARKERS ---

# Alpha Line
fig.add_trace(go.Scatter(
    x=ts_plot, y=alpha_plot, mode='lines', name='Median Alpha',
    line=dict(color='purple', width=1.5)
), row=2, col=1)

# Freeze Markers
fig.add_trace(go.Scatter(
    x=ts_freeze, y=alpha_freeze,
    mode='markers', name='Learning Freeze',
    marker=dict(color='red', symbol='x', size=8, line=dict(width=1, color='white'))
), row=2, col=1)


# --- ROW 3: HISTOGRAM OF ALPHA MEDIANS ---

fig.add_trace(go.Histogram(
    x=alpha_plot,
    name='Alpha Distribution',
    marker_color='purple',
    opacity=0.7,
    nbinsx=50
), row=3, col=1)

# ─────────────────────────────────────────────────────────────────────────────
# 3) LAYOUT
# ─────────────────────────────────────────────────────────────────────────────
fig.update_layout(
    title_text="RBPF Analysis: Tracking, Volatility, and Regime Distribution",
    height=900,
    hovermode="x unified",
    showlegend=True,
    legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1)
)

# Axis Labels
fig.update_yaxes(title_text="Temp (°C)", row=1, col=1, secondary_y=False)
fig.update_yaxes(title_text="Power (W)", row=1, col=1, secondary_y=True, showgrid=False)
fig.update_yaxes(title_text="Alpha Scale", row=2, col=1)
fig.update_yaxes(title_text="Count", row=3, col=1)
fig.update_xaxes(title_text="Alpha Value", row=3, col=1)

# Align time axes for Row 1 & 2
fig.update_xaxes(matches='x', row=1, col=1)
fig.update_xaxes(matches='x', row=2, col=1)

fig.show()

import numpy as np
import plotly.graph_objects as go

# ─────────────────────────────────────────────────────────────────────────────
# 1) PARAMETERS
# ─────────────────────────────────────────────────────────────────────────────
min_len_hours = 3.0   # minimum length in hours for a "no-freeze" interval

# regime_flag[1:] is aligned with ts_plot, alpha_plot
no_freeze = (regime_flag[1:] != 1)   # True where there is NO freeze
no_freeze_int = no_freeze.astype(int)

# ─────────────────────────────────────────────────────────────────────────────
# 2) FIND CONTIGUOUS RUNS OF NO-FREEZE
# ─────────────────────────────────────────────────────────────────────────────
diff = np.diff(no_freeze_int)

# +1: start of a True-run (False→True)
# -1: end of a True-run (True→False)
run_starts = np.where(diff == 1)[0] + 1
run_ends   = np.where(diff == -1)[0]

# Handle edge cases where run starts at 0 or ends at last index
if no_freeze[0]:
    run_starts = np.r_[0, run_starts]
if no_freeze[-1]:
    run_ends = np.r_[run_ends, len(no_freeze) - 1]

assert len(run_starts) == len(run_ends)

# ─────────────────────────────────────────────────────────────────────────────
# 3) FILTER BY MINIMUM DURATION AND STORE (start_index, end_index)
# ─────────────────────────────────────────────────────────────────────────────
dt_hours = dt_seconds / 3600.0

non_freeze_intervals_idx = []   # (start_index, end_index) in ts_plot / alpha_plot space
non_freeze_intervals_ts  = []   # (start_timestamp, end_timestamp)

for s, e in zip(run_starts, run_ends):
    num_steps = (e - s + 1)
    run_hours = num_steps * dt_hours

    if run_hours >= min_len_hours:
        non_freeze_intervals_idx.append((int(s), int(e)))
        non_freeze_intervals_ts.append((ts_plot.iloc[s], ts_plot.iloc[e]))

print("Non-freeze intervals (indices):", non_freeze_intervals_idx)
print("Non-freeze intervals (timestamps):", non_freeze_intervals_ts)

# ─────────────────────────────────────────────────────────────────────────────
# 4) PLOT: ALPHA WITH SHADED NO-FREEZE INTERVALS
# ─────────────────────────────────────────────────────────────────────────────
fig_intervals = go.Figure()

# Alpha trajectory
fig_intervals.add_trace(go.Scatter(
    x=ts_plot,
    y=alpha_plot,
    mode='lines',
    name='Median Alpha'
))

# Shade each no-freeze interval
for (s, e) in non_freeze_intervals_idx:
    fig_intervals.add_vrect(
        x0=ts_plot.iloc[s],
        x1=ts_plot.iloc[e],
        fillcolor="rgba(0, 200, 0, 0.2)",
        line_width=0,
        layer="below",
        annotation_text="no-freeze",
        annotation_position="top left"
    )

fig_intervals.update_layout(
    title=f"No-freeze intervals (≥ {min_len_hours} h) on Alpha trajectory",
    xaxis_title="Time",
    yaxis_title="Alpha"
)

fig_intervals.show()

import numpy as np
import plotly.graph_objects as go

# ─────────────────────────────────────────────────────────────────────────────
# 1) PREP: ARRAYS ALIGNED WITH ts_plot (we skip k=0 everywhere)
# ─────────────────────────────────────────────────────────────────────────────
Y_meas_plot = Y_meas[1:]          # measured indoor temp
u_plot      = u_arr[1:]           # heater power
T_out_plot  = T_out_arr[1:]       # outside temp
T_or_plot   = T_or_arr[1:]        # other room temp

# Safety checks
assert len(ts_plot) == len(Y_meas_plot) == len(u_plot) == len(T_out_plot) == len(T_or_plot)

# RMSE helper
def rmse(y_true, y_pred):
    y_true = np.asarray(y_true)
    y_pred = np.asarray(y_pred)
    return float(np.sqrt(np.mean((y_true - y_pred) ** 2)))


# ─────────────────────────────────────────────────────────────────────────────
# 2) LOOP OVER NON-FREEZE INTERVALS AND SIMULATE BOTH MODELS
# ─────────────────────────────────────────────────────────────────────────────
interval_results = []   # will hold per-interval metrics

for idx, (s, e) in enumerate(non_freeze_intervals_idx):
    # Slice segment [s, e] (inclusive) in "plot space"
    ts_seg    = ts_plot.iloc[s:e+1]
    y_seg     = Y_meas_plot[s:e+1]
    u_seg     = u_plot[s:e+1]
    T_out_seg = T_out_plot[s:e+1]
    T_or_seg  = T_or_plot[s:e+1]

    # --- LS RC MODEL (discrete 4-node model identified by LS) ---
    # simulate_open_loop_4c(z, u, T_out, T_or, y, dt, return_states=False)
    y_ls_seg, _, _, _ = simulate_open_loop_4c(
        best_z, u_seg, T_out_seg, T_or_seg, y_seg, dt_seconds
    )

    # --- RBPF RC MODEL (continuous 4-node with theta_final) ---
    # simulate_open_loop_final_4state(theta_vec, u, T_out, T_or, y_start, dt_total)
    y_rbpf_seg, _ = simulate_open_loop_final_4state(
        theta_final, u_seg, T_out_seg, T_or_seg, y_seg[0], dt_seconds
    )

    # Ensure same length (defensive)
    min_len = min(len(y_seg), len(y_ls_seg), len(y_rbpf_seg))
    y_seg       = y_seg[:min_len]
    y_ls_seg    = y_ls_seg[:min_len]
    y_rbpf_seg  = y_rbpf_seg[:min_len]
    ts_seg      = ts_seg.iloc[:min_len]

    # --- RMSEs ---
    rmse_ls    = rmse(y_seg, y_ls_seg)
    rmse_rbpf  = rmse(y_seg, y_rbpf_seg)

    interval_results.append({
        "interval_index": idx + 1,
        "start_idx_plot": int(s),
        "end_idx_plot":   int(e),
        "start_ts": ts_seg.iloc[0],
        "end_ts":   ts_seg.iloc[-1],
        "rmse_ls": rmse_ls,
        "rmse_rbpf": rmse_rbpf,
    })

    # ─────────────────────────────────────────────────────────────
    # 3) PLOT: MEASURED VS LS-RC VS RBPF-RC FOR THIS INTERVAL
    # ─────────────────────────────────────────────────────────────
    fig_int = go.Figure()

    fig_int.add_trace(go.Scatter(
        x=ts_seg, y=y_seg,
        mode='lines', name='Measured',
        line=dict(color='black', width=2)
    ))

    fig_int.add_trace(go.Scatter(
        x=ts_seg, y=y_ls_seg,
        mode='lines', name='LS RC',
        line=dict(color='blue', width=2, dash='dash')
    ))

    fig_int.add_trace(go.Scatter(
        x=ts_seg, y=y_rbpf_seg,
        mode='lines', name='RBPF RC',
        line=dict(color='red', width=2, dash='dot')
    ))

    fig_int.update_layout(
        title=(
            f"No-freeze interval {idx+1}: "
            f"{ts_seg.iloc[0]} → {ts_seg.iloc[-1]}<br>"
            f"RMSE LS={rmse_ls:.3f} °C, "
            f"RMSE RBPF={rmse_rbpf:.3f} °C"
        ),
        xaxis_title="Time",
        yaxis_title="Temperature (°C)",
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
        hovermode="x unified",
    )

    fig_int.show()


# ─────────────────────────────────────────────────────────────────────────────
# 4) PRINT SUMMARY TABLE OF RMSE PER INTERVAL
# ─────────────────────────────────────────────────────────────────────────────
print("\n=== RMSE per no-freeze interval ===")
for r in interval_results:
    print(
        f"Interval {r['interval_index']:2d} "
        f"[{r['start_ts']} → {r['end_ts']}]: "
        f"RMSE_LS = {r['rmse_ls']:.3f} °C, "
        f"RMSE_RBPF = {r['rmse_rbpf']:.3f} °C"
    )

# (Optional) overall means
if interval_results:
    mean_ls   = np.mean([r["rmse_ls"] for r in interval_results])
    mean_rbpf = np.mean([r["rmse_rbpf"] for r in interval_results])
    print(f"\nMean RMSE over all intervals: LS = {mean_ls:.3f} °C, RBPF = {mean_rbpf:.3f} °C")

import pandas as pd
import numpy as np
from sklearn.metrics import mean_squared_error
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from datetime import datetime, time

# 1. CONFIGURATION
#    Define the "Night" window (or any systematic interval)
EVAL_START_TIME = "20:00"
EVAL_END_TIME   = "08:00"

print(f"Systematic Evaluation: Simulating independent blocks from {EVAL_START_TIME} to {EVAL_END_TIME}...")

# 2. HELPER: TIME WINDOW MASK
def is_in_window(ts, start_str, end_str):
    t = ts.time()
    s = datetime.strptime(start_str, "%H:%M").time()
    e = datetime.strptime(end_str, "%H:%M").time()
    if s <= e:
        return (t >= s) & (t <= e)
    else: # Crosses midnight
        return (t >= s) | (t <= e)

# 3. DETECT BLOCKS
df_eval = base_df.copy()
df_eval["In_Window"] = df_eval["Timestamp"].apply(lambda x: is_in_window(x, EVAL_START_TIME, EVAL_END_TIME))
# Group consecutive True rows
df_eval["Block_ID"] = (df_eval["In_Window"] != df_eval["In_Window"].shift()).cumsum()
blocks = df_eval[df_eval["In_Window"]].groupby("Block_ID")

# 4. ITERATE, SIMULATE, AND PLOT
results = []
ls_wins = 0
rbpf_wins = 0

print(f"\nProcessing blocks... (Plots will appear below)")

for _, block_data in blocks:
    # Filter out short blocks (< 4 hours)
    if len(block_data) < (4 * 3600 / dt_seconds):
        continue

    # Extract Data
    ts_blk     = block_data["Timestamp"]
    y_meas_blk = block_data["Temp2"].to_numpy(dtype=float)
    u_blk      = block_data["heat_input"].to_numpy(dtype=float)
    t_out_blk  = block_data["Sensor_outside"].to_numpy(dtype=float)
    t_or_blk   = block_data["Other_room_temp"].to_numpy(dtype=float)

    # --- SIMULATE LS (Static) FROM SCRATCH ---
    # It initializes T_walls, T_heater = y_meas_blk[0]
    y_ls_blk, _, _, _ = simulate_open_loop_4c(
        best_z, u_blk, t_out_blk, t_or_blk, y_meas_blk, dt_seconds
    )

    # --- SIMULATE RBPF (Learned) FROM SCRATCH ---
    # It initializes T_walls, T_heater = y_meas_blk[0]
    y_rbpf_blk, _ = simulate_open_loop_final_4state(
        theta_final, u_blk, t_out_blk, t_or_blk, y_meas_blk[0], dt_seconds
    )

    # Metrics
    rmse_ls   = np.sqrt(mean_squared_error(y_meas_blk, y_ls_blk))
    rmse_rbpf = np.sqrt(mean_squared_error(y_meas_blk, y_rbpf_blk))

    if rmse_rbpf < rmse_ls:
        rbpf_wins += 1
        winner = "RBPF"
    else:
        ls_wins += 1
        winner = "LS"

    # Info strings
    start_str = ts_blk.iloc[0].strftime("%Y-%m-%d %H:%M")
    end_str   = ts_blk.iloc[-1].strftime("%H:%M")
    title_str = (f"Night: {start_str} to {end_str} | "
                 f"RMSE: LS={rmse_ls:.3f}, RBPF={rmse_rbpf:.3f} | Winner: {winner}")

    results.append({
        "Label": ts_blk.iloc[0].strftime("%m-%d"),
        "RMSE_LS": rmse_ls,
        "RMSE_RBPF": rmse_rbpf
    })

    # --- PLOTTING THIS BLOCK ---
    fig = make_subplots(specs=[[{"secondary_y": True}]])

    # 1. Measured
    fig.add_trace(go.Scatter(
        x=ts_blk, y=y_meas_blk, name="Measured",
        mode='lines', line=dict(color='black', width=2)
    ), secondary_y=False)

    # 2. LS Static
    fig.add_trace(go.Scatter(
        x=ts_blk, y=y_ls_blk, name=f"LS Static (RMSE={rmse_ls:.2f})",
        mode='lines', line=dict(color='blue', width=2, dash='dash')
    ), secondary_y=False)

    # 3. RBPF Learned
    fig.add_trace(go.Scatter(
        x=ts_blk, y=y_rbpf_blk, name=f"RBPF Learned (RMSE={rmse_rbpf:.2f})",
        mode='lines', line=dict(color='red', width=2, dash='dot')
    ), secondary_y=False)

    # 4. Heater (Secondary Axis) - Helps explain jumps
    fig.add_trace(go.Scatter(
        x=ts_blk, y=u_blk, name="Heater Power",
        mode='lines', line=dict(color='orange', width=1),
        fill='tozeroy', opacity=0.1
    ), secondary_y=True)

    fig.update_layout(
        title=title_str,
        height=400,
        hovermode="x unified",
        margin=dict(l=20, r=20, t=40, b=20),
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1)
    )
    fig.update_yaxes(title_text="Temp (°C)", secondary_y=False)
    fig.update_yaxes(title_text="Power (W)", secondary_y=True, showgrid=False)

    fig.show()

# 5. FINAL SUMMARY PLOT
print("-" * 60)
print(f"SUMMARY: LS Wins: {ls_wins} | RBPF Wins: {rbpf_wins}")
avg_ls = np.mean([r['RMSE_LS'] for r in results])
avg_rbpf = np.mean([r['RMSE_RBPF'] for r in results])
print(f"AVG RMSE: LS={avg_ls:.3f} | RBPF={avg_rbpf:.3f}")

if results:
    labels = [r['Label'] for r in results]
    y_ls   = [r['RMSE_LS'] for r in results]
    y_rbpf = [r['RMSE_RBPF'] for r in results]

    fig_sum = go.Figure()
    fig_sum.add_trace(go.Bar(x=labels, y=y_ls, name='LS Static', marker_color='blue'))
    fig_sum.add_trace(go.Bar(x=labels, y=y_rbpf, name='RBPF Learned', marker_color='red'))
    fig_sum.update_layout(
        title="Overall RMSE Comparison per Night",
        xaxis_title="Date", yaxis_title="RMSE (°C)", barmode='group'
    )
    fig_sum.show()

import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import pandas as pd
import numpy as np
import os

# 1. SETUP & CONFIGURATION
# ---------------------------------------------------------
OUTPUT_DIR = "Paper_Plots"
os.makedirs(OUTPUT_DIR, exist_ok=True)

# Set professional publication style
plt.rcParams.update({
    'font.family': 'sans-serif',
    'font.size': 11,
    'axes.titlesize': 12,
    'axes.labelsize': 11,
    'xtick.labelsize': 10,
    'ytick.labelsize': 10,
    'figure.dpi': 300,
    'savefig.bbox': 'tight'
})

# 2. DATA PREPARATION
# ---------------------------------------------------------
# A. Align Time Series
# Ensure we match the length of the RBPF output (N particles)
N_filter = len(Alpha_md)
ts_plot = base_df["Timestamp"].iloc[:N_filter]

# B. Prepare Diurnal Data (Bottom Plot)
# Create a temporary DataFrame for aggregation
df_vol = pd.DataFrame({
    'Timestamp': ts_plot,
    'Alpha': Alpha_md
})

# Bin into 2-hour intervals (0, 2, 4...)
df_vol['Hour'] = df_vol['Timestamp'].dt.hour
df_vol['Bin_Start'] = (df_vol['Hour'] // 2) * 2

# Calculate Mean and Std Dev for each bin
vol_stats = df_vol.groupby('Bin_Start')['Alpha'].agg(['mean', 'std']).reset_index()
vol_stats['Label'] = vol_stats['Bin_Start'].apply(lambda x: f"{x:02d}-{x+2:02d}")

# 3. PLOTTING
# ---------------------------------------------------------
# Create figure with 2 rows, sharing no axes
fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(12, 10), gridspec_kw={'height_ratios': [2, 1.2]})

# --- SUBPLOT 1: Alpha Evolution (Time Series) ---
# Plot Median
ax1.plot(ts_plot, Alpha_md, color='#333333', linewidth=1.5, label='Median $\\alpha$')

# Plot Confidence Bounds (Shaded Region)
# Note: Using Alpha_lo/hi (2.5%-97.5%) as proxy for uncertainty bounds
ax1.fill_between(ts_plot, Alpha_lo, Alpha_hi, color='purple', alpha=0.2,
                 label='Confidence Interval (Bounds)')

# Formatting Top Plot
ax1.set_ylabel(r"Stochastic Volatility")
ax1.set_title("Evolution of Process Noise Sensitivity over Time", fontweight='bold')
ax1.legend(loc="upper left", frameon=True, fancybox=False, edgecolor='black')
ax1.grid(True, which='major', linestyle=':', alpha=0.6)

# Date Axis Formatting
ax1.xaxis.set_major_formatter(mdates.DateFormatter('%m-%d'))
ax1.xaxis.set_major_locator(mdates.DayLocator(interval=2))
ax1.set_xlim(ts_plot.iloc[0], ts_plot.iloc[-1])

# --- SUBPLOT 2: Diurnal Profile (Bar Chart) ---
x_pos = np.arange(len(vol_stats))

# Bar Chart with Error Bars (Std Dev)
rects = ax2.bar(x_pos, vol_stats['mean'], yerr=vol_stats['std'],
                align='center', alpha=0.75, color='purple', capsize=5,
                edgecolor='black', linewidth=0.7, label=r'Mean $\alpha \pm$ 1 Std')

# Formatting Bottom Plot
ax2.set_xticks(x_pos)
ax2.set_xticklabels(vol_stats['Label'], rotation=0)
ax2.set_xlabel("Time of Day (2-Hour Bins)")
ax2.set_ylabel(r"Mean $\alpha$")
ax2.set_title("Diurnal Volatility Profile (Systematic Patterns)", fontweight='bold')
ax2.grid(axis='y', linestyle=':', alpha=0.6)
ax2.legend(loc='upper right')

# 4. SAVE AND SHOW
# ---------------------------------------------------------
plt.tight_layout()

# Save to PDF
filename = f"{OUTPUT_DIR}/Alpha_Evolution_Diurnal_Composite.pdf"
plt.savefig(filename, format='pdf')
plt.show()

print(f"Composite plot saved to: {filename}")

import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import numpy as np
import pandas as pd
from sklearn.metrics import mean_squared_error
from datetime import datetime
import os

# --- 1. CONFIGURATION ---
EVAL_START_TIME = "20:00"
EVAL_END_TIME   = "08:00"
OUTPUT_DIR      = "Night_Eval_Plots"

# Create output directory
os.makedirs(OUTPUT_DIR, exist_ok=True)

# Set professional style parameters
plt.rcParams.update({
    'font.family': 'sans-serif',
    'font.size': 10,
    'axes.titlesize': 12,
    'axes.labelsize': 11,
    'legend.fontsize': 9,
    'xtick.labelsize': 9,
    'ytick.labelsize': 9,
    'figure.dpi': 300, # High resolution
    'savefig.bbox': 'tight'
})

# --- 2. DATA PREPARATION (Block Detection) ---
def is_in_window(ts, start_str, end_str):
    t = ts.time()
    s = datetime.strptime(start_str, "%H:%M").time()
    e = datetime.strptime(end_str, "%H:%M").time()
    if s <= e:
        return (t >= s) & (t <= e)
    else: # Crosses midnight
        return (t >= s) | (t <= e)

df_eval = base_df.copy()
df_eval["In_Window"] = df_eval["Timestamp"].apply(lambda x: is_in_window(x, EVAL_START_TIME, EVAL_END_TIME))
df_eval["Block_ID"] = (df_eval["In_Window"] != df_eval["In_Window"].shift()).cumsum()
blocks = df_eval[df_eval["In_Window"]].groupby("Block_ID")

results = []
ls_wins = 0
rbpf_wins = 0

print(f"Generating plots in '{OUTPUT_DIR}'...")

# --- 3. MAIN LOOP ---
for i, (_, block_data) in enumerate(blocks):
    # Filter short blocks
    if len(block_data) < (4 * 3600 / dt_seconds):
        continue

    # Extract Data
    ts_blk      = block_data["Timestamp"]
    y_meas_blk  = block_data["Temp2"].to_numpy(dtype=float)
    u_blk       = block_data["heat_input"].to_numpy(dtype=float)
    t_out_blk   = block_data["Sensor_outside"].to_numpy(dtype=float)
    t_or_blk    = block_data["Other_room_temp"].to_numpy(dtype=float)

    # --- SIMULATIONS ---
    # 1. LS Static (Open Loop)
    y_ls_blk, _, _, _ = simulate_open_loop_4c(
        best_z, u_blk, t_out_blk, t_or_blk, y_meas_blk, dt_seconds
    )

    # 2. RBPF Learned (Open Loop using final params)
    y_rbpf_blk, _ = simulate_open_loop_final_4state(
        theta_final, u_blk, t_out_blk, t_or_blk, y_meas_blk[0], dt_seconds
    )

    # Metrics
    rmse_ls   = np.sqrt(mean_squared_error(y_meas_blk, y_ls_blk))
    rmse_rbpf = np.sqrt(mean_squared_error(y_meas_blk, y_rbpf_blk))

    # Winner logic
    if rmse_rbpf < rmse_ls:
        rbpf_wins += 1
        winner_color = 'red' # RBPF color
    else:
        ls_wins += 1
        winner_color = 'blue' # LS color

    # Store results
    date_label = ts_blk.iloc[0].strftime("%Y-%m-%d")
    results.append({
        "Label": ts_blk.iloc[0].strftime("%m-%d"),
        "RMSE_LS": rmse_ls,
        "RMSE_RBPF": rmse_rbpf
    })

    # --- PLOTTING (Matplotlib) ---
    fig, ax1 = plt.subplots(figsize=(10, 5))

    # Title
    start_str = ts_blk.iloc[0].strftime("%H:%M")
    end_str   = ts_blk.iloc[-1].strftime("%H:%M")
    ax1.set_title(f"Evaluation: {date_label} ({start_str}-{end_str})\n"
                  f"LS RMSE: {rmse_ls:.3f} | RBPF RMSE: {rmse_rbpf:.3f}", fontweight='bold')

    # Primary Axis (Temperature)
    ax1.set_xlabel("Time (HH:MM)")
    ax1.set_ylabel("Temperature ($^{\circ}$C)", color='black')

    # Plots
    l1, = ax1.plot(ts_blk, y_meas_blk, 'k-', lw=1.5, alpha=0.8, label='Measured')
    l2, = ax1.plot(ts_blk, y_ls_blk, color='blue', linestyle='--', lw=1.5, label=f'LS Static')
    l3, = ax1.plot(ts_blk, y_rbpf_blk, color='red', linestyle='-.', lw=1.5, label=f'RBPF Learned')

    # Secondary Axis (Heater Power)
    ax2 = ax1.twinx()
    ax2.set_ylabel("Heater Power (W)", color='orange')
    l4 = ax2.fill_between(ts_blk, u_blk, color='orange', alpha=0.2, label='Heater Power')
    ax2.tick_params(axis='y', labelcolor='orange')

    # Formatting Time Axis
    ax1.xaxis.set_major_formatter(mdates.DateFormatter('%H:%M'))
    plt.setp(ax1.get_xticklabels(), rotation=0, ha='center')

    # Grid
    ax1.grid(True, which='major', linestyle=':', alpha=0.6)

    # Legend (Combine both axes)
    lines = [l1, l2, l3, l4]
    labels = [l.get_label() for l in lines]
    ax1.legend(lines, labels, loc='upper center', bbox_to_anchor=(0.5, -0.15),
               ncol=4, frameon=False)

    # Save PDF
    filename = f"{OUTPUT_DIR}/Eval_{date_label}_LSvsRBPF.pdf"
    plt.savefig(filename, format='pdf', bbox_inches='tight')
    plt.close(fig) # Close to free memory

# --- 4. SUMMARY PLOT ---
if results:
    labels = [r['Label'] for r in results]
    y_ls   = [r['RMSE_LS'] for r in results]
    y_rbpf = [r['RMSE_RBPF'] for r in results]

    x = np.arange(len(labels))
    width = 0.35

    fig, ax = plt.subplots(figsize=(12, 6))
    rects1 = ax.bar(x - width/2, y_ls, width, label='LS Static', color='blue', alpha=0.7)
    rects2 = ax.bar(x + width/2, y_rbpf, width, label='RBPF Learned', color='red', alpha=0.7)

    ax.set_ylabel('RMSE ($^{\circ}$C)')
    ax.set_title('Model Performance Comparison per Night')
    ax.set_xticks(x)
    ax.set_xticklabels(labels, rotation=45)
    ax.legend()
    ax.grid(axis='y', linestyle=':', alpha=0.5)

    # Add text for overall stats
    stats_text = (f"Total Nights: {len(results)}\n"
                  f"Avg RMSE (LS): {np.mean(y_ls):.3f}\n"
                  f"Avg RMSE (RBPF): {np.mean(y_rbpf):.3f}")

    props = dict(boxstyle='round', facecolor='white', alpha=0.8)
    ax.text(0.02, 0.95, stats_text, transform=ax.transAxes, fontsize=10,
            verticalalignment='top', bbox=props)

    plt.savefig(f"{OUTPUT_DIR}/Eval_Summary_RMSE.pdf", format='pdf', bbox_inches='tight')
    plt.show() # Show summary inline
    print(f"\nProcessing Complete. {len(results)} plot files saved to folder '{OUTPUT_DIR}'.")