# -*- coding: utf-8 -*-
"""RBPF_Synthdata.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hgUAN2Ja54Greb4D1amip0FBrq9vUPaW
"""

!pip install filterpy

!pip install control

import os, platform, time, re
import numpy as np
import pandas as pd
from pathlib import Path
from scipy.linalg import expm
import plotly.graph_objects as go
from scipy.optimize import minimize
import control
from scipy.signal import cont2discrete
import math
import os
from datetime import datetime
from google.colab import drive
from scipy.signal import cont2discrete
from scipy.optimize import minimize
from scipy.optimize._numdiff import approx_derivative  # SciPy numerical Jacobian
from filterpy.kalman import ExtendedKalmanFilter
def cpu_model_name():

def cpu_model_name():
    # Works on Colab/Linux
  try:
      with open("/proc/cpuinfo", "r") as f:
          txt = f.read()
      m = re.search(r"model name\s*:\s*(.+)", txt)
      return m.group(1).strip() if m else "Unknown CPU"
  except Exception:
      return "Unknown CPU"

def system_ram_gb():
    try:
        with open("/proc/meminfo", "r") as f:
            meminfo = f.read()
        m = re.search(r"MemTotal:\s+(\d+)\s+kB", meminfo)
        if not m:
            return None
        return int(m.group(1)) / (1024**2)  # kB -> GB
    except Exception:
        return None

# Process memory (RSS)
try:
    import psutil
    _proc = psutil.Process(os.getpid())
    def process_rss_mb():
        return _proc.memory_info().rss / (1024**2)
except Exception:
    # Fallback if psutil is unavailable
    def process_rss_mb():
        try:
            with open("/proc/self/status", "r") as f:
                txt = f.read()
            m = re.search(r"VmRSS:\s+(\d+)\s+kB", txt)
            return (int(m.group(1)) / 1024.0) if m else float("nan")
        except Exception:
            return float("nan")

print("=== Runtime environment ===")
print("Platform:", platform.platform())
print("Python:", platform.python_version())
print("CPU:", cpu_model_name())
ram_gb = system_ram_gb()
if ram_gb is not None:
    print(f"System RAM: {ram_gb:.2f} GB")
print(f"Initial process RSS: {process_rss_mb():.1f} MB")
print("===========================")

def arrays_size_mb(arr_list, dedupe_by_data_ptr=True):
    """
    Sum payload sizes (nbytes) of NumPy arrays in arr_list.
    Returns total size in MB.
    """
    total = 0
    seen = set()

    for a in arr_list:
        if a is None:
            continue
        if not isinstance(a, np.ndarray):
            continue

        if dedupe_by_data_ptr:
            # pointer to underlying data buffer
            ptr = int(a.__array_interface__["data"][0])
            if ptr in seen:
                continue
            seen.add(ptr)

        total += a.nbytes

    return total / (1024**2)

def generate_square_heating(N,
                            dt_seconds,
                            power=6000.0,
                            p_start=0.002,                # per-STEP start prob when OFF
                            min_duration_s=30*60,         # 30 minutes
                            max_duration_s=4*60*60,       # 4 hours
                            seed=None):
    """
    Generate a square heating signal with random ON episodes.
    - When OFF, each step has probability p_start to begin an ON episode.
    - Each ON episode has a constant 'power' and a duration uniform in [min_duration_s, max_duration_s].
    - Episodes do not overlap; new ones can start only when the previous one ends.

    Returns
    -------
    F_true : (N,) float array
        Heating power in Watts at each step.
    event_log : list of dict
        Each dict has: {'start_idx', 'end_idx', 'duration_s'} (end_idx inclusive).
    """
    rng = np.random.default_rng(seed)

    # durations in steps
    min_steps = int(np.ceil(min_duration_s / dt_seconds))
    max_steps = int(np.ceil(max_duration_s / dt_seconds))
    print("MAX steps",max_steps)
    print("MIN steps",min_steps)
    if min_steps < 1:
      min_steps = 1
    if max_steps < min_steps:
      max_steps = min_steps

    F_true = np.zeros(N, dtype=float)
    event_log = []

    on_remaining = 0
    start_idx = None

    for k in range(N):
        if on_remaining > 0:
            F_true[k] = power
            on_remaining -= 1
            if on_remaining == 0:
                # episode ends at k
                event_log.append({
                    "start_idx": start_idx,
                    "end_idx": k,
                    "duration_s": (k - start_idx + 1) * dt_seconds
                })
                start_idx = None
        else:
            # currently OFF; possibly start a new episode
            if rng.random() < p_start:
                dur_steps = rng.integers(min_steps, max_steps + 1)
                on_remaining = dur_steps
                start_idx = k
                F_true[k] = power
                on_remaining -= 1  # consumed this step
            # else remains 0 (OFF)
    # If an ON episode runs past the last index, we close it at N-1
    if start_idx is not None and (len(event_log) == 0 or event_log[-1]["end_idx"] != N-1):
        event_log.append({
            "start_idx": start_idx,
            "end_idx": N-1,
            "duration_s": (N - start_idx) * dt_seconds
        })

    return F_true, event_log

def generate_pulse_heating(N,
                           dt_seconds,
                           mode="alpha",                  # "alpha" (rise/decay) or "gauss"
                           p_start=0.0015,                # per-step birth probability
                           amp_range=(1500.0, 8000.0),    # Watts (uniform)
                           tau_r_range_s=(5*60, 40*60),   # alpha: rise time (seconds)
                           tau_d_range_s=(45*60, 4*60*60),# alpha: decay time (seconds)
                           sigma_range_s=(15*60, 90*60),  # gauss: std (seconds)
                           kill_rel=1e-3,                 # drop pulse when value < kill_rel * A
                           max_active=6,                  # cap concurrent pulses
                           seed=None):
    """
    Generate a bursty positive latent heat signal as a sum of smooth pulses.

    Pulses arrive via a Bernoulli hazard p_start per step. Each new pulse samples its
    parameters from simple ranges, remains active, and contributes a smooth, positive shape:

      - mode="alpha":  f(t) = A * max( exp(-age/tau_d) - exp(-age/tau_r), 0.0 )
      - mode="gauss":  f(t) = A * exp( -0.5 * (age/sigma)**2 )

    A pulse is dropped when f(t) < kill_rel * A.

    Returns
    -------
    F_true : (N,) float
        Total latent heat per step (W).
    event_log : list of dict
        For each pulse:
          {
            'mode', 'start_idx', 'end_idx',
            'A', 'tau_r_s', 'tau_d_s', 'sigma_s',
            'peak_W', 'peak_idx'
          }
        Unused keys are None for the chosen mode.
    """
    import numpy as np

    rng = np.random.default_rng(seed)
    F_true = np.zeros(N, dtype=float)
    event_log = []

    active = []  # list of dicts; each has fixed params and evolving 'age_s'

    def _sample_time_s(lo, hi):
        # sample in log-space for robustness if ranges are wide
        lo = max(lo, 1.0)
        hi = max(hi, lo + 1.0)
        return float(10 ** rng.uniform(np.log10(lo), np.log10(hi)))

    for k in range(N):
        # births
        if len(active) < max_active and rng.random() < p_start:
            A = rng.uniform(*amp_range)
            if mode == "alpha":
                tau_r_s = _sample_time_s(*tau_r_range_s)
                tau_d_s = _sample_time_s(*tau_d_range_s)
                if tau_d_s <= tau_r_s:
                    tau_d_s = tau_r_s * rng.uniform(1.5, 3.0)  # enforce decay > rise
                pulse = {
                    "mode": "alpha",
                    "A": A,
                    "tau_r_s": tau_r_s,
                    "tau_d_s": tau_d_s,
                    "sigma_s": None,
                    "age_s": 0.0,
                    "start_idx": k,
                    "peak_W": 0.0,
                    "peak_idx": k
                }
            elif mode == "gauss":
                sigma_s = _sample_time_s(*sigma_range_s)
                pulse = {
                    "mode": "gauss",
                    "A": A,
                    "tau_r_s": None,
                    "tau_d_s": None,
                    "sigma_s": sigma_s,
                    "age_s": 0.0,
                    "start_idx": k,
                    "peak_W": 0.0,
                    "peak_idx": k
                }
            else:
                raise ValueError("mode must be 'alpha' or 'gauss'")
            active.append(pulse)

        # accumulate contributions from active pulses at time k
        val_k = 0.0
        keep = []
        for p in active:
            age = p["age_s"]
            A = p["A"]
            if p["mode"] == "alpha":
                tr = p["tau_r_s"]
                td = p["tau_d_s"]
                f = A * max(np.exp(-age/td) - np.exp(-age/tr), 0.0)
            else:  # "gauss"
                sg = p["sigma_s"]
                f = A * np.exp(-0.5 * (age/sg)**2)

            val_k += f

            # track peak and decide if to keep
            if f > p["peak_W"]:
                p["peak_W"] = f
                p["peak_idx"] = k

            if (age == 0.0) or (f >= kill_rel * A):
                p["age_s"] = age + dt_seconds
                keep.append(p)
            else:
                p["end_idx"] = k
                event_log.append(p)
        active = keep
        F_true[k] = val_k

    # close any remaining pulses at the end
    for p in active:
        p["end_idx"] = N - 1
        event_log.append(p)

    # normalize event_log fields
    for p in event_log:
        p.setdefault("end_idx", N - 1)
        p.setdefault("peak_W", 0.0)
        p.setdefault("peak_idx", p["start_idx"])

    return F_true, event_log

# --------------------------- USER INPUTS ----------------------------
TEMP_FILE  = Path("dwd_20242025.txt")
SOLAR_FILE = Path("radiation_20242025.txt")

START = "2024-04-10 00:00"   # inclusive
END   = "2024-05-10 00:00"   # exclusive
dt_seconds = 600             # 10 min window (changed from 120)

# ------------------- LOADERS (robust to DWD format) ----------------
# ------------------- LOADERS (robust to DWD format) ----------------
def load_dwd_temperature(path: Path) -> pd.DataFrame:
    # Added on_bad_lines='skip' to handle malformed rows/footers
    df = pd.read_csv(path, sep=";", decimal=",", dtype=str,
                     na_values=["-999", "-9999", "-999.0", "", "NA", "NaN"],
                     on_bad_lines='skip')

    if "MESS_DATUM" not in df.columns:
        # Sometimes DWD files have leading spaces in headers; strip them just in case
        df.columns = df.columns.str.strip()

    if "MESS_DATUM" not in df.columns:
        raise ValueError(f"Temperature file missing 'MESS_DATUM'. Found: {df.columns}")

    cand = [c for c in df.columns if c.upper().startswith("TT")]
    if not cand:
        raise ValueError("Temperature file missing 'TT_10' (°C).")
    df = df.rename(columns={cand[0]: "TT_10"})

    df["Timestamp"] = pd.to_datetime(df["MESS_DATUM"], format="%Y%m%d%H%M", errors="coerce")
    df["TT_10"] = pd.to_numeric(df["TT_10"], errors="coerce")
    df = df.dropna(subset=["Timestamp", "TT_10"]).reset_index(drop=True)
    return df[["Timestamp", "TT_10"]].sort_values("Timestamp")

def load_dwd_radiation(path: Path) -> pd.DataFrame:
    # Added on_bad_lines='skip' to handle malformed rows/footers
    df = pd.read_csv(path, sep=";", decimal=",", dtype=str,
                     na_values=["-999", "-9999", "-999.0", "", "NA", "NaN"],
                     on_bad_lines='skip')

    if "MESS_DATUM" not in df.columns:
        df.columns = df.columns.str.strip()

    if "MESS_DATUM" not in df.columns:
        raise ValueError(f"Solar file missing 'MESS_DATUM'. Found: {df.columns}")

    cand = [c for c in df.columns if c.upper().startswith("GS")]
    if not cand:
        raise ValueError("Solar file missing 'GS_10'.")
    df = df.rename(columns={cand[0]: "GS_10"})

    df["Timestamp"] = pd.to_datetime(df["MESS_DATUM"], format="%Y%m%d%H%M", errors="coerce")
    df["GS_10"] = pd.to_numeric(df["GS_10"], errors="coerce")
    df = df.dropna(subset=["Timestamp", "GS_10"]).reset_index(drop=True)

    # J/cm² over 10 min -> W/m² average over the interval
    df["U_s"] = df["GS_10"] * 10000.0 / 600.0
    return df[["Timestamp", "U_s"]].sort_values("Timestamp")

# Load Data
t_df = load_dwd_temperature(TEMP_FILE)
s_df = load_dwd_radiation(SOLAR_FILE)

# ----------------------- TIME FILTER & ALIGN -----------------------
# Create the target 10-minute grid
ts_grid_pd = pd.date_range(start=START, end=END, freq=f'{dt_seconds}s', inclusive='left')

# Reindex both dataframes to this grid using 'nearest' (no interpolation)
def align_to_grid(df, grid, col_name):
    # Ensure sorted unique index
    df = df.sort_values("Timestamp").drop_duplicates(subset=["Timestamp"])
    df = df.set_index("Timestamp")

    # Reindex with nearest tolerance.
    # We allow a tolerance of dt/2 so we don't grab data too far away.
    tol = pd.Timedelta(seconds=dt_seconds/2)
    aligned = df.reindex(grid, method='nearest', tolerance=tol)

    # Fill remaining NaNs (gaps > tolerance) with ffill/bfill or 0
    # Here we forward fill to keep causal structure, then backfill start
    aligned[col_name] = aligned[col_name].ffill().bfill()
    return aligned[col_name].values

T_out_C = align_to_grid(t_df, ts_grid_pd, "TT_10")
U_s     = align_to_grid(s_df, ts_grid_pd, "U_s")

# Convert to Numpy/Model Units
ts = ts_grid_pd.to_pydatetime()
ts_grid = ts_grid_pd.values.astype('datetime64[s]')
t_grid_s = ts_grid.astype('int64')
N = len(ts_grid)

T_out_K = T_out_C + 273.15

# ------------------- HARD-CODED RC PARAMETERS identification number 67 ---------------------
Ci_kWhK = 2.745148488
Cm_kWhK = 19.76698557
Ce_kWhK = 2.412573281
Ch_kWhK = 0.101200218
Cs_kWhK = 0.106406602
Ci = Ci_kWhK * 3_600_000.0
Cm = Cm_kWhK * 3_600_000.0
Ce = Ce_kWhK * 3_600_000.0
Ch = Ch_kWhK * 3_600_000.0
Cs = Cs_kWhK * 3_600_000.0

def to_G(R):
    return 0.0 if not np.isfinite(R) else 1000.0 / R

Rie_K_per_kW = 0.532152894
Rea_K_per_kW = 7.115085934
Ria_K_per_kW = np.inf
Rim_K_per_kW = 0.552472387
Rih_K_per_kW = 0.269801371
Ris_K_per_kW = 2.349904019

g_ie = to_G(Rie_K_per_kW)
g_ea = to_G(Rea_K_per_kW)
g_ia = to_G(Ria_K_per_kW)
g_im = to_G(Rim_K_per_kW)
g_ih = to_G(Rih_K_per_kW)
g_is = to_G(Ris_K_per_kW)

Aw_m2 = 4.542558125
Ae_m2 = 0.0
Aw = float(Aw_m2)
Ae = float(Ae_m2)

eta_h = 1.0

# ----------------- CONTINUOUS-TIME MATRICES ---------------------
Cdiag = np.array([Ci, Cm, Ce, Ch, Cs], float)
Cinvt = np.diag(1.0 / Cdiag)

G = np.zeros((5,5), float)
G[0,1] = G[1,0] = g_im
G[0,2] = G[2,0] = g_ie
G[0,3] = G[3,0] = g_ih
G[0,4] = G[4,0] = g_is
G[0,0] = -(g_im + g_ie + g_ih + g_is + g_ia)
G[1,1] = -(g_im)
G[2,2] = -(g_ie + g_ea)
G[3,3] = -(g_ih)
G[4,4] = -(g_is)

A_c = Cinvt @ G

# Input matrices (Columns: [u, T_out, U_s, F])
# Note: ZOH usually treats inputs as constant over the step.
# We will combine B matrices for the ZOH calculation.
# x_dot = A_c*x + B_total * u_total
# u_total = [u, T_out, U_s, F]^T

B_total = np.zeros((5, 4))
B_total[3, 0] = eta_h / Ch             # u -> Th
B_total[0, 1] = g_ia / Ci              # T_out -> Ti (0 here)
B_total[2, 1] = g_ea / Ce              # T_out -> Te
B_total[0, 2] = Aw / Ci                # U_s -> Ti
B_total[2, 2] = Ae / Ce                # U_s -> Te
B_total[0, 3] = 1.0 / Ci               # F -> Ti

# Measurement Matrix (Cy)
C_y = np.array([[1, 0, 0, 0, 0]], float)

# Direct feedthrough (Dy) – all zeros for this model
D_y = np.zeros((1, 4))

# ----------------------- INPUTS: LATENT & HEATER -------------------
# (Assuming generate_square_heating functions are available from previous context)
F_true, F_events = generate_square_heating(
    N=N, dt_seconds=dt_seconds,
    power=7000.0,
    p_start=0.0055,
    min_duration_s=20*60,
    max_duration_s=8*60*60,
    seed=321
)

u, u_events = generate_square_heating(
    N=N, dt_seconds=dt_seconds,
    power=800.0,
    p_start=0.02,
    min_duration_s=20*60,
    max_duration_s=1*60*60,
    seed=321
)

print(f"Latent F: mean={F_true.mean():.1f} W, max={F_true.max():.0f} W")
print(f"Heater u: mean={u.mean():.1f} W, max={u.max():.0f} W")

# ---------------------------- SIMULATE (ZOH) ---------------------
# Use scipy.signal.cont2discrete for exact ZOH discretization
system_ct = (A_c, B_total, C_y, D_y)
Ad, Bd, Cd, Dd, dt_out = cont2discrete(system_ct, dt_seconds, method="zoh")

# Extract Discrete System
Phi = Ad                    # State transition
Gam = Bd                    # Input influence

Ti0 = T_out_K[0]
x = np.array([Ti0, Ti0, Ti0, Ti0, Ti0], float)
X = np.zeros((N,5), float)
X[0] = x

q_std = np.array([0.03, 0.03, 0.03, 0.03, 0.03])
rng = np.random.default_rng(123)

print("Starting ZOH Simulation (scipy.signal.cont2discrete)...")
for k in range(N-1):
    # Input vector at step k (constant over interval)
    u_vec = np.array([
        u[k],       # Heater
        T_out_K[k], # Outdoor Temp
        U_s[k],     # Solar
        F_true[k]   # Latent
    ])

    # Exact ZOH update: x[k+1] = Phi*x[k] + Gamma*u[k]
    x = Phi @ x + Gam @ u_vec

    # Add Process Noise
    x = x + rng.normal(0.0, q_std)

    X[k+1] = x

Y_Ti = (C_y @ X.T).ravel()  # Ti [K]

# ---------------------------- PLOTS -------------------------------
# 1) Weather, heater, and latent heat
fig1 = go.Figure()
fig1.add_trace(go.Scatter(x=ts, y=T_out_C, name="Outside T [°C]", mode="lines"))
fig1.add_trace(go.Scatter(x=ts, y=U_s,     name="Solar U_s [W/m²]", mode="lines", yaxis="y2", opacity=0.5))
fig1.add_trace(go.Scatter(x=ts, y=F_true,  name="Latent F [W]",    mode="lines", yaxis="y3", opacity=0.6))
fig1.add_trace(go.Scatter(x=ts, y=u,       name="Heater u [W]",    mode="lines", yaxis="y4", opacity=0.7))
fig1.update_layout(
    title="Inputs: Outside Temp, Solar, Latent Heat (Ti), and Heater (Th) [10min ZOH]",
    xaxis=dict(title="Time", type="date", rangeslider=dict(visible=True)),
    yaxis=dict(title="°C"),
    yaxis2=dict(title="W/m²", overlaying="y", side="right", showgrid=False),
    yaxis3=dict(title="W (Latent F)", overlaying="y", side="right", anchor="free", position=0.98, showgrid=False),
    yaxis4=dict(title="W (Heater u)", overlaying="y", side="right", anchor="free", position=0.92, showgrid=False),
    template="plotly_white",
    legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="left", x=0)
)
fig1.show()

# 2) State trajectories (°C)
Ti_C = X[:,0] - 273.15
Tm_C = X[:,1] - 273.15
Te_C = X[:,2] - 273.15
Th_C = X[:,3] - 273.15
Ts_C = X[:,4] - 273.15

fig2 = go.Figure()
fig2.add_trace(go.Scatter(x=ts, y=Ti_C, name="Ti", mode="lines"))
fig2.add_trace(go.Scatter(x=ts, y=Tm_C, name="Tm", mode="lines"))
fig2.add_trace(go.Scatter(x=ts, y=Te_C, name="Te", mode="lines"))
fig2.add_trace(go.Scatter(x=ts, y=Th_C, name="Th", mode="lines"))
fig2.add_trace(go.Scatter(x=ts, y=Ts_C, name="Ts", mode="lines"))
fig2.update_layout(
    title="5-State RC Simulation (ZOH Generation)",
    xaxis=dict(title="Time", type="date", rangeslider=dict(visible=True)),
    yaxis=dict(title="Temperature [°C]"),
    template="plotly_white",
    legend=dict(orientation="h", yanchor="bottom", y=1.02, x=0)
)
fig2.show()

# 3) Measured Ti (noisy) vs true Ti
sigma_y = 0.15
Y_meas = Y_Ti + rng.normal(0.0, sigma_y, size=N)
fig3 = go.Figure()
fig3.add_trace(go.Scatter(x=ts, y=Ti_C,          name="True Ti [°C]", mode="lines"))
fig3.add_trace(go.Scatter(x=ts, y=Y_meas-273.15, name="Measured Ti [°C]", mode="lines", opacity=0.6))
fig3.update_layout(
    title="Indoor Air Temperature (True vs Measured)",
    xaxis=dict(title="Time", type="date", rangeslider=dict(visible=True)),
    yaxis=dict(title="°C"),
    template="plotly_white",
    legend=dict(orientation="h", y=1.02, x=0)
)
fig3.show()

# ------------------------ QUICK SANITY PRINTS ---------------------
print(f"N = {N}, dt = {dt_seconds}s, grid duration = {N*dt_seconds/3600:.1f} h")

# ------------------------------------------------------------------
# Helper: Exact ZOH Discretization from Theta (Single Step)
# ------------------------------------------------------------------
def discrete_from_theta_single(theta_full):
    Ci, Cm, Ce, Ch, Cs = (
        theta_full[0],
        theta_full[1],
        theta_full[2],
        theta_full[3],
        theta_full[4],
    )
    g_im, g_ie, g_ih, g_is, g_ea = (
        theta_full[5],
        theta_full[6],
        theta_full[7],
        theta_full[8],
        theta_full[9],
    )
    g_ia = 0.0

    invC = np.array([1.0 / Ci, 1.0 / Cm, 1.0 / Ce, 1.0 / Ch, 1.0 / Cs])

    # --- 1. Construct Continuous Dynamics Matrix A_c ---
    # Rows are scaled by 1/C after conductance assembly
    d0 = -(g_im + g_ie + g_ih + g_is + g_ia)
    d1 = -g_im
    d2 = -(g_ie + g_ea)
    d3 = -g_ih
    d4 = -g_is

    A_c = np.zeros((5, 5))
    A_c[0, :] = [d0, g_im, g_ie, g_ih, g_is]
    A_c[1, :] = [g_im, d1, 0, 0, 0]
    A_c[2, :] = [g_ie, 0, d2, 0, 0]
    A_c[3, :] = [g_ih, 0, 0, d3, 0]
    A_c[4, :] = [g_is, 0, 0, 0, d4]

    # Apply 1/C scaling to rows
    A_c = (A_c.T * invC).T

    # --- 2. Construct Continuous Input Matrix B_c ---
    # Columns correspond to: [u (heater), T_out, U_s (solar)]
    B_c = np.zeros((5, 3))

    # u -> Th
    B_c[3, 0] = eta_h * invC[3]

    # T_out -> Ti (g_ia=0 usually) and Te (g_ea)
    B_c[0, 1] = g_ia * invC[0]
    B_c[2, 1] = g_ea * invC[2]

    # U_s -> Ti (Aw) and Te (Ae)
    B_c[0, 2] = Aw * invC[0]
    B_c[2, 2] = Ae * invC[2]

    # --- 3. ZOH Discretization via scipy.signal.cont2discrete ---
    # Use a dummy output so we can call cont2discrete with method='zoh'
    C_dummy = np.zeros((1, 5))
    D_dummy = np.zeros((1, 3))

    A_d, B_d, _, _, _ = cont2discrete(
        (A_c, B_c, C_dummy, D_dummy),
        dt_seconds,
        method="zoh"
    )

    # A_d: 5x5, B_d: 5x3
    return A_d, B_d

# Measurement matrix: Ti only
C_meas = np.array([[1, 0, 0, 0, 0]], float)

# Fixed parameters setup
theta_fixed_cap = np.array([Ci, Cm, Ce, Ch, Cs], float)
g_is_fixed = float(g_is)

# ------------------------------------------------------------------
# Helper: build full θ from the 4 free conductances
# ------------------------------------------------------------------
def theta_from_g4(g4):
    g4 = np.maximum(np.asarray(g4, float), 1e-6)
    g_im_hat, g_ie_hat, g_ih_hat, g_ea_hat = g4
    return np.array(
        [
            Ci,
            Cm,
            Ce,
            Ch,
            Cs,
            g_im_hat,
            g_ie_hat,
            g_ih_hat,
            g_is_fixed,  # <-- fixed
            g_ea_hat,
        ],
        float,
    )

# ------------------------------------------------------------------
# Deterministic state-space simulation (Output Error method)
# ------------------------------------------------------------------
def simulate_y(theta_full, x0=None):
    """
    Deterministic simulation of the model output y over the whole horizon using ZOH.
    """
    A_d, B_d = discrete_from_theta_single(theta_full)

    # Split B_d into individual input influence vectors
    B_u  = B_d[:, 0]  # heater input
    B_To = B_d[:, 1]  # outdoor temperature
    B_Us = B_d[:, 2]  # solar

    # Initial state guess: set all nodes to first measured T_in
    if x0 is None:
        x = np.array([Y_meas[0]] * 5, float)
    else:
        x = np.array(x0, float)

    y_hat = np.empty_like(Y_meas, dtype=float)
    y_hat[0] = (C_meas @ x).item()

    # Simulation Loop
    for k in range(1, len(Y_meas)):
        uk  = u[k - 1]
        Tok = T_out_K[k - 1]
        Usk = U_s[k - 1]

        # Discrete ZOH update
        x = A_d @ x + uk * B_u + Tok * B_To + Usk * B_Us

        # Output
        y_hat[k] = (C_meas @ x).item()

    return y_hat

# ------------------------------------------------------------------
# Objective Function: Sum of Squared Errors
# ------------------------------------------------------------------
def sse_g4(g4):
    theta_full = theta_from_g4(g4)
    y_hat = simulate_y(theta_full)
    err = Y_meas - y_hat
    return float(np.sum(err**2))

# ------------------------------------------------------------------
# Optimization: 4 vars = g_im, g_ie, g_ih, g_ea (g_is fixed)
# ------------------------------------------------------------------
print("Starting Least Squares Optimization (ZOH)...")

g0_4 = np.array([g_im, g_ie, g_ih, g_ea], float)

bounds = [
    (0.1 * g_im, 3.0 * g_im),   # g_im
    (0.1 * g_ie, 3.0 * g_ie),   # g_ie
    (0.1 * g_ih, 3.0 * g_ih),   # g_ih
    (0.1 * g_ea, 3.0 * g_ea),   # g_ea
]

# Run L-BFGS-B
res = minimize(sse_g4, g0_4, method="L-BFGS-B", bounds=bounds)

# Extract results
g_im_hat, g_ie_hat, g_ih_hat, g_ea_hat = res.x

print(f"Optimization Success: {res.success}")
print(f"Final SSE: {res.fun:.4f}")
print("Learned Conductances vs True:")
print(f"  g_im: {g_im_hat:.4f} (True: {g_im:.4f})")
print(f"  g_ie: {g_ie_hat:.4f} (True: {g_ie:.4f})")
print(f"  g_ih: {g_ih_hat:.4f} (True: {g_ih:.4f})")
print(f"  g_ea: {g_ea_hat:.4f} (True: {g_ea:.4f})")

# ============ RBPF: GLOBAL RW-SV on Q + Liu–West on θ (log-space),
#               online alpha-histogram gating with continuous learning rate ============

# ---------------- Settings ----------------

Np = 9000
sigma_y_pf = 0.15

# Baseline process noise (per-state, K per step)
q_states = np.array([0.01] * 5, float)

# -------- Single global stochastic volatility (random walk on log α) ----------
alpha_min, alpha_max = 0.01, 25.0

# RW step size (same for all k)
sigma_eta_post = 0.1

# Liu–West (θ in log-space) - base parameters
a_lw  = 0.99
h2_lw = 1.0 - a_lw**2

# Gating parameters (α-based)
g_min = 0.05   # minimum learning rate (never fully freeze)

# Resampling threshold
resample_frac = 0.5

# Mixture sampling counts (for bands)
Nsamp_mixture_state = 2000

# ---------------- Helpers ----------------
def systematic_resample(w, rng):
    N = w.size
    u0 = (rng.random() + np.arange(N)) / N
    cs = np.cumsum(w)
    idx = np.empty(N, int)
    i = j = 0
    while i < N:
        if u0[i] < cs[j]:
            idx[i] = j
            i += 1
        else:
            j += 1
    return idx

def wquantile(x, w, qs):
    x = np.asarray(x); w = np.asarray(w)
    i = np.argsort(x)
    xs, ws = x[i], w[i]
    cw = np.cumsum(ws)
    if cw[-1] > 0:
        cw = cw / cw[-1]
    else:
        cw = np.linspace(1/len(ws), 1, len(ws))
    return np.interp(qs, cw, xs)

def logsumexp(v):
    m = np.max(v)
    return m + np.log(np.sum(np.exp(v - m)))

def sample_from_weighted_gaussian_mixture(means, variances, weights, Nsamp, rng):
    weights = np.asarray(weights, float)
    cw = np.cumsum(weights)
    if cw[-1] > 0:
        cw = cw / cw[-1]
    else:
        cw = np.linspace(1/len(weights), 1, len(weights))
    u = (rng.random(Nsamp) + np.arange(Nsamp)) / Nsamp
    idx = np.searchsorted(cw, u, side='right')
    idx = np.clip(idx, 0, len(weights)-1)
    stds = np.sqrt(np.maximum(variances[idx], 1e-12))
    return means[idx] + stds * rng.standard_normal(Nsamp)

# ---------------- Data ----------------
Y_meas  = np.asarray(Y_meas, float).ravel()
u_arr   = np.asarray(u, float).ravel()
T_out_K = np.asarray(T_out_K, float).ravel()
U_s_arr = np.asarray(U_s, float).ravel()
N       = int(len(Y_meas))

# Measurement matrix (Ti only)
C_y = np.array([[1, 0, 0, 0, 0]], float)

# True Ti (optional diag)
has_Ti_true = 'Y_Ti' in globals()
if has_Ti_true:
    Ti_true = np.asarray(Y_Ti, float).ravel()
    Ti_true_C = Ti_true - 273.15

# ---------------- θ definition ----------------
theta_names = [
    "Ci","Cm","Ce","Ch","Cs",
    "g_im","g_ie","g_ih","g_is","g_ea"
]

theta_true = np.array([
    Ci, Cm, Ce, Ch, Cs,
    g_im, g_ie, g_ih, g_is, g_ea
], float)

_param_defaults = {
    # Capacitances
    "Ci": Ci,
    "Cm": (0.1*Cm, 3*Cm),
    "Ce": (0.1*Ce, 3*Ce),
    "Ch": Ch,
    "Cs": Cs,
    # Conductances
    "g_im": (0.1*g_im, 3*g_im),
    "g_ie": (0.1*g_ie, 3*g_ie),
    "g_ih": (0.1*g_ih, 3*g_ih),
    "g_is": g_is,
    "g_ea": (0.1*g_ea, 3*g_ea)
}
param_ranges = _param_defaults

theta_eps = 1e-20
dθ        = len(theta_names)
theta_lo  = np.empty(dθ, float)
theta_hi  = np.empty(dθ, float)
is_fixed  = np.zeros(dθ, dtype=bool)

for j, nm in enumerate(theta_names):
    spec = param_ranges[nm]
    if isinstance(spec, (tuple, list)) and len(spec) == 2:
        lo, hi = float(spec[0]), float(spec[1])
    else:
        lo = hi = float(spec)
    lo = max(lo, theta_eps)
    hi = max(hi, theta_eps)
    theta_lo[j] = lo
    theta_hi[j] = hi
    is_fixed[j] = (hi == lo)

is_free   = ~is_fixed
free_idx  = np.nonzero(is_free)[0]
fixed_idx = np.nonzero(is_fixed)[0]

tau_defs = [
    ("Ci/g_im", 0, 5, Ci / g_im),
    ("Ci/g_ie", 0, 6, Ci / g_ie),
    ("Ci/g_ih", 0, 7, Ci / g_ih),
    ("Ci/g_is", 0, 8, Ci / g_is),
    ("Cm/g_im", 1, 5, Cm / g_im),
    ("Ce/g_ie", 2, 6, Ce / g_ie),
    ("Ce/g_ea", 2, 9, Ce / g_ea),
    ("Ch/g_ih", 3, 7, Ch / g_ih),
    ("Cs/g_is", 4, 8, Cs / g_is),
]
n_tau = len(tau_defs)

# ---------------- Initialization ----------------
rng = np.random.default_rng(123)
T_start_K = float(Y_meas[0]) if np.isfinite(Y_meas[0]) else float(T_out_K[0])

# KF state
m = np.tile(np.array([T_start_K]*5, float), (Np, 1))
P0 = np.diag(np.full(5, 0.2**2))
P  = np.tile(P0, (Np, 1, 1))

# Global alpha (single dynamic scalar, random walk in log-space)
log_alpha = rng.normal(0.0, 0.1, size=Np)
log_alpha = np.clip(log_alpha, np.log(alpha_min), np.log(alpha_max))
alpha     = np.exp(log_alpha)

# θ particles in log-space
phi_lo = np.log(np.clip(theta_lo, theta_eps, None))
phi_hi = np.log(np.clip(theta_hi, theta_eps, None))
phi    = rng.uniform(low=phi_lo[None, :], high=phi_hi[None, :], size=(Np, dθ))
if fixed_idx.size > 0:
    phi[:, fixed_idx] = np.log(np.clip(theta_lo[fixed_idx], theta_eps, None))
theta = np.exp(phi)

logw = np.full(Np, -np.log(Np), float)
Q0   = np.diag(q_states**2)
Q0_diag = np.diag(Q0).copy()
R    = np.array([[sigma_y_pf**2]], float)

# Gating bookkeeping (online α-histogram)
regime_flag   = np.zeros(N, dtype=int)  # 0 = quiet/learning-ish, 1 = high-vol/burst
z_std_innov   = np.zeros(N)

# Histogram settings for log(alpha)
n_bins_alpha  = 30
log_alpha_min = np.log(alpha_min)
log_alpha_max = np.log(alpha_max)
alpha_bin_edges = np.linspace(log_alpha_min, log_alpha_max, n_bins_alpha + 1)

# Pseudo-counts for a uniform prior over bins
pseudo_count = 1.0
alpha_hist_counts = np.full(n_bins_alpha, pseudo_count, dtype=float)

# Continuous gating thresholds in CDF-space:
F_quiet = 0.40   # bottom 40% of α-history => clearly "quiet"
F_burst = 0.95   # top 5% of α-history   => clearly "burst"

# Storage
q_lo, q_md, q_hi = 0.025, 0.50, 0.975
Ti_lo = np.zeros(N); Ti_md = np.zeros(N); Ti_hi = np.zeros(N)
Alpha_lo = np.zeros(N); Alpha_md = np.zeros(N); Alpha_hi = np.zeros(N)
Th_lo = np.zeros((N, dθ)); Th_md = np.zeros((N, dθ)); Th_hi = np.zeros((N, dθ))
Y_pred_mean = np.full(N, np.nan)
Y_pred_std  = np.full(N, np.nan)
Tau_lo = np.zeros((N, n_tau))
Tau_md = np.zeros((N, n_tau))
Tau_hi = np.zeros((N, n_tau))

# t=0 summaries
w_lin = np.exp(logw - logsumexp(logw))
Ti_draws_0 = sample_from_weighted_gaussian_mixture(m[:, 0], P[:, 0, 0], w_lin, Nsamp_mixture_state, rng)
TiC0 = Ti_draws_0 - 273.15
Ti_lo[0], Ti_md[0], Ti_hi[0] = np.quantile(TiC0, [q_lo, q_md, q_hi])
Alpha_lo[0], Alpha_md[0], Alpha_hi[0] = wquantile(alpha, w_lin, [q_lo, q_md, q_hi])
for j in range(dθ):
    Th_lo[0, j], Th_md[0, j], Th_hi[0, j] = wquantile(theta[:, j], w_lin, [q_lo, q_md, q_hi])
for t_idx, (_, c_idx, g_idx, _) in enumerate(tau_defs):
    tau_vals = theta[:, c_idx] / np.maximum(theta[:, g_idx], 1e-300)
    Tau_lo[0, t_idx], Tau_md[0, t_idx], Tau_hi[0, t_idx] = \
        wquantile(tau_vals, w_lin, [q_lo, q_md, q_hi])

# Initialize histogram with α-median at t=0
alpha_med_0 = Alpha_md[0]
log_alpha_med_0 = np.log(np.clip(alpha_med_0, alpha_min, alpha_max))
bin_idx_0 = np.searchsorted(alpha_bin_edges, log_alpha_med_0, side='right') - 1
bin_idx_0 = np.clip(bin_idx_0, 0, n_bins_alpha - 1)
alpha_hist_counts[bin_idx_0] += 1.0

# ---------------- CONTINUOUS-TIME MATRICES FROM θ (5-state) ---------------
def continuous_from_theta(theta_arr):
    """
    Build continuous-time A_c and input vectors B_u, B_To, B_Us
    for the 5-state RC model from per-particle θ.
    theta_arr shape: (Np, 10) with
      [Ci, Cm, Ce, Ch, Cs, g_im, g_ie, g_ih, g_is, g_ea]
    Returns:
      A_c   : (Np, 5, 5)
      B_u   : (Np, 5)  (heater power)
      B_To  : (Np, 5)  (outdoor temp)
      B_Us  : (Np, 5)  (solar)
    """
    Np_loc = theta_arr.shape[0]

    Ci  = theta_arr[:, 0]
    Cm  = theta_arr[:, 1]
    Ce  = theta_arr[:, 2]
    Ch  = theta_arr[:, 3]
    Cs  = theta_arr[:, 4]
    gim = theta_arr[:, 5]
    gie = theta_arr[:, 6]
    gih = theta_arr[:, 7]
    gis = theta_arr[:, 8]
    gea = theta_arr[:, 9]
    gia = np.zeros_like(gea)

    invC = np.stack([1.0/Ci, 1.0/Cm, 1.0/Ce, 1.0/Ch, 1.0/Cs], axis=1)

    # Conductance G entries
    G00 = -(gim + gie + gih + gis + gia)
    G01 = gim; G02 = gie; G03 = gih; G04 = gis
    G10 = gim; G11 = -gim
    G20 = gie; G22 = -(gie + gea)
    G30 = gih; G33 = -gih
    G40 = gis; G44 = -gis
    Z0  = np.zeros_like(G00)

    # A_c rows (then scaled by 1/C per row)
    A0 = np.stack([G00, G01, G02, G03, G04], axis=1) * invC[:, [0]]
    A1 = np.stack([G10, G11, Z0,  Z0,  Z0 ], axis=1) * invC[:, [1]]
    A2 = np.stack([G20, Z0,  G22, Z0,  Z0 ], axis=1) * invC[:, [2]]
    A3 = np.stack([G30, Z0,  Z0,  G33, Z0 ], axis=1) * invC[:, [3]]
    A4 = np.stack([G40, Z0,  Z0,  Z0,  G44], axis=1) * invC[:, [4]]
    A_c = np.stack([A0, A1, A2, A3, A4], axis=1)   # (Np, 5, 5)

    # Inputs (continuous-time):
    # B_u: heater input (u -> Th)
    B_u  = np.zeros((Np_loc, 5), float)
    B_u[:, 3] = eta_h / Ch

    # B_To: outdoor temperature
    B_To = np.zeros((Np_loc, 5), float)
    B_To[:, 0] = 0.0 * (1.0 / Ci)          # g_ia = 0
    B_To[:, 2] = gea * (1.0 / Ce)

    # B_Us: solar
    B_Us = np.zeros((Np_loc, 5), float)
    B_Us[:, 0] = Aw * (1.0 / Ci)
    B_Us[:, 2] = Ae * (1.0 / Ce)

    return A_c, B_u, B_To, B_Us

# ---------------- RBPF loop (Euler sub-stepping: 60s) ----------------
const_ll = -0.5 * np.log(2*np.pi)
I5_batch = np.eye(5)[None, :, :]

# substepping configuration
dt_total = dt_seconds           # measurement interval (e.g. 600s)
dt_sub_target = 60.0            # desired substep [s]
n_subs = max(1, int(round(dt_total / dt_sub_target)))
dt_sub = dt_total / n_subs      # actual substep used

print(f"RBPF with Euler sub-stepping: dt_total={dt_total}s, n_subs={n_subs}, dt_sub={dt_sub:.1f}s")
report_every = 50
_window_t0 = time.perf_counter()
state_arrays = [m, P, theta, logw, log_alpha, Q0_diag, R, C_y, I5_batch]
for k in range(1, N):
    uk, Tok, Usk = u_arr[k-1], T_out_K[k-1], U_s_arr[k-1]
    yk = float(Y_meas[k])

    # Prior weights
    w_lin_prior = np.exp(logw - logsumexp(logw))

    # (A) Global SV: random walk on log_alpha (always active)
    sigma_eta_eff = sigma_eta_post
    log_alpha = log_alpha + rng.normal(0.0, sigma_eta_eff, size=Np)
    log_alpha = np.clip(log_alpha, np.log(alpha_min), np.log(alpha_max))
    alpha     = np.exp(log_alpha)

    # Effective α for gating: weighted median under PRIOR weights
    alpha_med_k = wquantile(alpha, w_lin_prior, [0.5])[0]

    # (B) α-based gating with histogram
    log_alpha_med_k = np.log(np.clip(alpha_med_k, alpha_min, alpha_max))
    bin_idx = np.searchsorted(alpha_bin_edges, log_alpha_med_k, side='right') - 1
    bin_idx = np.clip(bin_idx, 0, n_bins_alpha - 1)
    alpha_hist_counts[bin_idx] += 1.0

    cdf_bins = np.cumsum(alpha_hist_counts)
    cdf_bins /= cdf_bins[-1]
    F_k = cdf_bins[bin_idx]

    if F_k <= F_quiet:
        g_alpha = 1.0
        regime_flag[k] = 0   # quiet / learning
    elif F_k >= F_burst:
        g_alpha = g_min
        regime_flag[k] = 1   # high-vol / burst
    else:
        r = (F_burst - F_k) / (F_burst - F_quiet + 1e-12)
        g_alpha = g_min + (1.0 - g_min) * r
        regime_flag[k] = 0   # treat as learning-ish

    g_k = max(g_alpha, g_min)

    # (C) Liu–West on θ (soft-gated by g_k)
    phi = np.log(np.clip(theta, theta_eps, None))

    if free_idx.size > 0:
        a_k  = 1.0 - g_k * (1.0 - a_lw)
        h2_k = g_k * h2_lw

        phi_bar_free = np.sum(phi[:, free_idx] * w_lin_prior[:, None], axis=0)

        diff_free = phi[:, free_idx] - phi_bar_free[None, :]
        V_free    = diff_free.T @ (diff_free * w_lin_prior[:, None])
        V_free    = 0.5 * (V_free + V_free.T) + 1e-12 * np.eye(free_idx.size)

        L_free   = np.linalg.cholesky(V_free)
        eps_free = rng.standard_normal((Np, free_idx.size)) @ (np.sqrt(h2_k) * L_free.T)

        phi[:, free_idx] = (
            a_k * phi[:, free_idx] +
            (1.0 - a_k) * phi_bar_free[None, :] +
            eps_free
        )

        phi[:, free_idx] = np.clip(
            phi[:, free_idx],
            phi_lo[None, free_idx],
            phi_hi[None, free_idx]
        )
    if fixed_idx.size > 0:
        phi[:, fixed_idx] = np.log(np.clip(theta_lo[fixed_idx], theta_eps, None))

    theta = np.exp(phi)

    # (D) Build per-particle CONTINUOUS-TIME matrices
    A_c_i, B_u_i, B_To_i, B_Us_i = continuous_from_theta(theta)

    # Kalman predict: mean via Euler sub-stepping, covariance via approx Φ = I + A_c * dt_total
    # ----------------------------------------------------------------------
    # Mean prediction with substeps
    m_pred = m.copy()
    for _ in range(n_subs):
        dx = np.einsum('nij,nj->ni', A_c_i, m_pred)
        dx += uk * B_u_i + Tok * B_To_i + Usk * B_Us_i
        m_pred += dx * dt_sub

    # Covariance prediction (one-shot Euler approximation over dt_total)
    Phi_approx = I5_batch + A_c_i * dt_total   # (Np,5,5)
    P_pred = np.einsum('nij,njk,nlk->nil', Phi_approx, P, Phi_approx)

    # Single dynamic scalar on Q (scaled by α)
    scale_sq = np.exp(2.0 * log_alpha)
    qdiag    = scale_sq[:, None] * Q0_diag[None, :]
    for s in range(5):
        P_pred[:, s, s] += qdiag[:, s]

    # (E) Prior predictive Y (1-step ahead)
    y_pred = (m_pred @ C_y.T).ravel()
    S      = np.einsum('ij,njk,kl->n', C_y, P_pred, C_y.T) + R[0, 0]
    S      = np.maximum(S, 1e-12)

    mu_k  = np.sum(w_lin_prior * y_pred)
    var_k = np.sum(w_lin_prior * (y_pred**2 + S)) - mu_k**2
    var_k = max(var_k, 1e-12)
    Y_pred_mean[k] = mu_k
    Y_pred_std[k]  = np.sqrt(var_k)
    z_std_innov[k] = (yk - mu_k) / np.sqrt(var_k)

    # (F) Weight update
    innov = yk - y_pred
    ll    = const_ll - 0.5*np.log(S) - 0.5*(innov**2)/S
    logw  = logw + ll
    logw  = logw - logsumexp(logw)
    w_lin_post = np.exp(logw)

    # (G) Kalman update
    K = (P_pred @ C_y.T) / S[:, None, None]
    m = m_pred + (K.reshape(Np, 5) * innov[:, None])
    KC = np.matmul(K, C_y)
    P  = np.matmul(I5_batch - KC, P_pred)

    # Summaries at time k
    Ti_draws = sample_from_weighted_gaussian_mixture(
        m[:, 0], P[:, 0, 0], w_lin_post, Nsamp_mixture_state, rng
    )
    TiC = Ti_draws - 273.15
    Ti_lo[k], Ti_md[k], Ti_hi[k] = np.quantile(TiC, [q_lo, q_md, q_hi])
    Alpha_lo[k], Alpha_md[k], Alpha_hi[k] = wquantile(alpha, w_lin_post, [q_lo, q_md, q_hi])

    for j in range(dθ):
        Th_lo[k, j], Th_md[k, j], Th_hi[k, j] = wquantile(
            theta[:, j], w_lin_post, [q_lo, q_md, q_hi]
        )

    for t_idx, (_, c_idx, g_idx, _) in enumerate(tau_defs):
        tau_vals = theta[:, c_idx] / np.maximum(theta[:, g_idx], 1e-300)
        Tau_lo[k, t_idx], Tau_md[k, t_idx], Tau_hi[k, t_idx] = \
            wquantile(tau_vals, w_lin_post, [q_lo, q_md, q_hi])

    # Resample if needed
    Neff = 1.0 / np.sum(w_lin_post * w_lin_post)
    if Neff < resample_frac * Np:
        idx = systematic_resample(w_lin_post, rng)
        m         = m[idx]
        P         = P[idx]
        log_alpha = log_alpha[idx]
        alpha     = alpha[idx]
        theta     = theta[idx]
        logw[:]   = -np.log(Np)
    if (k % report_every) == 0:
        elapsed = time.perf_counter() - _window_t0
        avg_step = elapsed / report_every
        rss = process_rss_mb()
        state_mb = arrays_size_mb(state_arrays)
        print(f"[k={k:6d}] avg {avg_step:.4f} s/step ({1.0/avg_step:.2f} steps/s), "
              f"STATE arrays={state_mb:.1f} MB, RSS={rss:.1f} MB")
        _window_t0 = time.perf_counter()
print("RBPF Complete (Euler sub-stepping, 1-step prediction/update).")

# ================================
# Frequency-domain convergence diagnostics

# How many RBPF steps to skip between TF evaluations.
SKIP_STEPS = 30

# Number of frequency points between DC and Nyquist
Nw = 300

# ------------------------------------------------------------
# 1) Offline LS parameter vector (your existing structure)
# ------------------------------------------------------------
theta_ls = np.array([
    Ci, Cm, Ce, Ch, Cs,
    g_im_hat, g_ie_hat, g_ih_hat, g_is, g_ea_hat
], float)
# If your theta has an extra entry (e.g. s_Q_scale), append it here
# so it matches theta_true and Th_md in length.

theta_true = np.array([
    Ci, Cm, Ce, Ch, Cs,
    g_im, g_ie, g_ih, g_is, g_ea
], float)

# ------------------------------------------------------------
# 2) Helpers: build SISO SS and compute H2-like energy error
# ------------------------------------------------------------

def _continuous_from_theta_single(theta):
    """
    Continuous-time A_c, B_c for a *single* θ vector:
      θ = [Ci, Cm, Ce, Ch, Cs, g_im, g_ie, g_ih, g_is, g_ea]
    Inputs (columns of B_c): [u (heater), T_out, U_s]
    Returns:
      A_c: (5,5)
      B_c: (5,3)
    """
    Ci, Cm, Ce, Ch, Cs = theta[0:5]
    g_im, g_ie, g_ih, g_is, g_ea = theta[5:10]
    g_ia = 0.0

    invC = np.array([1.0/Ci, 1.0/Cm, 1.0/Ce, 1.0/Ch, 1.0/Cs])

    # --- G matrix entries (symmetric conductances) ---
    G00 = -(g_im + g_ie + g_ih + g_is + g_ia)
    G01 = g_im
    G02 = g_ie
    G03 = g_ih
    G04 = g_is

    G10 = g_im
    G11 = -g_im

    G20 = g_ie
    G22 = -(g_ie + g_ea)

    G30 = g_ih
    G33 = -g_ih

    G40 = g_is
    G44 = -g_is

    # Assemble G as 5x5
    A_c = np.zeros((5, 5), float)
    A_c[0, :] = [G00, G01, G02, G03, G04]
    A_c[1, :] = [G10, G11, 0.0, 0.0, 0.0]
    A_c[2, :] = [G20, 0.0, G22, 0.0, 0.0]
    A_c[3, :] = [G30, 0.0, 0.0, G33, 0.0]
    A_c[4, :] = [G40, 0.0, 0.0, 0.0, G44]

    # Scale rows by 1/C
    A_c = (A_c.T * invC).T

    # --- Continuous-time input matrix B_c (5x3) ---
    # Columns: [u (heater), T_out, U_s]
    B_c = np.zeros((5, 3), float)

    # u -> Th
    B_c[3, 0] = eta_h * invC[3]

    # T_out -> Ti (g_ia=0) and Te (g_ea)
    B_c[0, 1] = g_ia * invC[0]       # =0 in practice
    B_c[2, 1] = g_ea * invC[2]

    # U_s -> Ti (Aw) and Te (Ae)
    B_c[0, 2] = Aw * invC[0]
    B_c[2, 2] = Ae * invC[2]

    return A_c, B_c


def build_siso_ss_from_theta(theta, channel):
    """
    Build a SISO *discrete-time* state-space model for a given input channel:
      'solar'   : U_s     -> Ti
      'heater'  : u       -> Ti
      'outside' : T_out   -> Ti

    Uses ZOH discretization via cont2discrete.
    """
    # 1) Continuous-time model
    A_c, B_c = _continuous_from_theta_single(theta)

    # 2) SISO selection index for each channel in B_c columns
    if channel == 'heater':
        col_idx = 0
    elif channel == 'outside':
        col_idx = 1
    elif channel == 'solar':
        col_idx = 2
    else:
        raise ValueError(f"Unknown channel: {channel}")

    # 3) Discretize MIMO (5x3) to get A_d, B_d, C_d, D_d, then pick 1 column
    # Measurement: Ti only
    C = C_y.copy()                  # shape (1,5)
    D = np.zeros((1, 3), float)     # no direct feedthrough

    A_d, B_d, C_d, D_d, _ = cont2discrete(
        (A_c, B_c, C, D),
        dt_seconds,
        method="zoh"
    )

    # 4) Make SISO system (Ti output, chosen input)
    B_siso = B_d[:, [col_idx]]      # (5,1)
    D_siso = D_d[:, [col_idx]]      # (1,1)

    sys = control.ss(A_d, B_siso, C_d, D_siso, dt=dt_seconds)
    return sys


def tf_h2_error(theta_est, theta_true, channel, w_grid):
    """
    H2-like energy error between learned and true TF for one channel.

    Approximate:
        ||G_est - G_true||_H2 ≈ sqrt( mean_ω |G_est(e^{jw}) - G_true(e^{jw})|^2 )
    over the given frequency grid w_grid.
    """
    sys_true = build_siso_ss_from_theta(theta_true, channel)
    sys_est  = build_siso_ss_from_theta(theta_est,  channel)

    # python-control: mag, phase, omega
    mag_true, phase_true, _ = control.freqresp(sys_true, w_grid)
    mag_est,  phase_est,  _ = control.freqresp(sys_est,  w_grid)

    mag_true  = mag_true.squeeze()
    mag_est   = mag_est.squeeze()
    phase_true = phase_true.squeeze()
    phase_est  = phase_est.squeeze()

    # Complex FRFs
    G_true = mag_true * np.exp(1j * phase_true)
    G_est  = mag_est  * np.exp(1j * phase_est)

    diff = G_est - G_true
    # RMS of complex error over frequency grid (H2-like)
    E = np.sqrt(np.mean(np.abs(diff)**2))

    return E


def tf_h2_norm(theta, channel, w_grid):
    """
    H2-like norm of a single-channel FRF:
        ||G||_H2 ≈ sqrt( mean_ω |G(e^{jw})|^2 )
    """
    sys = build_siso_ss_from_theta(theta, channel)
    mag, phase, _ = control.freqresp(sys, w_grid)
    G = mag.squeeze() * np.exp(1j * phase.squeeze())
    return np.sqrt(np.mean(np.abs(G)**2))


# ------------------------------------------------------------
# 3) Frequency grid (0 .. Nyquist)
# ------------------------------------------------------------
# For sample time dt_seconds, Nyquist angular frequency is pi / dt_seconds [rad/s].
w_grid = np.linspace(0.0, np.pi / dt_seconds, Nw)

channels = ['solar', 'heater', 'outside']

# ------------------------------------------------------------
# 4) Baseline: offline LS vs true (constant per channel)
# ------------------------------------------------------------
baseline_errors = {}
for ch in channels:
    baseline_errors[ch] = tf_h2_error(
        theta_est=theta_ls,
        theta_true=theta_true,
        channel=ch,
        w_grid=w_grid
    )

print("Baseline offline LS H2-like TF energy errors:")
for ch in channels:
    print(f"  {ch:8s}: {baseline_errors[ch]:.6e}")

# ------------------------------------------------------------
# 5) RBPF: time-varying H2-like TF energy error vs true
#    Use parameter medians Th_md from RBPF.
# ------------------------------------------------------------
Theta_rbpf = Th_md   # shape (N_T, d_theta)

N_T, d_theta_rbpf = Theta_rbpf.shape
assert d_theta_rbpf == len(theta_true), "RBPF θ dimension mismatch."

sample_indices = np.arange(0, N_T, SKIP_STEPS)
t_hours = sample_indices * dt_seconds / 3600.0

rbpf_errors = {ch: np.zeros_like(sample_indices, dtype=float) for ch in channels}

for idx, k in enumerate(sample_indices):
    theta_k = Theta_rbpf[k, :]  # RBPF parameters at time k

    for ch in channels:
        rbpf_errors[ch][idx] = tf_h2_error(
            theta_est=theta_k,
            theta_true=theta_true,
            channel=ch,
            w_grid=w_grid
        )

# Print final RBPF error (last TF evaluated) per channel
print("\nFinal RBPF H2-like TF energy errors (last evaluated time):")
for ch in channels:
    print(f"  {ch:8s}: {rbpf_errors[ch][-1]:.6e}")

# Relative errors vs true H2-norm
for ch in channels:
    norm_true = tf_h2_norm(theta_true, ch, w_grid)
    err_ls    = baseline_errors[ch]
    err_rbpf  = rbpf_errors[ch][-1]
    print(f"{ch}: rel LS={err_ls/norm_true:.3e}, rel RBPF={err_rbpf/norm_true:.3e}")

# ================================
# Frequency-domain convergence diagnostics (naive band-limited relative error)
# ================================

#from scipy.signal import cont2discrete

# How many RBPF steps to skip between TF evaluations.
SKIP_STEPS = 30

# Number of frequency points between DC and Nyquist
Nw = 300

# Fraction of true output energy (per channel) used to define the band
# e.g. 0.90 = 90%, 0.999 = 99.9%
ENERGY_FRAC = 0.90

# If True, ignore ENERGY_FRAC and use the full band [0, Nyquist]
USE_FULL_BAND = False

# ------------------------------------------------------------
# 1) Offline LS parameter vector (your existing structure)
# ------------------------------------------------------------
theta_ls = np.array([
    Ci, Cm, Ce, Ch, Cs,
    g_im_hat, g_ie_hat, g_ih_hat, g_is, g_ea_hat
], float)

# True parameter vector (from your data generation model)
theta_true = np.array([
    Ci, Cm, Ce, Ch, Cs,
    g_im, g_ie, g_ih, g_is, g_ea
], float)

# ------------------------------------------------------------
# 2) Helpers: build SISO SS, input PSD and band info
# ------------------------------------------------------------

def _continuous_from_theta_single(theta):
    """
    Continuous-time A_c, B_c for a *single* θ vector:
      θ = [Ci, Cm, Ce, Ch, Cs, g_im, g_ie, g_ih, g_is, g_ea]
    Inputs (columns of B_c): [u (heater), T_out, U_s]
    Returns:
      A_c: (5,5)
      B_c: (5,3)
    """
    Ci, Cm, Ce, Ch, Cs = theta[0:5]
    g_im, g_ie, g_ih, g_is, g_ea = theta[5:10]
    g_ia = 0.0

    invC = np.array([1.0/Ci, 1.0/Cm, 1.0/Ce, 1.0/Ch, 1.0/Cs])

    # --- G-like entries for conductance network ---
    G00 = -(g_im + g_ie + g_ih + g_is + g_ia)
    G01 = g_im
    G02 = g_ie
    G03 = g_ih
    G04 = g_is

    G10 = g_im
    G11 = -g_im

    G20 = g_ie
    G22 = -(g_ie + g_ea)

    G30 = g_ih
    G33 = -g_ih

    G40 = g_is
    G44 = -g_is

    # Assemble A_c from G and then scale rows by 1/C
    A_c = np.zeros((5, 5), float)
    A_c[0, :] = [G00, G01, G02, G03, G04]
    A_c[1, :] = [G10, G11, 0.0, 0.0, 0.0]
    A_c[2, :] = [G20, 0.0, G22, 0.0, 0.0]
    A_c[3, :] = [G30, 0.0, 0.0, G33, 0.0]
    A_c[4, :] = [G40, 0.0, 0.0, 0.0, G44]

    A_c = (A_c.T * invC).T

    # Continuous-time input matrix B_c (5x3), columns: [u, T_out, U_s]
    B_c = np.zeros((5, 3), float)

    # u -> Th
    B_c[3, 0] = eta_h * invC[3]

    # T_out -> Ti (g_ia=0) and Te (g_ea)
    B_c[0, 1] = g_ia * invC[0]       # =0 here
    B_c[2, 1] = g_ea * invC[2]

    # U_s -> Ti (Aw) and Te (Ae)
    B_c[0, 2] = Aw * invC[0]
    B_c[2, 2] = Ae * invC[2]

    return A_c, B_c


def build_siso_ss_from_theta(theta, channel):
    """
    Build a SISO discrete-time state-space model for a given input channel:
      'solar'   : U_s     -> Ti
      'heater'  : u       -> Ti
      'outside' : T_out   -> Ti

    Uses ZOH discretization via cont2discrete.
    """
    # 1) Continuous-time model
    A_c, B_c = _continuous_from_theta_single(theta)

    # 2) Select which column of B_c corresponds to the channel
    if channel == 'heater':
        col_idx = 0
    elif channel == 'outside':
        col_idx = 1
    elif channel == 'solar':
        col_idx = 2
    else:
        raise ValueError(f"Unknown channel: {channel}")

    # 3) Discretize the full MIMO system, then select one input channel
    C = C_y.copy()                  # (1,5), Ti measurement
    D = np.zeros((1, 3), float)     # no direct feedthrough

    A_d, B_d, C_d, D_d, _ = cont2discrete(
        (A_c, B_c, C, D),
        dt_seconds,
        method="zoh"
    )

    B_siso = B_d[:, [col_idx]]      # (5,1)
    D_siso = D_d[:, [col_idx]]      # (1,1)

    sys = control.ss(A_d, B_siso, C_d, D_siso, dt=dt_seconds)
    return sys


def compute_input_psd_on_grid(u, w_grid, dt):
    """
    Compute an (unnormalized) one-sided PSD of the input sequence u,
    and interpolate it onto the angular frequency grid w_grid [rad/s].

    Any overall scaling cancels in the relative band selection, so we
    do not worry about exact normalization constants here.
    """
    u = np.asarray(u, float).ravel()
    u = u - np.mean(u)

    N = len(u)
    U = np.fft.rfft(u)
    Su_fft = np.abs(U)**2           # proportional to PSD
    f_fft = np.fft.rfftfreq(N, d=dt)

    # Map w_grid [rad/s] to Hz and interpolate PSD
    f_grid = w_grid / (2.0 * np.pi)
    Su_grid = np.interp(f_grid, f_fft, Su_fft, left=0.0, right=0.0)

    return Su_grid


def prepare_tf_band_info(theta_true, channel, u_input, w_grid,
                         energy_frac=0.99, use_full_band=False):
    """
    For a given channel, build the true TF, compute the input PSD on the
    same frequency grid, and determine the band over which TF errors
    will be evaluated.

    If use_full_band is False:
        - Determine the smallest band [0, w_cut] that contains
          `energy_frac` of the true output energy:
              E_true(ω) = |G_true(e^{jω})|^2 * S_u(ω)

    If use_full_band is True:
        - Use the full band [0, Nyquist] (i.e. all w_grid points).

    Returns a dict with:
        Su_grid   : PSD on w_grid
        band_mask : boolean mask selecting the band
        true_norm : RMS magnitude of G_true over that band
        f_cut     : cutoff frequency in Hz (w_cut / 2π)
        f_nyq     : Nyquist frequency in Hz (1 / (2*dt))
    """
    sys_true = build_siso_ss_from_theta(theta_true, channel)
    mag_true, phase_true, _ = control.freqresp(sys_true, w_grid)
    G_true = mag_true.squeeze() * np.exp(1j * phase_true.squeeze())

    # Input PSD on grid
    Su_grid = compute_input_psd_on_grid(u_input, w_grid, dt_seconds)

    if use_full_band:
        band_mask = np.ones_like(w_grid, dtype=bool)
    else:
        # True output energy density = |G_true|^2 * S_u
        E_true = (np.abs(G_true)**2) * Su_grid
        E_tot = np.sum(E_true)

        if not np.isfinite(E_tot) or E_tot <= 0.0:
            # Fallback: no meaningful energy, keep full band
            band_mask = np.ones_like(w_grid, dtype=bool)
        else:
            cum = np.cumsum(E_true)
            ratio = cum / E_tot
            k_cut = int(np.searchsorted(ratio, energy_frac))
            k_cut = min(max(k_cut, 0), len(w_grid) - 1)
            band_mask = np.zeros_like(w_grid, dtype=bool)
            band_mask[:k_cut + 1] = True

    G_true_band = G_true[band_mask]
    true_norm = float(np.sqrt(np.mean(np.abs(G_true_band)**2))) if G_true_band.size > 0 else 0.0

    w_cut = w_grid[band_mask].max()
    f_cut = float(w_cut / (2.0 * np.pi))
    f_nyq = float(1.0 / (2.0 * dt_seconds))

    return {
        "Su_grid": Su_grid,
        "band_mask": band_mask,
        "true_norm": true_norm,
        "f_cut": f_cut,
        "f_nyq": f_nyq,
    }


def tf_naive_errors(theta_est, theta_true, channel, w_grid, band_info, eps=1e-8):
    """
    Naive band-limited TF errors for one channel, on the chosen band
    (either the ENERGY_FRAC-band of true output energy, or the full band).

    We compute:
      - abs_err   : RMS of |G_est - G_true| over the band
      - rel_err   : RMS of |(G_est - G_true) / G_true| over the band
      - hinf_abs  : max_ω |G_est - G_true| over the band (H_infinity-like)
      - hinf_rel  : hinf_abs / max_ω |G_true| over the band
    """
    sys_true = build_siso_ss_from_theta(theta_true, channel)
    sys_est  = build_siso_ss_from_theta(theta_est,  channel)

    mag_true, phase_true, _ = control.freqresp(sys_true, w_grid)
    mag_est,  phase_est,  _ = control.freqresp(sys_est,  w_grid)

    G_true = mag_true.squeeze() * np.exp(1j * phase_true.squeeze())
    G_est  = mag_est.squeeze()  * np.exp(1j * phase_est.squeeze())

    mask = band_info["band_mask"]
    G_true_band = G_true[mask]
    G_est_band  = G_est[mask]

    if G_true_band.size == 0:
        return np.nan, np.nan, np.nan, np.nan

    diff = G_est_band - G_true_band

    # Absolute RMS error: RMS of |G_est - G_true|
    abs_err = float(np.sqrt(np.mean(np.abs(diff)**2)))

    # Pointwise relative error; guard against |G_true| ~ 0
    denom = np.where(np.abs(G_true_band) < eps, np.nan, G_true_band)
    rel_pt = diff / denom
    rel_pt = rel_pt[~np.isnan(rel_pt)]

    if rel_pt.size == 0:
        rel_err = np.nan
    else:
        rel_err = float(np.sqrt(np.mean(np.abs(rel_pt)**2)))

    # H_infinity-like errors over the same band
    hinf_abs = float(np.max(np.abs(diff)))
    max_true = float(np.max(np.abs(G_true_band))) if G_true_band.size > 0 else 0.0
    hinf_rel = float(hinf_abs / max_true) if max_true > eps else np.nan

    return abs_err, rel_err, hinf_abs, hinf_rel


# ------------------------------------------------------------
# 3) Frequency grid (0 .. Nyquist)
# ------------------------------------------------------------
w_grid = np.linspace(0.0, np.pi / dt_seconds, Nw)
channels = ['solar', 'heater', 'outside']

# Map channels to their input time series
input_signals = {
    'heater':  np.asarray(u, float).ravel(),        # Heater (W)
    'solar':   np.asarray(U_s, float).ravel(),      # Solar (W/m^2)
    'outside': np.asarray(T_out_K, float).ravel(),  # Outside temperature (K)
}

# ------------------------------------------------------------
# 4) Precompute band and norms for each channel
# ------------------------------------------------------------
tf_band_info = {}

if USE_FULL_BAND:
    print("\nFrequency bands: full band [0, Nyquist] (ignoring ENERGY_FRAC).")
else:
    print(f"\nInput-spectrum-weighted frequency bands "
          f"({ENERGY_FRAC*100:.1f}% true output energy):")

for ch in channels:
    info = prepare_tf_band_info(
        theta_true=theta_true,
        channel=ch,
        u_input=input_signals[ch],
        w_grid=w_grid,
        energy_frac=ENERGY_FRAC,
        use_full_band=USE_FULL_BAND,
    )
    tf_band_info[ch] = info
    f_cut = info["f_cut"]
    f_nyq = info["f_nyq"]
    if USE_FULL_BAND:
        print(f"  {ch:8s}: band = [0, {f_nyq:.4f}] Hz (full band; f_cut/f_Nyq = 1.000)")
    else:
        print(f"  {ch:8s}: f_cut = {f_cut:.4f} Hz  "
              f"({f_cut/f_nyq:.3f} of Nyquist {f_nyq:.4f} Hz)")

# ------------------------------------------------------------
# 5) Baseline: offline LS vs true (constant per channel)
# ------------------------------------------------------------
baseline_errors_abs   = {}
baseline_errors_rel   = {}
baseline_hinf_abs     = {}
baseline_hinf_rel     = {}

for ch in channels:
    e_abs, e_rel, h_abs, h_rel = tf_naive_errors(
        theta_est=theta_ls,
        theta_true=theta_true,
        channel=ch,
        w_grid=w_grid,
        band_info=tf_band_info[ch],
    )
    baseline_errors_abs[ch] = e_abs
    baseline_errors_rel[ch] = e_rel
    baseline_hinf_abs[ch]   = h_abs
    baseline_hinf_rel[ch]   = h_rel

print("\nBaseline offline LS naive TF errors (selected band):")
for ch in channels:
    print(f"  {ch:8s}: "
          f"RMS_abs={baseline_errors_abs[ch]:.6e},  "
          f"RMS_rel={baseline_errors_rel[ch]:.3e},  "
          f"Hinf_abs={baseline_hinf_abs[ch]:.6e},  "
          f"Hinf_rel={baseline_hinf_rel[ch]:.3e}")

# ------------------------------------------------------------
# 6) RBPF: time-varying naive TF errors vs true
#    Use parameter medians Th_md from RBPF.
# ------------------------------------------------------------
Theta_rbpf = Th_md   # shape (N_T, d_theta)
N_T, d_theta_rbpf = Theta_rbpf.shape
assert d_theta_rbpf == len(theta_true), "RBPF θ dimension mismatch."

sample_indices = np.arange(0, N_T, SKIP_STEPS)
t_hours = sample_indices * dt_seconds / 3600.0

rbpf_errors_abs = {ch: np.zeros_like(sample_indices, dtype=float) for ch in channels}
rbpf_errors_rel = {ch: np.zeros_like(sample_indices, dtype=float) for ch in channels}
rbpf_hinf_abs   = {ch: np.zeros_like(sample_indices, dtype=float) for ch in channels}
rbpf_hinf_rel   = {ch: np.zeros_like(sample_indices, dtype=float) for ch in channels}

for idx, k in enumerate(sample_indices):
    theta_k = Theta_rbpf[k, :]  # RBPF parameters at time k

    for ch in channels:
        e_abs, e_rel, h_abs, h_rel = tf_naive_errors(
            theta_est=theta_k,
            theta_true=theta_true,
            channel=ch,
            w_grid=w_grid,
            band_info=tf_band_info[ch],
        )
        rbpf_errors_abs[ch][idx] = e_abs
        rbpf_errors_rel[ch][idx] = e_rel
        rbpf_hinf_abs[ch][idx]   = h_abs
        rbpf_hinf_rel[ch][idx]   = h_rel

print("\nFinal RBPF naive TF errors (last evaluated time, selected band):")
for ch in channels:
    print(f"  {ch:8s}: "
          f"RMS_abs={rbpf_errors_abs[ch][-1]:.6e},  "
          f"RMS_rel={rbpf_errors_rel[ch][-1]:.3e},  "
          f"Hinf_abs={rbpf_hinf_abs[ch][-1]:.6e},  "
          f"Hinf_rel={rbpf_hinf_rel[ch][-1]:.3e}")

print("\nTrue TF RMS magnitudes over selected band and naive relative errors:")
for ch in channels:
    norm_true = tf_band_info[ch]["true_norm"]
    print(f"  {ch:8s}: ||G_true||_RMS ≈ {norm_true:.6e},  "
          f"RMS_rel_LS={baseline_errors_rel[ch]:.3e},  "
          f"RMS_rel_RBPF={rbpf_errors_rel[ch][-1]:.3e},  "
          f"Hinf_rel_LS={baseline_hinf_rel[ch]:.3e},  "
          f"Hinf_rel_RBPF={rbpf_hinf_rel[ch][-1]:.3e}")

# -----------------------------------------------
# 1) Parameter Setup (Linear Bounds → Log-Space)
# -----------------------------------------------
theta_eps = 1e-20
theta_lo = np.empty(len(theta_names), float)
theta_hi = np.empty(len(theta_names), float)
is_fixed = np.zeros(len(theta_names), dtype=bool)

for j, nm in enumerate(theta_names):
    spec = param_ranges[nm]
    if isinstance(spec, (tuple, list)) and len(spec) == 2:
        lo, hi = float(spec[0]), float(spec[1])
    else:
        lo = hi = float(spec)
    lo = max(lo, theta_eps); hi = max(hi, theta_eps)
    theta_lo[j] = lo
    theta_hi[j] = hi
    is_fixed[j] = (hi == lo)

free_idx  = np.nonzero(~is_fixed)[0]
fixed_idx = np.nonzero(is_fixed)[0]
n_free    = free_idx.size

# Helper: build full θ from free log-parameters
def theta_from_phi(phi_log, theta_base, free_idx):
    theta_full = theta_base.copy()
    theta_full[free_idx] = np.exp(phi_log)
    return theta_full

# -----------------------------------------------
# 2) ZOH Discretization Helper (A_c,B_c → A_d,B_d)
#    x_{k+1} = Phi x_k + Gu u_k + GTo T_out_k + GUs U_s_k
# -----------------------------------------------
def discrete_system_zoh(theta_full, dt):
    """
    ZOH discretization of the 5R5C building model.

    Continuous model:
        x_dot = A_c x + B_u u + B_To T_out + B_Us U_s

    Discrete (ZOH):
        x_{k+1} = Phi x_k + Gu u_k + GTo T_out_k + GUs U_s_k
    """
    Ci, Cm, Ce, Ch, Cs = theta_full[0], theta_full[1], theta_full[2], theta_full[3], theta_full[4]
    g_im, g_ie, g_ih, g_is, g_ea = theta_full[5], theta_full[6], theta_full[7], theta_full[8], theta_full[9]
    g_ia = 0.0

    invC = np.array([1.0/Ci, 1.0/Cm, 1.0/Ce, 1.0/Ch, 1.0/Cs])

    # --- Construct Continuous A matrix (5x5) ---
    d0 = -(g_im + g_ie + g_ih + g_is + g_ia)
    d1 = -g_im
    d2 = -(g_ie + g_ea)
    d3 = -g_ih
    d4 = -g_is

    A_c = np.zeros((5,5))
    A_c[0,:] = [d0,   g_im, g_ie, g_ih, g_is]
    A_c[1,:] = [g_im, d1,   0.0,  0.0,  0.0 ]
    A_c[2,:] = [g_ie, 0.0,  d2,   0.0,  0.0 ]
    A_c[3,:] = [g_ih, 0.0,  0.0,  d3,   0.0 ]
    A_c[4,:] = [g_is, 0.0,  0.0,  0.0,  d4  ]

    # Scale rows by 1/C
    A_c = (A_c.T * invC).T

    # --- Construct Continuous B matrices ---
    B_u  = np.zeros(5); B_u[3]  = eta_h * invC[3]
    B_To = np.zeros(5); B_To[2] = g_ea  * invC[2]
    B_Us = np.zeros(5); B_Us[0] = Aw * invC[0]; B_Us[2] = Ae * invC[2]

    # Stack into a single B_c with 3 inputs: [u, T_out, U_s]
    B_c = np.column_stack((B_u, B_To, B_Us))

    # Dummy C,D for cont2discrete (we only care about A_d, B_d)
    C_dummy = np.eye(5)
    D_dummy = np.zeros((5, 3))

    A_d, B_d, _, _, _ = cont2discrete((A_c, B_c, C_dummy, D_dummy),
                                      dt,
                                      method="zoh")
    Phi = A_d
    Gu  = B_d[:, 0]
    GTo = B_d[:, 1]
    GUs = B_d[:, 2]

    return Phi, Gu, GTo, GUs

# Helper for numerical Jacobian: x_{k+1}(phi_log)
def f_x_next(phi_log, x_k, uk, Tok, Usk, dt):
    theta_full = theta_from_phi(phi_log, theta0_full, free_idx)
    Phi, Gu, GTo, GUs = discrete_system_zoh(theta_full, dt)
    return Phi @ x_k + uk*Gu + Tok*GTo + Usk*GUs  # shape (5,)

# -----------------------------------------------
# 3) Data Setup
# -----------------------------------------------
Y_meas  = np.asarray(Y_meas, float).ravel()
u_arr   = np.asarray(u, float).ravel()
T_out_K = np.asarray(T_out_K, float).ravel()
U_s_arr = np.asarray(U_s, float).ravel()
N       = int(len(Y_meas))

R = np.array([[sigma_y_pf**2]], float)

# Process noise for STATES
q_states = np.array([0.03]*5, float)
Qx_base  = np.diag(q_states**2)

# Process noise for LOG-PARAMETERS
# std=0.002 in log space means ~0.2% multiplicative drift per step
sigma_log_theta_rw = 0.002
Q_log_theta = np.diag(np.full(n_free, sigma_log_theta_rw**2))

# -----------------------------------------------
# 4) Log-EKF Initialization (FilterPy)
# -----------------------------------------------
x0 = np.array([Y_meas[0]]*5, float)

# Init theta in Linear Space, convert to Log Space
theta0_full = theta_lo.copy()
theta0_full[free_idx] = 0.5 * (theta_lo[free_idx] + theta_hi[free_idx])
phi0_free = np.log(theta0_full[free_idx])

# Augmented State z = [x; phi]
z0 = np.concatenate([x0, phi0_free], axis=0)
nz = z0.size

# Initial covariance
P0 = np.zeros((nz, nz), float)
P0[:5, :5] = np.diag(np.full(5, 0.2**2))
P0[5:, 5:] = np.diag(np.full(n_free, 0.3**2))  # log-space variance

# Build augmented Q
Q_aug = np.zeros((nz, nz), float)
Q_aug[:5, :5] = Qx_base
Q_aug[5:, 5:] = Q_log_theta

# Set up FilterPy EKF
ekf = ExtendedKalmanFilter(dim_x=nz, dim_z=1)
ekf.x = z0.copy()
ekf.P = P0.copy()
ekf.Q = Q_aug.copy()
ekf.R = R.copy()

# Measurement functions (Ti only)
def hx(z):
    # measurement is indoor temperature Ti
    return np.array([z[0]])

def H_jacobian(z):
    H = np.zeros((1, nz))
    H[0, 0] = 1.0
    return H

# -----------------------------------------------
# 5) Storage
# -----------------------------------------------
Ti_mean_ekf    = np.zeros(N)
Ti_var_ekf     = np.zeros(N)
Yhat           = np.zeros(N)
S_arr          = np.zeros(N)
Theta_traj_ekf = np.zeros((N, len(theta_names)))  # linear θ

# t = 0 save
Ti_mean_ekf[0]    = ekf.x[0]
Ti_var_ekf[0]     = ekf.P[0,0]
Yhat[0]           = ekf.x[0]
S_arr[0]          = ekf.P[0,0] + ekf.R[0,0]
Theta_traj_ekf[0] = theta0_full.copy()

# -----------------------------------------------
# 6) EKF Loop (Log-Space + ZOH, with SciPy Jacobian)
# -----------------------------------------------
print("Running Log-Space EKF (ZOH, FilterPy, SciPy Jacobian)...")

for k in range(1, N):
    uk  = u_arr[k-1]
    Tok = T_out_K[k-1]
    Usk = U_s_arr[k-1]
    yk  = float(Y_meas[k])

    # Unpack
    x_k   = ekf.x[:5].copy()
    phi_k = ekf.x[5:].copy()

    # 1. Physics in Linear Space (ZOH discretization)
    theta_full = theta_from_phi(phi_k, theta0_full, free_idx)
    Phi_k, Gu_k, GTo_k, GUs_k = discrete_system_zoh(theta_full, dt_seconds)

    # 2. Predict state (ZOH)
    x_pred   = Phi_k @ x_k + uk*Gu_k + Tok*GTo_k + Usk*GUs_k
    phi_pred = phi_k
    z_pred   = np.concatenate([x_pred, phi_pred])

    # 3. Jacobian F = d(z_next)/d(z)
    F = np.eye(nz)
    # ∂x_next/∂x = Phi_k (linear in x)
    F[:5, :5] = Phi_k

    # ∂x_next/∂phi via SciPy numerical differentiation
    J_phi = approx_derivative(
        lambda phi: f_x_next(phi, x_k, uk, Tok, Usk, dt_seconds),
        phi_k,
        method='2-point',      # or '3-point'
        rel_step=1e-5
    )  # shape (5, n_free)

    F[:5, 5:] = J_phi

    # 4. Predict covariance with F and Q
    P_pred = F @ ekf.P @ F.T + ekf.Q

    # Put prediction into the EKF object
    ekf.x = z_pred
    ekf.P = P_pred
    ekf.F = F  # optional, but keeps EKF state consistent

    # Predicted measurement and innovation variance (for logging)
    y_pred = hx(z_pred)[0]
    H_aug  = H_jacobian(z_pred)
    S      = (H_aug @ P_pred @ H_aug.T + ekf.R).item()

    # 5. Measurement update via FilterPy EKF
    z_meas = np.array([yk])
    ekf.update(z_meas, HJacobian=H_jacobian, Hx=hx)

    # 6. Store results
    Ti_mean_ekf[k] = ekf.x[0]
    Ti_var_ekf[k]  = ekf.P[0,0]
    Yhat[k]        = y_pred
    S_arr[k]       = S

    theta_k = theta_from_phi(ekf.x[5:], theta0_full, free_idx)
    Theta_traj_ekf[k] = theta_k

# Explicitly calculate bands for later (convert to °C)
Ti_lo_ekf = (Ti_mean_ekf - 1.96*np.sqrt(Ti_var_ekf)) - 273.15
Ti_hi_ekf = (Ti_mean_ekf + 1.96*np.sqrt(Ti_var_ekf)) - 273.15

print("Log-Space EKF (FilterPy, ZOH, SciPy Jacobian) Complete.")

from filterpy.kalman import UnscentedKalmanFilter, MerweScaledSigmaPoints

theta_eps = 1e-20
theta_lo = np.empty(len(theta_names), float)
theta_hi = np.empty(len(theta_names), float)
is_fixed = np.zeros(len(theta_names), dtype=bool)

for j, nm in enumerate(theta_names):
    spec = param_ranges[nm]
    if isinstance(spec, (tuple, list)) and len(spec) == 2:
        lo, hi = float(spec[0]), float(spec[1])
    else:
        lo = hi = float(spec)
    lo = max(lo, theta_eps); hi = max(hi, theta_eps)
    theta_lo[j] = lo
    theta_hi[j] = hi
    is_fixed[j] = (hi == lo)

free_idx  = np.nonzero(~is_fixed)[0]
fixed_idx = np.nonzero(is_fixed)[0]
n_free    = free_idx.size

# -----------------------------------------------
# 2) ZOH Discretization Helper (Same structure as EKF)
# -----------------------------------------------
def discrete_system_zoh(theta_full, dt):
    """
    ZOH discretization of the 5R5C building model.

    Continuous:
        x_dot = A_c x + B_u u + B_To T_out + B_Us U_s

    Discrete (ZOH):
        x_{k+1} = Phi x_k + Gu u_k + GTo T_out_k + GUs U_s_k
    """
    Ci, Cm, Ce, Ch, Cs = theta_full[0], theta_full[1], theta_full[2], theta_full[3], theta_full[4]
    g_im, g_ie, g_ih, g_is, g_ea = theta_full[5], theta_full[6], theta_full[7], theta_full[8], theta_full[9]
    g_ia = 0.0

    invC = np.array([1.0/Ci, 1.0/Cm, 1.0/Ce, 1.0/Ch, 1.0/Cs])

    # --- Continuous A matrix (5x5) ---
    d0 = -(g_im + g_ie + g_ih + g_is + g_ia)
    d1 = -g_im
    d2 = -(g_ie + g_ea)
    d3 = -g_ih
    d4 = -g_is

    A_c = np.zeros((5,5))
    A_c[0,:] = [d0,   g_im, g_ie, g_ih, g_is]
    A_c[1,:] = [g_im, d1,   0.0,  0.0,  0.0 ]
    A_c[2,:] = [g_ie, 0.0,  d2,   0.0,  0.0 ]
    A_c[3,:] = [g_ih, 0.0,  0.0,  d3,   0.0 ]
    A_c[4,:] = [g_is, 0.0,  0.0,  0.0,  d4  ]

    # Scale rows by 1/C
    A_c = (A_c.T * invC).T

    # --- Continuous B matrices ---
    B_u  = np.zeros(5); B_u[3]  = eta_h * invC[3]
    B_To = np.zeros(5); B_To[2] = g_ea  * invC[2]
    B_Us = np.zeros(5); B_Us[0] = Aw * invC[0]; B_Us[2] = Ae * invC[2]

    # Stack into a single B_c with 3 inputs: [u, T_out, U_s]
    B_c = np.column_stack((B_u, B_To, B_Us))

    # Dummy C,D for cont2discrete (we only care about A_d, B_d)
    C_dummy = np.eye(5)
    D_dummy = np.zeros((5, 3))

    A_d, B_d, _, _, _ = cont2discrete((A_c, B_c, C_dummy, D_dummy),
                                      dt,
                                      method="zoh")
    Phi = A_d
    Gu  = B_d[:, 0]
    GTo = B_d[:, 1]
    GUs = B_d[:, 2]

    return Phi, Gu, GTo, GUs

# -----------------------------------------------
# 3) Data Setup
# -----------------------------------------------
Y_meas  = np.asarray(Y_meas, float).ravel()
u_arr   = np.asarray(u, float).ravel()
T_out_K = np.asarray(T_out_K, float).ravel()
U_s_arr = np.asarray(U_s, float).ravel()
N       = int(len(Y_meas))

C_meas = np.zeros((1,5), float); C_meas[0,0] = 1.0
R      = np.array([[sigma_y_pf**2]], float)

# Process Noise
q_states = np.array([0.03]*5, float)
Qx_base  = np.diag(q_states**2)

sigma_log_theta_rw = 0.002
Q_log_theta = np.diag(np.full(n_free, sigma_log_theta_rw**2))

# -----------------------------------------------
# 4) UKF Initialization (Augmented State)
# -----------------------------------------------
x0 = np.array([Y_meas[0]]*5, float)

# Init params
theta0_full = theta_lo.copy()
theta0_full[free_idx] = 0.5*(theta_lo[free_idx] + theta_hi[free_idx])
phi0_free = np.log(theta0_full[free_idx])

# Augmented State z
z0 = np.concatenate([x0, phi0_free], axis=0)
nz = z0.size

# Covariance
P0 = np.zeros((nz, nz), float)
P0[:5,:5] = np.diag(np.full(5, 0.2**2))
P0[5:,5:] = np.diag(np.full(n_free, 0.3**2))  # log variance

# Sigma Points
points = MerweScaledSigmaPoints(nz, alpha=0.1, beta=2.0, kappa=0.0)

# Global tracker for time index inside fx
_current_k_for_fx = 0

def fx_augmented(z, dt):
    k = _current_k_for_fx
    x = z[:5]
    phi_free = z[5:]  # Log-params

    # Convert to linear params
    theta_lin_free = np.exp(phi_free)
    theta_full = theta0_full.copy()
    theta_full[free_idx] = theta_lin_free

    # ZOH physics
    Phi, Gu, GTo, GUs = discrete_system_zoh(theta_full, dt)

    # Inputs
    uk  = u_arr[k]
    Tok = T_out_K[k]
    Usk = U_s_arr[k]

    # Predict state
    x_next = Phi @ x + uk*Gu + Tok*GTo + Usk*GUs

    # Params RW handled by Q
    phi_next = phi_free

    return np.concatenate([x_next, phi_next])

def hx_augmented(z):
    return np.array([z[0]])

# Initialize Filter
ukf = UnscentedKalmanFilter(dim_x=nz, dim_z=1, dt=dt_seconds,
                            fx=fx_augmented, hx=hx_augmented, points=points)
ukf.x = z0.copy()
ukf.P = P0.copy()

# Set Noise
Q_aug = np.zeros((nz, nz), float)
Q_aug[:5,:5] = Qx_base
Q_aug[5:,5:] = Q_log_theta
ukf.Q = Q_aug
ukf.R = R

# -----------------------------------------------
# 5) Storage (Renamed for Global Assessment)
# -----------------------------------------------
Ti_mean_ukf = np.zeros(N); Ti_var_ukf = np.zeros(N)
Yhat        = np.zeros(N); S_arr      = np.zeros(N)
Theta_traj_ukf = np.zeros((N, len(theta_names)))  # linear θ storage

# t=0
Ti_mean_ukf[0]      = ukf.x[0]
Ti_var_ukf[0]       = ukf.P[0,0]
Yhat[0]             = ukf.x[0]
S_arr[0]            = ukf.P[0,0] + R[0,0]
Theta_traj_ukf[0]   = theta0_full

# -----------------------------------------------
# 6) UKF Loop
# -----------------------------------------------
print("Running Log-Space UKF (ZOH)...")

for k in range(1, N):
    yk = float(Y_meas[k])

    # Predict
    _current_k_for_fx = k-1
    ukf.predict()

    # Pre-update storage (one-step predictive stats)
    y_pred = ukf.x[0]
    S      = ukf.P[0,0] + R[0,0]
    Yhat[k]  = y_pred
    S_arr[k] = S

    # Update
    ukf.update(np.array([yk]))

    # Post-update storage
    Ti_mean_ukf[k] = ukf.x[0]
    Ti_var_ukf[k]  = ukf.P[0,0]

    # Store linear params
    theta_full = theta0_full.copy()
    theta_full[free_idx] = np.exp(ukf.x[5:])
    Theta_traj_ukf[k] = theta_full

# Explicitly calculate bands for later (convert to °C)
Ti_lo_ukf = (Ti_mean_ukf - 1.96*np.sqrt(Ti_var_ukf)) - 273.15
Ti_hi_ukf = (Ti_mean_ukf + 1.96*np.sqrt(Ti_var_ukf)) - 273.15

print("Log-Space UKF (ZOH) Complete.")

# -----------------------------------------------
# 7) Diagnostics
# -----------------------------------------------
def coverage(y, lo, hi):
    y, lo, hi = map(np.asarray, (y, lo, hi))
    ok = np.isfinite(y) & np.isfinite(lo) & np.isfinite(hi) & (lo <= hi)
    if not np.any(ok):
        return np.nan, 0, len(y)
    y, lo, hi = y[ok], lo[ok], hi[ok]
    return float(np.mean((y >= lo) & (y <= hi))), int(ok.size), int(len(y) - ok.size)

def mean_width(lo, hi):
    return float(np.nanmean(np.asarray(hi) - np.asarray(lo)))

# One-step Bands
S_sd = np.sqrt(np.maximum(S_arr, 0.0))
Y_lo_1 = Yhat - 1.96*S_sd
Y_hi_1 = Yhat + 1.96*S_sd

cov_pred, n2, d2 = coverage(Y_meas, Y_lo_1, Y_hi_1)

print("=========== LOG-SPACE UKF DIAGNOSTICS ===========\n")
print(f"[One-step Prediction Y] Coverage: {100*cov_pred:.1f}% "
      f"| Width: {mean_width(Y_lo_1, Y_hi_1):.3f} K")

# ============================================
# DIAGNOSTICS: RMSE, TF Errors, Winkler, Calibration
# ============================================
# ------------------------
# Helper: Winkler score for 95% intervals
# ------------------------
def winkler_score(y, lo, hi, alpha=0.05):
    """
    Compute mean Winkler score for (1-alpha) central prediction intervals.
    y, lo, hi: 1D arrays (same length, same units).
    """
    y  = np.asarray(y,  float)
    lo = np.asarray(lo, float)
    hi = np.asarray(hi, float)

    ok = np.isfinite(y) & np.isfinite(lo) & np.isfinite(hi) & (lo <= hi)
    if not np.any(ok):
        return np.nan

    y, lo, hi = y[ok], lo[ok], hi[ok]
    width = hi - lo

    score  = np.empty_like(width)
    inside = (y >= lo) & (y <= hi)
    below  = (y < lo)
    above  = (y > hi)

    # Inside interval
    score[inside] = width[inside]
    # Below
    score[below]  = width[below] + (2.0/alpha)*(lo[below] - y[below])
    # Above
    score[above]  = width[above] + (2.0/alpha)*(y[above] - hi[above])

    return float(np.mean(score))


# ------------------------
# Helper: coverage of intervals
# ------------------------
def coverage(y, lo, hi):
    """
    Empirical coverage of intervals [lo, hi] for targets y.
    Returns (coverage_fraction, n_used, n_dropped).
    """
    y, lo, hi = map(lambda a: np.asarray(a, float).ravel(), (y, lo, hi))
    ok = np.isfinite(y) & np.isfinite(lo) & np.isfinite(hi) & (lo <= hi)

    if not np.any(ok):
        return np.nan, 0, len(y)

    y_ok  = y[ok]
    lo_ok = lo[ok]
    hi_ok = hi[ok]

    cov = float(np.mean((y_ok >= lo_ok) & (y_ok <= hi_ok)))
    return cov, int(ok.size), int(len(y) - ok.size)


# ------------------------
# Helper: TF error metrics (H2-like, H1-like, H∞-like)
# ------------------------
def tf_error_metrics(theta_est, theta_true, channel, w_grid):
    """
    Compute frequency-domain errors between TF(theta_est) and TF(theta_true)
    for a given input channel over the given frequency grid w_grid.

    Important:
      - Assumes build_siso_ss_from_theta(theta, channel) returns a *discrete-time*
        ZOH-discretized SISO system (Ti output, chosen input) with dt = dt_seconds.
      - w_grid is the frequency grid passed to control.freqresp.

    Returns a dict with absolute and relative H2-, H1-, and H∞-like errors.
    """
    sys_true = build_siso_ss_from_theta(theta_true, channel)
    sys_est  = build_siso_ss_from_theta(theta_est,  channel)

    mag_true, phase_true, _ = control.freqresp(sys_true, w_grid)
    mag_est,  phase_est,  _ = control.freqresp(sys_est,  w_grid)

    G_true = mag_true.squeeze() * np.exp(1j*phase_true.squeeze())
    G_est  = mag_est.squeeze()  * np.exp(1j*phase_est.squeeze())

    diff     = G_est - G_true
    abs_diff = np.abs(diff)
    abs_true = np.abs(G_true)

    # H2-like (RMS over freq)
    h2_err  = math.sqrt(np.mean(abs_diff**2))
    h2_norm = math.sqrt(np.mean(abs_true**2))

    # H1-like (mean abs error / mean abs magnitude)
    h1_err  = float(np.mean(abs_diff))
    h1_norm = float(np.mean(abs_true))

    # H∞-like (max abs error / max abs magnitude)
    hinf_err  = float(np.max(abs_diff))
    hinf_norm = float(np.max(abs_true))

    return {
        "H2_err":   h2_err,
        "H2_rel":   h2_err / h2_norm if h2_norm > 0 else np.nan,
        "H1_err":   h1_err,
        "H1_rel":   h1_err / h1_norm if h1_norm > 0 else np.nan,
        "Hinf_err": hinf_err,
        "Hinf_rel": hinf_err / hinf_norm if hinf_norm > 0 else np.nan,
    }


# ====================================================
# 1) RMSE of RBPF vs EKF vs UKF on indoor temperature
# ====================================================
# Prefer true Ti if available, otherwise fall back to measured Y_meas
if 'Ti_true_C' in globals():
    y_true_C = np.asarray(Ti_true_C, float).ravel()
    target_label = "Ti_true"
else:
    # Measurement (Kelvin) → Celsius
    y_true_C = np.asarray(Y_meas, float).ravel() - 273.15
    target_label = "Y_meas (no true Ti available)"

# RBPF: Ti_md is already in °C
Ti_rbpf_C = np.asarray(Ti_md, float).ravel()

# EKF / UKF: means are in Kelvin; convert to °C
Ti_ekf_C = np.asarray(Ti_mean_ekf, float).ravel() - 273.15
Ti_ukf_C = np.asarray(Ti_mean_ukf, float).ravel() - 273.15

def rmse(a, b):
    a = np.asarray(a, float).ravel()
    b = np.asarray(b, float).ravel()
    return float(np.sqrt(np.mean((a - b)**2)))

rmse_rbpf = rmse(Ti_rbpf_C, y_true_C)
rmse_ekf  = rmse(Ti_ekf_C,  y_true_C)
rmse_ukf  = rmse(Ti_ukf_C,  y_true_C)

print("=========== RMSE on indoor temperature (°C) ===========")
print(f"Target series: {target_label}")
print(f"RBPF RMSE: {rmse_rbpf:.4f} °C")
print(f"EKF  RMSE: {rmse_ekf:.4f} °C")
print(f"UKF  RMSE: {rmse_ukf:.4f} °C")


# ====================================================
# 2) TF errors (H2, H1, H∞) for last parameter state
# ====================================================
theta_last = {
    "LS":   theta_ls,                 # offline least-squares
    "RBPF": Theta_rbpf[-1, :],        # median RBPF at final time
    "EKF":  Theta_traj_ekf[-1, :],    # EKF final parameters
    "UKF":  Theta_traj_ukf[-1, :],    # UKF final parameters
}

print("\n=========== Transfer Function Errors (final θ) ===========")
for ch in ['solar', 'heater', 'outside']:
    print(f"\nChannel: {ch}")
    for method_name, theta_est in theta_last.items():
        metrics = tf_error_metrics(theta_est, theta_true, ch, w_grid)
        print(
            f"  {method_name:4s} | "
            f"H2_abs={metrics['H2_err']:.3e}, H2_rel={metrics['H2_rel']:.3e} | "
            f"H1_abs={metrics['H1_err']:.3e}, H1_rel={metrics['H1_rel']:.3e} | "
            f"Hinf_abs={metrics['Hinf_err']:.3e}, Hinf_rel={metrics['Hinf_rel']:.3e}"
        )


# ====================================================
# 3) Winkler scores & 95% calibration (quiet vs latent)
# ====================================================
# Intervals are in °C:
#   RBPF: Ti_lo, Ti_hi
#   EKF:  Ti_lo_ekf, Ti_hi_ekf
#   UKF:  Ti_lo_ukf, Ti_hi_ukf
intervals = {
    "RBPF": (np.asarray(Ti_lo,     float).ravel(),
             np.asarray(Ti_hi,     float).ravel()),
    "EKF":  (np.asarray(Ti_lo_ekf, float).ravel(),
             np.asarray(Ti_hi_ekf, float).ravel()),
    "UKF":  (np.asarray(Ti_lo_ukf, float).ravel(),
             np.asarray(Ti_hi_ukf, float).ravel()),
}

# Regime masks: quiet vs latent (if F_true is available)
has_F_true = 'F_true' in globals()
if has_F_true:
    F_arr = np.asarray(F_true, float).ravel()
    quiet_mask  = np.abs(F_arr) < 1e-8
    latent_mask = ~quiet_mask
else:
    quiet_mask  = None
    latent_mask = None

print("\n=========== Winkler Scores & 95% Calibration (Ti, 95% bands) ===========")
print("All scores in °C units; 95% intervals; Winkler lower is better.")

for method_name, (lo_C, hi_C) in intervals.items():
    ws_all   = winkler_score(y_true_C, lo_C, hi_C, alpha=0.05)
    cov_all, _, _ = coverage(y_true_C, lo_C, hi_C)

    print(f"\nMethod: {method_name}")
    print(f"  Overall  : Winkler={ws_all:.4f}, 95%-cov={100*cov_all:.2f}%")

    if has_F_true and np.any(quiet_mask):
        ws_quiet   = winkler_score(y_true_C[quiet_mask],
                                   lo_C[quiet_mask],
                                   hi_C[quiet_mask],
                                   alpha=0.05)
        cov_quiet, _, _ = coverage(y_true_C[quiet_mask],
                                   lo_C[quiet_mask],
                                   hi_C[quiet_mask])
        print(f"  Quiet    : Winkler={ws_quiet:.4f}, 95%-cov={100*cov_quiet:.2f}%")

    if has_F_true and np.any(latent_mask):
        ws_latent   = winkler_score(y_true_C[latent_mask],
                                    lo_C[latent_mask],
                                    hi_C[latent_mask],
                                    alpha=0.05)
        cov_latent, _, _ = coverage(y_true_C[latent_mask],
                                    lo_C[latent_mask],
                                    hi_C[latent_mask])
        print(f"  Latent F : Winkler={ws_latent:.4f}, 95%-cov={100*cov_latent:.2f}%")

print("\nDiagnostics block complete.")

# ============================================
# OPEN-LOOP FORECAST ERRORS ON QUIET INTERVALS
# ============================================

import numpy as np

# Minimum quiet duration: 12 hours
min_quiet_hours = 12.0
min_quiet_steps = int(np.ceil((min_quiet_hours * 3600.0) / float(dt_seconds)))

# Ensure we have a quiet_mask based on F_true
if quiet_mask is None:
    print("\n[Open-loop diagnostics] quiet_mask is None (no F_true available) -> skipping.")
else:
    quiet_mask_arr = np.asarray(quiet_mask, dtype=bool).ravel()
    N_total = quiet_mask_arr.size

    # ----------------------------------------
    # 1) Find contiguous quiet segments
    # ----------------------------------------
    quiet_segments = []
    in_seg = False
    start_idx = 0

    for k in range(N_total):
        if quiet_mask_arr[k]:
            if not in_seg:
                in_seg = True
                start_idx = k
        else:
            if in_seg:
                end_idx = k - 1
                seg_len = end_idx - start_idx + 1
                if seg_len >= min_quiet_steps:
                    quiet_segments.append((start_idx, end_idx))
                in_seg = False

    # Handle case where we end in a quiet segment
    if in_seg:
        end_idx = N_total - 1
        seg_len = end_idx - start_idx + 1
        if seg_len >= min_quiet_steps:
            quiet_segments.append((start_idx, end_idx))

    print("\n=========== Open-loop forecast errors on quiet intervals (F_true ≈ 0) ===========")
    print(f"dt = {dt_seconds} s, min_quiet_steps = {min_quiet_steps} (~{min_quiet_hours:.1f} h)")

    if not quiet_segments:
        print("No quiet segments ≥ 12 h found; nothing to evaluate.")
    else:
        # ----------------------------------------
        # 2) Ground-truth indoor temperature (Kelvin)
        # ----------------------------------------
        if 'Y_Ti' in globals():
            Ti_true_K = np.asarray(Y_Ti, float).ravel()
            truth_label = "Y_Ti (true Ti from simulator)"
        elif 'Ti_true' in globals():
            Ti_true_K = np.asarray(Ti_true, float).ravel()
            truth_label = "Ti_true"
        elif 'Ti_true_C' in globals():
            Ti_true_K = np.asarray(Ti_true_C, float).ravel() + 273.15
            truth_label = "Ti_true_C + 273.15"
        else:
            Ti_true_K = np.asarray(Y_meas, float).ravel()
            truth_label = "Y_meas (noisy measurement)"
        print(f"Using ground-truth series: {truth_label}")

        # Time axis (if available)
        has_ts = 'ts' in globals()

        # ----------------------------------------
        # 3) Final parameter states per method
        # ----------------------------------------
        theta_final = {
            "LS":   np.asarray(theta_ls, float).ravel(),
            "RBPF": np.asarray(Theta_rbpf[-1, :], float).ravel(),
            "EKF":  np.asarray(Theta_traj_ekf[-1, :], float).ravel(),
            "UKF":  np.asarray(Theta_traj_ukf[-1, :], float).ravel(),
        }

        # ----------------------------------------
        # 4) Data arrays and initial states
        # ----------------------------------------
        X_arr     = np.asarray(X, float)
        u_arr_loc = np.asarray(u_arr if 'u_arr' in globals() else u, float).ravel()
        T_out_loc = np.asarray(T_out_K, float).ravel()
        U_s_loc   = np.asarray(U_s_arr if 'U_s_arr' in globals() else U_s, float).ravel()

        # Measurement matrix for Ti
        C_y_arr = np.asarray(C_y if 'C_y' in globals() else C_meas, float).reshape(1, -1)

        # Container for per-segment RMSEs
        openloop_rmse = {name: [] for name in theta_final.keys()}

        # ----------------------------------------
        # 5) Loop over quiet segments and methods
        # ----------------------------------------
        for seg_idx, (k0, k1) in enumerate(quiet_segments, start=1):
            seg_len   = k1 - k0 + 1
            seg_hours = seg_len * float(dt_seconds) / 3600.0

            if has_ts:
                t0 = ts[k0]
                t1 = ts[k1]
                print(f"\nSegment {seg_idx}: idx [{k0}:{k1}] "
                      f"(len={seg_len} steps, {seg_hours:.2f} h, {t0} → {t1})")
            else:
                print(f"\nSegment {seg_idx}: idx [{k0}:{k1}] "
                      f"(len={seg_len} steps, {seg_hours:.2f} h)")

            # True initial state at start of segment
            x0_true     = X_arr[k0, :].astype(float)
            Ti_true_seg = Ti_true_K[k0:k1+1]

            for method_name, theta_est in theta_final.items():
                # Build discrete-time model from final parameters (ZOH)
                Phi, Gu, GTo, GUs = discrete_system_zoh(theta_est, dt_seconds)

                x = x0_true.copy()
                y_hat_seg = np.zeros(seg_len, float)
                stable = True

                for i in range(seg_len):
                    # Output at current state
                    y_hat_seg[i] = float(C_y_arr @ x)

                    if i < seg_len - 1:
                        idx_global = k0 + i
                        uk  = u_arr_loc[idx_global]
                        Tok = T_out_loc[idx_global]
                        Usk = U_s_loc[idx_global]

                        # ZOH-discretized open-loop update (no latent force, no noise)
                        x = Phi @ x + Gu * uk + GTo * Tok + GUs * Usk

                        # Basic stability / sanity check
                        if (not np.all(np.isfinite(x))) or np.any(np.abs(x) > 1e6):
                            stable = False
                            break

                if not stable:
                    rmse_val = np.nan
                    print(f"  {method_name:4s}: simulation unstable (RMSE = NaN)")
                else:
                    # RMSE in Kelvin (same as °C difference)
                    rmse_val = float(np.sqrt(np.mean((y_hat_seg - Ti_true_seg)**2)))
                    print(f"  {method_name:4s}: RMSE_open_loop = {rmse_val:.4f} K "
                          f"(= {rmse_val:.4f} °C)")
                openloop_rmse[method_name].append(rmse_val)

        # ----------------------------------------
        # 6) Summary across segments
        # ----------------------------------------
        print("\nSummary over all quiet segments (RMSE_open_loop in °C/K):")
        for method_name, vals in openloop_rmse.items():
            vals_arr = np.asarray([v for v in vals if np.isfinite(v)], float)
            if vals_arr.size == 0:
                print(f"  {method_name:4s}: no finite RMSE values.")
            else:
                mean_rmse = float(vals_arr.mean())
                med_rmse  = float(np.median(vals_arr))
                min_rmse  = float(vals_arr.min())
                max_rmse  = float(vals_arr.max())
                print(f"  {method_name:4s}: "
                      f"mean={mean_rmse:.4f}, median={med_rmse:.4f}, "
                      f"min={min_rmse:.4f}, max={max_rmse:.4f}")

# ==============================================================================
# SAVE RESULTS TO GOOGLE DRIVE (RAW DATA & SINGLE-STEP FILTER RESULTS)
# ==============================================================================

# 1. Mount Google Drive
drive.mount('/content/drive')

# 2. Setup Directory: Drive -> RBPF_Simulations -> Date_Time
#    This creates a unique folder for every run so you don't overwrite old experiments.
timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M")
print(timestamp)
base_dir = "/content/drive/My Drive/RBPF_Simulations"
save_path = os.path.join(base_dir, timestamp)
os.makedirs(save_path, exist_ok=True)

print(f" Saving simulation data to: {save_path}")

# 3. Consolidate and Save
# We use .npz (compressed) for efficiency.
output_file = os.path.join(save_path, "simulation_results_ZOH.npz")

np.savez_compressed(
    output_file,

    # ---------------------------------------------------------
    # A. METADATA & SETUP
    # ---------------------------------------------------------
    time_seconds    = ts_grid,               # Grid in seconds (for math)
    time_timestamps = ts,                    # Datetime objects (for plotting)
    theta_names     = np.array(theta_names), # Names of params ['Ci', 'Cm'...]
    dt_step         = dt_seconds,            # Time step size (e.g., 120s)

    # ---------------------------------------------------------
    # B. GROUND TRUTH & INPUTS (The Reality)
    # ---------------------------------------------------------
    truth_Ti        = Ti_true_C,        # True Indoor Temp (Celsius)
    truth_Y_meas    = Y_meas,           # Noisy Measurements (Kelvin)
    truth_F_latent  = F_true,           # True Latent Heat Signal (Watts)
    truth_theta     = theta_true,       # True Parameter Vector

    # Forcing Inputs
    input_heater    = u,                # Heater (Watts)
    input_Tout      = T_out_K,          # Outside Temp (Kelvin)
    input_Solar     = U_s,              # Solar (W/m2)

    # ---------------------------------------------------------
    # C. RBPF RESULTS (The Main Model)
    # ---------------------------------------------------------
    # Parameters (N x 10) - Median and 95% Bounds
    rbpf_theta_med  = Th_md,
    rbpf_theta_low  = Th_lo,
    rbpf_theta_high = Th_hi,

    # State Estimates (Indoor Temp)
    rbpf_Ti_med     = Ti_md,
    rbpf_Ti_low     = Ti_lo,
    rbpf_Ti_high    = Ti_hi,

    # Internal Logic
    rbpf_alpha      = Alpha_md,         # Adaptive noise scaler trajectory
    rbpf_regime     = regime_flag,      # 0=Quiet, 1=Burst

    # ---------------------------------------------------------
    # D. BASELINE RESULTS (EKF & UKF, single-step)
    # ---------------------------------------------------------
    # EKF
    ekf_theta_mean  = Theta_traj_ekf,   # Parameter means over time
    ekf_Ti_mean     = Ti_mean_ekf,      # State mean over time (K)
    ekf_Ti_var      = Ti_var_ekf,       # State variance (for CI)

    # UKF
    ukf_theta_mean  = Theta_traj_ukf,   # Parameter means over time
    ukf_Ti_mean     = Ti_mean_ukf,      # State mean over time (K)
    ukf_Ti_var      = Ti_var_ukf,       # State variance (for CI)

    # ---------------------------------------------------------
    # E. STATIC FIT
    # ---------------------------------------------------------
    ls_theta_static = theta_ls,         # Offline Least Squares fit vector
)

print(f" File: {output_file}")