# -*- coding: utf-8 -*-
"""RBPF_HIST_Q_V2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mdljbVAWnumEdY4y5WjVK0ewDfnBeIl4
"""

!pip install filterpy

!pip install control



import numpy as np
import pandas as pd
from pathlib import Path
from scipy.linalg import expm
import plotly.graph_objects as go
from scipy.optimize import minimize
import control
def generate_square_heating(N,
                            dt_seconds,
                            power=6000.0,
                            p_start=0.002,                # per-STEP start prob when OFF
                            min_duration_s=30*60,         # 30 minutes
                            max_duration_s=4*60*60,       # 4 hours
                            seed=None):
    """
    Generate a square heating signal with random ON episodes.
    - When OFF, each step has probability p_start to begin an ON episode.
    - Each ON episode has a constant 'power' and a duration uniform in [min_duration_s, max_duration_s].
    - Episodes do not overlap; new ones can start only when the previous one ends.

    Returns
    -------
    F_true : (N,) float array
        Heating power in Watts at each step.
    event_log : list of dict
        Each dict has: {'start_idx', 'end_idx', 'duration_s'} (end_idx inclusive).
    """
    rng = np.random.default_rng(seed)

    # durations in steps
    min_steps = int(np.ceil(min_duration_s / dt_seconds))
    max_steps = int(np.ceil(max_duration_s / dt_seconds))
    print("MAX steps",max_steps)
    print("MIN steps",min_steps)
    if min_steps < 1:
      min_steps = 1
    if max_steps < min_steps:
      max_steps = min_steps

    F_true = np.zeros(N, dtype=float)
    event_log = []

    on_remaining = 0
    start_idx = None

    for k in range(N):
        if on_remaining > 0:
            F_true[k] = power
            on_remaining -= 1
            if on_remaining == 0:
                # episode ends at k
                event_log.append({
                    "start_idx": start_idx,
                    "end_idx": k,
                    "duration_s": (k - start_idx + 1) * dt_seconds
                })
                start_idx = None
        else:
            # currently OFF; possibly start a new episode
            if rng.random() < p_start:
                dur_steps = rng.integers(min_steps, max_steps + 1)
                on_remaining = dur_steps
                start_idx = k
                F_true[k] = power
                on_remaining -= 1  # consumed this step
            # else remains 0 (OFF)
    # If an ON episode runs past the last index, we close it at N-1
    if start_idx is not None and (len(event_log) == 0 or event_log[-1]["end_idx"] != N-1):
        event_log.append({
            "start_idx": start_idx,
            "end_idx": N-1,
            "duration_s": (N - start_idx) * dt_seconds
        })

    return F_true, event_log

def generate_pulse_heating(N,
                           dt_seconds,
                           mode="alpha",                  # "alpha" (rise/decay) or "gauss"
                           p_start=0.0015,                # per-step birth probability
                           amp_range=(1500.0, 8000.0),    # Watts (uniform)
                           tau_r_range_s=(5*60, 40*60),   # alpha: rise time (seconds)
                           tau_d_range_s=(45*60, 4*60*60),# alpha: decay time (seconds)
                           sigma_range_s=(15*60, 90*60),  # gauss: std (seconds)
                           kill_rel=1e-3,                 # drop pulse when value < kill_rel * A
                           max_active=6,                  # cap concurrent pulses
                           seed=None):
    """
    Generate a bursty positive latent heat signal as a sum of smooth pulses.

    Pulses arrive via a Bernoulli hazard p_start per step. Each new pulse samples its
    parameters from simple ranges, remains active, and contributes a smooth, positive shape:

      - mode="alpha":  f(t) = A * max( exp(-age/tau_d) - exp(-age/tau_r), 0.0 )
      - mode="gauss":  f(t) = A * exp( -0.5 * (age/sigma)**2 )

    A pulse is dropped when f(t) < kill_rel * A.

    Returns
    -------
    F_true : (N,) float
        Total latent heat per step (W).
    event_log : list of dict
        For each pulse:
          {
            'mode', 'start_idx', 'end_idx',
            'A', 'tau_r_s', 'tau_d_s', 'sigma_s',
            'peak_W', 'peak_idx'
          }
        Unused keys are None for the chosen mode.
    """
    import numpy as np

    rng = np.random.default_rng(seed)
    F_true = np.zeros(N, dtype=float)
    event_log = []

    active = []  # list of dicts; each has fixed params and evolving 'age_s'

    def _sample_time_s(lo, hi):
        # sample in log-space for robustness if ranges are wide
        lo = max(lo, 1.0)
        hi = max(hi, lo + 1.0)
        return float(10 ** rng.uniform(np.log10(lo), np.log10(hi)))

    for k in range(N):
        # births
        if len(active) < max_active and rng.random() < p_start:
            A = rng.uniform(*amp_range)
            if mode == "alpha":
                tau_r_s = _sample_time_s(*tau_r_range_s)
                tau_d_s = _sample_time_s(*tau_d_range_s)
                if tau_d_s <= tau_r_s:
                    tau_d_s = tau_r_s * rng.uniform(1.5, 3.0)  # enforce decay > rise
                pulse = {
                    "mode": "alpha",
                    "A": A,
                    "tau_r_s": tau_r_s,
                    "tau_d_s": tau_d_s,
                    "sigma_s": None,
                    "age_s": 0.0,
                    "start_idx": k,
                    "peak_W": 0.0,
                    "peak_idx": k
                }
            elif mode == "gauss":
                sigma_s = _sample_time_s(*sigma_range_s)
                pulse = {
                    "mode": "gauss",
                    "A": A,
                    "tau_r_s": None,
                    "tau_d_s": None,
                    "sigma_s": sigma_s,
                    "age_s": 0.0,
                    "start_idx": k,
                    "peak_W": 0.0,
                    "peak_idx": k
                }
            else:
                raise ValueError("mode must be 'alpha' or 'gauss'")
            active.append(pulse)

        # accumulate contributions from active pulses at time k
        val_k = 0.0
        keep = []
        for p in active:
            age = p["age_s"]
            A = p["A"]
            if p["mode"] == "alpha":
                tr = p["tau_r_s"]
                td = p["tau_d_s"]
                f = A * max(np.exp(-age/td) - np.exp(-age/tr), 0.0)
            else:  # "gauss"
                sg = p["sigma_s"]
                f = A * np.exp(-0.5 * (age/sg)**2)

            val_k += f

            # track peak and decide if to keep
            if f > p["peak_W"]:
                p["peak_W"] = f
                p["peak_idx"] = k

            if (age == 0.0) or (f >= kill_rel * A):
                p["age_s"] = age + dt_seconds
                keep.append(p)
            else:
                p["end_idx"] = k
                event_log.append(p)
        active = keep
        F_true[k] = val_k

    # close any remaining pulses at the end
    for p in active:
        p["end_idx"] = N - 1
        event_log.append(p)

    # normalize event_log fields
    for p in event_log:
        p.setdefault("end_idx", N - 1)
        p.setdefault("peak_W", 0.0)
        p.setdefault("peak_idx", p["start_idx"])

    return F_true, event_log

# --------------------------- USER INPUTS ----------------------------
TEMP_FILE  = Path("dwd_20242025.txt")
SOLAR_FILE = Path("radiation_20242025.txt")

START = "2024-03-17 00:00"   # inclusive
END   = "2024-07-17 00:00"   # exclusive
dt_seconds = 120             # 2min

# ------------------- LOADERS (robust to DWD format) ----------------
def load_dwd_temperature(path: Path) -> pd.DataFrame:
    df = pd.read_csv(path, sep=";", decimal=",", dtype=str,
                     na_values=["-999", "-9999", "-999.0", "", "NA", "NaN"])
    if "MESS_DATUM" not in df.columns:
        raise ValueError("Temperature file missing 'MESS_DATUM'.")
    if "TT_10" not in df.columns:
        cand = [c for c in df.columns if c.upper().startswith("TT")]
        if not cand:
            raise ValueError("Temperature file missing 'TT_10' (°C).")
        df = df.rename(columns={cand[0]: "TT_10"})
    df["Timestamp"] = pd.to_datetime(df["MESS_DATUM"], format="%Y%m%d%H%M", errors="coerce")
    df["TT_10"] = pd.to_numeric(df["TT_10"], errors="coerce")
    df = df.dropna(subset=["Timestamp", "TT_10"]).reset_index(drop=True)
    df = df[["Timestamp", "TT_10"]].sort_values("Timestamp")
    return df

def load_dwd_radiation(path: Path) -> pd.DataFrame:
    df = pd.read_csv(path, sep=";", decimal=",", dtype=str,
                     na_values=["-999", "-9999", "-999.0", "", "NA", "NaN"])
    if "MESS_DATUM" not in df.columns:
        raise ValueError("Solar file missing 'MESS_DATUM'.")
    if "GS_10" not in df.columns:
        cand = [c for c in df.columns if c.upper().startswith("GS")]
        if not cand:
            raise ValueError("Solar file missing 'GS_10'.")
        df = df.rename(columns={cand[0]: "GS_10"})
    df["Timestamp"] = pd.to_datetime(df["MESS_DATUM"], format="%Y%m%d%H%M", errors="coerce")
    df["GS_10"] = pd.to_numeric(df["GS_10"], errors="coerce")
    df = df.dropna(subset=["Timestamp", "GS_10"]).reset_index(drop=True)
    # J/cm² over 10 min -> W/m² average over the interval
    df["U_s"] = df["GS_10"] * 10000.0 / 600.0
    df = df[["Timestamp", "U_s"]].sort_values("Timestamp")
    return df

t_df = load_dwd_temperature(TEMP_FILE)
s_df = load_dwd_radiation(SOLAR_FILE)

# ----------------------- TIME FILTER & ALIGN -----------------------
mask_t = (t_df["Timestamp"] >= pd.to_datetime(START)) & (t_df["Timestamp"] < pd.to_datetime(END))
mask_s = (s_df["Timestamp"] >= pd.to_datetime(START)) & (s_df["Timestamp"] < pd.to_datetime(END))
t_df = t_df.loc[mask_t].copy()
s_df = s_df.loc[mask_s].copy()

if t_df.empty or s_df.empty:
    raise ValueError("One of the weather dataframes is empty in the selected range.")

# align temp and solar to the same irregular stamps first (nearest within tolerance)
merged = pd.merge_asof(
    t_df.sort_values("Timestamp"),
    s_df.sort_values("Timestamp"),
    on="Timestamp",
    direction="nearest",
    tolerance=pd.to_timedelta(dt_seconds/2, unit="s")
).dropna(subset=["TT_10", "U_s"]).set_index("Timestamp").sort_index()

# ---------- BUILD UNIFORM GRID & INTERPOLATE WITH NUMPY ----------
# uniform grid [START, END) with step dt_seconds
start_np = np.datetime64(pd.to_datetime(START), 's')
end_np   = np.datetime64(pd.to_datetime(END),   's')
step     = np.timedelta64(int(dt_seconds), 's')
ts_grid  = np.arange(start_np, end_np, step, dtype='datetime64[s]')     # shape (N,)
t_grid_s = ts_grid.astype('int64')  # seconds since epoch

# irregular input series as seconds since epoch
t_in   = merged.index.values.astype('datetime64[s]')
x_in   = t_in.astype('int64')
TT_in  = merged["TT_10"].to_numpy(float)
Us_in  = merged["U_s"].to_numpy(float)

# clean/sort/deduplicate
good   = np.isfinite(TT_in) & np.isfinite(Us_in)
x_in, TT_in, Us_in = x_in[good], TT_in[good], Us_in[good]
order  = np.argsort(x_in, kind="mergesort")
x_in, TT_in, Us_in = x_in[order], TT_in[order], Us_in[order]
uniq_x, uniq_idx   = np.unique(x_in, return_index=True)
x_in, TT_in, Us_in = uniq_x, TT_in[uniq_idx], Us_in[uniq_idx]

# linear interpolation in time; edge-fill with nearest endpoint values
T_out_C = np.interp(t_grid_s, x_in, TT_in, left=TT_in[0], right=TT_in[-1])
U_s     = np.interp(t_grid_s, x_in, Us_in, left=Us_in[0], right=Us_in[-1])

# Known inputs on the grid
ts = pd.to_datetime(ts_grid).to_pydatetime()
T_out_K = T_out_C + 273.15
N       = ts_grid.size

# ------------------- HARD-CODED RC PARAMETERS ---------------------
Ci_kWhK = 2.745148488
Cm_kWhK = 19.76698557
Ce_kWhK = 2.412573281
Ch_kWhK = 0.101200218
Cs_kWhK = 0.106406602
Ci = Ci_kWhK * 3_600_000.0
Cm = Cm_kWhK * 3_600_000.0
Ce = Ce_kWhK * 3_600_000.0
Ch = Ch_kWhK * 3_600_000.0
Cs = Cs_kWhK * 3_600_000.0

def to_G(R):
    return 0.0 if not np.isfinite(R) else 1000.0 / R

Rie_K_per_kW = 0.532152894
Rea_K_per_kW = 7.115085934
Ria_K_per_kW = np.inf
Rim_K_per_kW = 0.552472387
Rih_K_per_kW = 0.269801371
Ris_K_per_kW = 2.349904019

g_ie = to_G(Rie_K_per_kW)
g_ea = to_G(Rea_K_per_kW)
g_ia = to_G(Ria_K_per_kW)  # 0 here
g_im = to_G(Rim_K_per_kW)
g_ih = to_G(Rih_K_per_kW)
g_is = to_G(Ris_K_per_kW)

Aw_m2 = 4.542558125
Ae_m2 = 0.0
Aw = float(Aw_m2)
Ae = float(Ae_m2)

eta_h = 1.0  # heater efficiency into Th

# ----------------- CONTINUOUS-TIME MODEL (°K) ---------------------
# States: x = [Ti, Tm, Te, Th, Ts]
# Inputs: [u (W), T_out (K), U_s (W/m^2), F (W)]
Cdiag = np.array([Ci, Cm, Ce, Ch, Cs], float)
Cinvt = np.diag(1.0 / Cdiag)

G = np.zeros((5,5), float)
# symmetric couplings
G[0,1] = G[1,0] = g_im
G[0,2] = G[2,0] = g_ie
G[0,3] = G[3,0] = g_ih
G[0,4] = G[4,0] = g_is
# diagonals
G[0,0] = -(g_im + g_ie + g_ih + g_is + g_ia)
G[1,1] = -(g_im)
G[2,2] = -(g_ie + g_ea)
G[3,3] = -(g_ih)
G[4,4] = -(g_is)

A_c = Cinvt @ G

# Inputs
B_u   = np.zeros((5,1), float); B_u[3,0] = eta_h / Ch               # heater -> Th
F_out = Cinvt @ np.array([[g_ia, 0.0, g_ea, 0.0, 0.0]]).T           # T_out drives Ti, Te
B_sol = Cinvt @ np.array([[Aw,   0.0,  Ae,   0.0, 0.0]]).T          # solar drives Ti, Te
B_F   = np.zeros((5,1), float); B_F[0,0] = 1.0 / Ci                 # latent heat into Ti

# Measurement matrix: Ti only
C_y = np.array([[1,0,0,0,0]], float)

# ----------------------- INPUTS: LATENT & HEATER -------------------
# You should have your generate_square_heating / generate_pulse_heating
# functions defined somewhere above this block.

F_true, F_events = generate_square_heating(
    N=N, dt_seconds=dt_seconds,
    power=7000.0,            # W
    p_start=0.0011,           # per-step start hazard when OFF 0.001
    min_duration_s=20*60,    # 20 min
    max_duration_s=8*60*60,  # 8 h
    seed=321
)

"""
F_true, F_events = generate_pulse_heating(
    N=N,
    dt_seconds=dt_seconds,
    mode="alpha",                 # or "gauss"
    p_start=0.0015,               # birth hazard per step
    amp_range=(8500.0, 9000.0),   # W
    tau_r_range_s=(20*60, 60*60),   # 20–60 min rise
    tau_d_range_s=(60*60, 6*60*60), # 60 min – 6 h decay
    kill_rel=1e-3,
    max_active=6,
    seed=123
)
"""

# Heater ON/OFF schedule u(t) at Th (also square episodes; separate seed)
u, u_events = generate_square_heating(
    N=N, dt_seconds=dt_seconds,
    power=800.0,            # W
    p_start=0.0035,
    min_duration_s=20*60,    # 20 min
    max_duration_s=1*60*60,  # 1 h
    seed=456
)

print(f"Latent F: mean={F_true.mean():.1f} W, max={F_true.max():.0f} W")
print(f"Heater u: mean={u.mean():.1f} W, max={u.max():.0f} W")

# ---------------------------- SIMULATE (EULER) ---------------------
Ti0 = T_out_K[0]
x = np.array([Ti0, Ti0, Ti0, Ti0, Ti0], float)
X = np.zeros((N,5), float)
X[0] = x

# small process noise for realism (K per step)
q_std = np.array([0.03, 0.03, 0.03, 0.03, 0.03])
rng = np.random.default_rng(123)

for k in range(N-1):
    U_vec = u[k]           # heater W
    To_k  = T_out_K[k]     # outside K
    Us_k  = U_s[k]         # W/m^2
    F_k   = F_true[k]      # W latent at Ti

    # Continuous-time RHS: dx/dt = A_c x + B_u u + F_out T_out + B_sol U_s + B_F F
    dx = (
        A_c @ x
        + B_u[:, 0]   * U_vec
        + F_out[:, 0] * To_k
        + B_sol[:, 0] * Us_k
        + B_F[:, 0]   * F_k
    )

    # Forward Euler step
    x = x + dt_seconds * dx

    # add small process noise (no clipping)
    x = x + rng.normal(0.0, q_std)

    X[k+1] = x

Y_Ti = (C_y @ X.T).ravel()  # Ti [K]

# ---------------------------- PLOTS -------------------------------
# 1) Weather, heater, and latent heat
fig1 = go.Figure()
fig1.add_trace(go.Scatter(x=ts, y=T_out_C, name="Outside T [°C]", mode="lines"))
fig1.add_trace(go.Scatter(x=ts, y=U_s,     name="Solar U_s [W/m²]", mode="lines", yaxis="y2", opacity=0.5))
fig1.add_trace(go.Scatter(x=ts, y=F_true,  name="Latent F [W]",    mode="lines", yaxis="y3", opacity=0.6))
fig1.add_trace(go.Scatter(x=ts, y=u,       name="Heater u [W]",    mode="lines", yaxis="y4", opacity=0.7))
fig1.update_layout(
    title="Inputs: Outside Temp, Solar, Latent Heat (Ti), and Heater (Th)",
    xaxis=dict(title="Time", type="date", rangeslider=dict(visible=True)),
    yaxis=dict(title="°C"),
    yaxis2=dict(title="W/m²", overlaying="y", side="right", showgrid=False),
    yaxis3=dict(title="W (Latent F)", overlaying="y", side="right", anchor="free", position=0.98, showgrid=False),
    yaxis4=dict(title="W (Heater u)", overlaying="y", side="right", anchor="free", position=0.92, showgrid=False),
    template="plotly_white",
    legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="left", x=0)
)
fig1.show()

# 2) State trajectories (°C)
Ti_C = X[:,0] - 273.15
Tm_C = X[:,1] - 273.15
Te_C = X[:,2] - 273.15
Th_C = X[:,3] - 273.15
Ts_C = X[:,4] - 273.15

fig2 = go.Figure()
fig2.add_trace(go.Scatter(x=ts, y=Ti_C, name="Ti", mode="lines"))
fig2.add_trace(go.Scatter(x=ts, y=Tm_C, name="Tm", mode="lines"))
fig2.add_trace(go.Scatter(x=ts, y=Te_C, name="Te", mode="lines"))
fig2.add_trace(go.Scatter(x=ts, y=Th_C, name="Th", mode="lines"))
fig2.add_trace(go.Scatter(x=ts, y=Ts_C, name="Ts", mode="lines"))
fig2.update_layout(
    title="5-State RC Simulation with Latent Heat at Ti and Heater at Th (Euler)",
    xaxis=dict(title="Time", type="date", rangeslider=dict(visible=True)),
    yaxis=dict(title="Temperature [°C]"),
    template="plotly_white",
    legend=dict(orientation="h", yanchor="bottom", y=1.02, x=0)
)
fig2.show()

# 3) Measured Ti (noisy) vs true Ti
sigma_y = 0.15
Y_meas = Y_Ti + rng.normal(0.0, sigma_y, size=N)
fig3 = go.Figure()
fig3.add_trace(go.Scatter(x=ts, y=Ti_C,          name="True Ti [°C]", mode="lines"))
fig3.add_trace(go.Scatter(x=ts, y=Y_meas-273.15, name="Measured Ti [°C]", mode="lines", opacity=0.6))
fig3.update_layout(
    title="Indoor Air Temperature (True vs Measured)",
    xaxis=dict(title="Time", type="date", rangeslider=dict(visible=True)),
    yaxis=dict(title="°C"),
    template="plotly_white",
    legend=dict(orientation="h", y=1.02, x=0)
)
fig3.show()

# ------------------------ QUICK SANITY PRINTS ---------------------
print(f"N = {N}, dt = {dt_seconds}s, grid duration = {N*dt_seconds/3600:.1f} h")
print("Euler latent gain dt/Ci =", dt_seconds / Ci, " -> expected scale of latent F effect per step on Ti")

# ----  helper -------------------------------------------------
def discrete_from_theta_single(theta_full):
    Ci, Cm, Ce, Ch, Cs = theta_full[0], theta_full[1], theta_full[2], theta_full[3], theta_full[4]
    g_im, g_ie, g_ih, g_is, g_ea = theta_full[5], theta_full[6], theta_full[7], theta_full[8], theta_full[9]
    g_ia = 0.0

    invC = np.array([1.0/Ci, 1.0/Cm, 1.0/Ce, 1.0/Ch, 1.0/Cs])

    # conductance matrix pieces
    G00 = -(g_im + g_ie + g_ih + g_is + g_ia)
    G01 = g_im; G02 = g_ie; G03 = g_ih; G04 = g_is
    G10 = g_im; G11 = -g_im
    G20 = g_ie; G22 = -(g_ie + g_ea)
    G30 = g_ih; G33 = -g_ih
    G40 = g_is; G44 = -g_is

    A0 = np.array([G00, G01, G02, G03, G04]) * invC[0]
    A1 = np.array([G10, G11, 0.0, 0.0, 0.0]) * invC[1]
    A2 = np.array([G20, 0.0,  G22, 0.0, 0.0]) * invC[2]
    A3 = np.array([G30, 0.0, 0.0,  G33, 0.0]) * invC[3]
    A4 = np.array([G40, 0.0, 0.0, 0.0,  G44]) * invC[4]
    A_c = np.stack([A0, A1, A2, A3, A4], axis=0)

    # inputs (heater, outdoor, solar)
    B_u  = np.zeros(5); B_u[3] = eta_h / Ch
    B_To = np.zeros(5); B_To[2] = g_ea * (1.0/Ce)
    B_Us = np.zeros(5); B_Us[0] = Aw * (1.0/Ci); B_Us[2] = Ae * (1.0/Ce)

    I5   = np.eye(5)
    Phi  = I5 + A_c * dt_seconds
    Gu   = B_u  * dt_seconds
    GTo  = B_To * dt_seconds
    GUs  = B_Us * dt_seconds
    return Phi, Gu, GTo, GUs
C_meas = np.array([[1, 0, 0, 0, 0]], float)  # we measure Ti only

Q_true = np.diag(np.full(5, 0.03**2))
R_true = np.array([[0.15**2]], float)

# fixed caps
theta_fixed_cap = np.array([Ci, Cm, Ce, Ch, Cs], float)

# g_is was FIXED in your RBPF -> fix it here too
g_is_fixed = float(g_is)

# ------------------------------------------------------------------
# helper: build full θ from the 4 free conductances
# θ = [Ci, Cm, Ce, Ch, Cs, g_im, g_ie, g_ih, g_is(fixed), g_ea]
# ------------------------------------------------------------------
def theta_from_g4(g4):
    g4 = np.maximum(np.asarray(g4, float), 1e-6)
    g_im_hat, g_ie_hat, g_ih_hat, g_ea_hat = g4
    return np.array([
        Ci, Cm, Ce, Ch, Cs,
        g_im_hat,
        g_ie_hat,
        g_ih_hat,
        g_is_fixed,   # <-- fixed
        g_ea_hat
    ], float)

# ------------------------------------------------------------------
# SSE objective: KF 1-step-ahead errors on Ti
# ------------------------------------------------------------------
def sse_g4(g4):
    theta_full = theta_from_g4(g4)
    Phi, Gam_u, Gam_To, Gam_Us = discrete_from_theta_single(theta_full)

    m = np.array([Y_meas[0]] * 5, float)
    P = np.diag(np.full(5, 0.2**2))

    sse = 0.0
    for k in range(1, len(Y_meas)):
        uk  = u[k-1]
        Tok = T_out_K[k-1]
        Usk = U_s[k-1]
        yk  = float(Y_meas[k])

        # predict
        m = Phi @ m + uk * Gam_u + Tok * Gam_To + Usk * Gam_Us
        P = Phi @ P @ Phi.T + Q_true

        # 1-step prediction of measurement
        y_pred = (C_meas @ m).item()
        err = yk - y_pred
        sse += err * err

        # KF update
        S = (C_meas @ P @ C_meas.T + R_true).item()
        S = max(S, 1e-12)
        K = (P @ C_meas.T) / S
        m = m + K.flatten() * err
        P = (np.eye(5) - K @ C_meas) @ P

    return sse

# ------------------------------------------------------------------
# optimize: 4 vars = g_im, g_ie, g_ih, g_ea  (g_is fixed)
# ------------------------------------------------------------------
g0_4 = np.array([g_im, g_ie, g_ih, g_ea], float)

bounds = [
    (0.02 * g_im,  2.0 * g_im),   # g_im
    (0.50 * g_ie,  2.0 * g_ie),   # g_ie (tightened so it can't collapse to ~0)
    (0.02 * g_ih,  2.0 * g_ih),   # g_ih
    (0.02 * g_ea,  2.0 * g_ea),   # g_ea
]

res = minimize(sse_g4, g0_4, method="L-BFGS-B", bounds=bounds)
g_im_hat, g_ie_hat, g_ih_hat, g_ea_hat = res.x

# ============ RBPF: GLOBAL RW-SV on Q + Liu–West on θ (log-space),
#               online alpha-histogram gating with continuous learning rate ============
# ---------------- Settings ----------------

Np = 4000
sigma_y_pf = 0.15

# Baseline process noise (per-state, K per step)
q_states = np.array([0.01] * 5, float)

# -------- Single global stochastic volatility (random walk on log α) ----------
alpha_min, alpha_max = 0.01, 12.0

# RW step size (same for all k)
sigma_eta_post = 0.06

# Liu–West (θ in log-space) - base parameters
a_lw  = 0.99
h2_lw = 1.0 - a_lw**2

# Gating parameters (α-based)
g_min = 0.05   # minimum learning rate (never fully freeze)

# Resampling threshold
resample_frac = 0.5

# Forecast horizon
H = 1

# Mixture sampling counts (for bands)
Nsamp_mixture_state = 2000
Nsamp_mixture_pred  = 2000
Nsamp_mixture_predH = 2000

# ---------------- Helpers ----------------
def systematic_resample(w, rng):
    N = w.size
    u0 = (rng.random() + np.arange(N)) / N
    cs = np.cumsum(w)
    idx = np.empty(N, int)
    i = j = 0
    while i < N:
        if u0[i] < cs[j]:
            idx[i] = j
            i += 1
        else:
            j += 1
    return idx

def wquantile(x, w, qs):
    x = np.asarray(x); w = np.asarray(w)
    i = np.argsort(x)
    xs, ws = x[i], w[i]
    cw = np.cumsum(ws)
    if cw[-1] > 0:
        cw = cw / cw[-1]
    else:
        cw = np.linspace(1/len(ws), 1, len(ws))
    return np.interp(qs, cw, xs)

def logsumexp(v):
    m = np.max(v)
    return m + np.log(np.sum(np.exp(v - m)))

def sample_from_weighted_gaussian_mixture(means, variances, weights, Nsamp, rng):
    weights = np.asarray(weights, float)
    cw = np.cumsum(weights)
    if cw[-1] > 0:
        cw = cw / cw[-1]
    else:
        cw = np.linspace(1/len(weights), 1, len(weights))
    u = (rng.random(Nsamp) + np.arange(Nsamp)) / Nsamp
    idx = np.searchsorted(cw, u, side='right')
    idx = np.clip(idx, 0, len(weights)-1)
    stds = np.sqrt(np.maximum(variances[idx], 1e-12))
    return means[idx] + stds * rng.standard_normal(Nsamp)

# ---------------- Data ----------------
Y_meas  = np.asarray(Y_meas, float).ravel()
u_arr   = np.asarray(u, float).ravel()
T_out_K = np.asarray(T_out_K, float).ravel()
U_s_arr = np.asarray(U_s, float).ravel()
N       = int(len(Y_meas))

# Measurement matrix (Ti only)
C_y = np.array([[1, 0, 0, 0, 0]], float)

# True Ti (optional diag)
has_Ti_true = 'Y_Ti' in globals()
if has_Ti_true:
    Ti_true = np.asarray(Y_Ti, float).ravel()
    Ti_true_C = Ti_true - 273.15

# ---------------- θ definition ----------------
theta_names = [
    "Ci","Cm","Ce","Ch","Cs",
    "g_im","g_ie","g_ih","g_is","g_ea"
]

theta_true = np.array([
    Ci, Cm, Ce, Ch, Cs,
    g_im, g_ie, g_ih, g_is, g_ea
], float)

_param_defaults = {
    # Capacitances
    "Ci": Ci,
    "Cm": (0.1*Cm, 3*Cm),
    "Ce": (0.1*Ce, 3*Ce),
    "Ch": Ch,
    "Cs": Cs,
    # Conductances
    "g_im": (0.1*g_im, 3*g_im),
    "g_ie": (0.1*g_ie, 3*g_ie),
    "g_ih": (0.1*g_ih, 3*g_ih),
    "g_is": g_is,
    "g_ea": (0.1*g_ea, 3*g_ea)
}
param_ranges = _param_defaults

theta_eps = 1e-20
dθ        = len(theta_names)
theta_lo  = np.empty(dθ, float)
theta_hi  = np.empty(dθ, float)
is_fixed  = np.zeros(dθ, dtype=bool)

for j, nm in enumerate(theta_names):
    spec = param_ranges[nm]
    if isinstance(spec, (tuple, list)) and len(spec) == 2:
        lo, hi = float(spec[0]), float(spec[1])
    else:
        lo = hi = float(spec)
    lo = max(lo, theta_eps)
    hi = max(hi, theta_eps)
    theta_lo[j] = lo
    theta_hi[j] = hi
    is_fixed[j] = (hi == lo)

is_free   = ~is_fixed
free_idx  = np.nonzero(is_free)[0]
fixed_idx = np.nonzero(is_fixed)[0]

tau_defs = [
    ("Ci/g_im", 0, 5, Ci / g_im),
    ("Ci/g_ie", 0, 6, Ci / g_ie),
    ("Ci/g_ih", 0, 7, Ci / g_ih),
    ("Ci/g_is", 0, 8, Ci / g_is),
    ("Cm/g_im", 1, 5, Cm / g_im),
    ("Ce/g_ie", 2, 6, Ce / g_ie),
    ("Ce/g_ea", 2, 9, Ce / g_ea),
    ("Ch/g_ih", 3, 7, Ch / g_ih),
    ("Cs/g_is", 4, 8, Cs / g_is),
]
n_tau = len(tau_defs)

# ---------------- Initialization ----------------
rng = np.random.default_rng(123)
T_start_K = float(Y_meas[0]) if np.isfinite(Y_meas[0]) else float(T_out_K[0])

# KF state
m = np.tile(np.array([T_start_K]*5, float), (Np, 1))
P0 = np.diag(np.full(5, 0.2**2))
P  = np.tile(P0, (Np, 1, 1))

# Global alpha (single dynamic scalar, random walk in log-space)
log_alpha = rng.normal(0.0, 0.1, size=Np)
log_alpha = np.clip(log_alpha, np.log(alpha_min), np.log(alpha_max))
alpha     = np.exp(log_alpha)

# θ particles in log-space
phi_lo = np.log(np.clip(theta_lo, theta_eps, None))
phi_hi = np.log(np.clip(theta_hi, theta_eps, None))
phi    = rng.uniform(low=phi_lo[None, :], high=phi_hi[None, :], size=(Np, dθ))
if fixed_idx.size > 0:
    phi[:, fixed_idx] = np.log(np.clip(theta_lo[fixed_idx], theta_eps, None))
theta = np.exp(phi)

logw = np.full(Np, -np.log(Np), float)
Q0   = np.diag(q_states**2)
Q0_diag = np.diag(Q0).copy()
R    = np.array([[sigma_y_pf**2]], float)

# Gating bookkeeping (online α-histogram)
regime_flag   = np.zeros(N, dtype=int)  # 0 = quiet/learning-ish, 1 = high-vol/burst
z_std_innov   = np.zeros(N)

# Histogram settings for log(alpha)
n_bins_alpha  = 30
log_alpha_min = np.log(alpha_min)
log_alpha_max = np.log(alpha_max)
alpha_bin_edges = np.linspace(log_alpha_min, log_alpha_max, n_bins_alpha + 1)

# Pseudo-counts for a uniform prior over bins
pseudo_count = 1.0
alpha_hist_counts = np.full(n_bins_alpha, pseudo_count, dtype=float)

# Continuous gating thresholds in CDF-space:
#   F_quiet  ~ below this => full learning (g = 1)
#   F_burst  ~ above this => minimal learning (g = g_min)
F_quiet = 0.50   # bottom 50% of α-history => clearly "quiet"
F_burst = 0.80   # top 20% of α-history   => clearly "burst"

# Storage
q_lo, q_md, q_hi = 0.025, 0.50, 0.975
Ti_lo = np.zeros(N); Ti_md = np.zeros(N); Ti_hi = np.zeros(N)
Alpha_lo = np.zeros(N); Alpha_md = np.zeros(N); Alpha_hi = np.zeros(N)
Th_lo = np.zeros((N, dθ)); Th_md = np.zeros((N, dθ)); Th_hi = np.zeros((N, dθ))
Y_pred_mean = np.full(N, np.nan)
Y_pred_std  = np.full(N, np.nan)
Tau_lo = np.zeros((N, n_tau))
Tau_md = np.zeros((N, n_tau))
Tau_hi = np.zeros((N, n_tau))

if H >= 1:
    YH_pred_mean  = np.full((N, H), np.nan)
    YH_pred_lo    = np.full((N, H), np.nan)
    YH_pred_hi    = np.full((N, H), np.nan)
    TiH_pred_mean = np.full((N, H), np.nan)
    TiH_pred_lo   = np.full((N, H), np.nan)
    TiH_pred_md   = np.full((N, H), np.nan)
    TiH_pred_hi   = np.full((N, H), np.nan)

# t=0 summaries
w_lin = np.exp(logw - logsumexp(logw))
Ti_draws_0 = sample_from_weighted_gaussian_mixture(
    m[:, 0], P[:, 0, 0], w_lin, Nsamp_mixture_state, rng
)
TiC0 = Ti_draws_0 - 273.15
Ti_lo[0], Ti_md[0], Ti_hi[0] = np.quantile(TiC0, [q_lo, q_md, q_hi])
Alpha_lo[0], Alpha_md[0], Alpha_hi[0] = wquantile(alpha, w_lin, [q_lo, q_md, q_hi])
for j in range(dθ):
    Th_lo[0, j], Th_md[0, j], Th_hi[0, j] = wquantile(theta[:, j], w_lin, [q_lo, q_md, q_hi])
for t_idx, (_, c_idx, g_idx, _) in enumerate(tau_defs):
    tau_vals = theta[:, c_idx] / np.maximum(theta[:, g_idx], 1e-300)
    Tau_lo[0, t_idx], Tau_md[0, t_idx], Tau_hi[0, t_idx] = \
        wquantile(tau_vals, w_lin, [q_lo, q_md, q_hi])

# Initialize histogram with α-median at t=0
alpha_med_0 = Alpha_md[0]
log_alpha_med_0 = np.log(np.clip(alpha_med_0, alpha_min, alpha_max))
bin_idx_0 = np.searchsorted(alpha_bin_edges, log_alpha_med_0, side='right') - 1
bin_idx_0 = np.clip(bin_idx_0, 0, n_bins_alpha - 1)
alpha_hist_counts[bin_idx_0] += 1.0

# ---------------- VECTORIZED EULER Discretization from θ ----------------
def discrete_from_theta(theta_arr):
    Np_loc = theta_arr.shape[0]
    Ci = theta_arr[:, 0]; Cm = theta_arr[:, 1]; Ce = theta_arr[:, 2]
    Ch = theta_arr[:, 3]; Cs = theta_arr[:, 4]
    gim = theta_arr[:, 5]; gie = theta_arr[:, 6]; gih = theta_arr[:, 7]
    gis = theta_arr[:, 8]; gea = theta_arr[:, 9]
    gia = np.zeros_like(gea)

    invC = np.stack([1.0/Ci, 1.0/Cm, 1.0/Ce, 1.0/Ch, 1.0/Cs], axis=1)

    # G entries
    G00 = -(gim + gie + gih + gis + gia)
    G01 = gim; G02 = gie; G03 = gih; G04 = gis
    G10 = gim; G11 = -gim
    G20 = gie; G22 = -(gie + gea)
    G30 = gih; G33 = -gih
    G40 = gis; G44 = -gis
    Z0  = np.zeros_like(G00)

    # A_c rows
    A0 = np.stack([G00, G01, G02, G03, G04], axis=1) * invC[:, [0]]
    A1 = np.stack([G10, G11, Z0,  Z0,  Z0 ], axis=1) * invC[:, [1]]
    A2 = np.stack([G20, Z0,  G22, Z0,  Z0 ], axis=1) * invC[:, [2]]
    A3 = np.stack([G30, Z0,  Z0,  G33, Z0 ], axis=1) * invC[:, [3]]
    A4 = np.stack([G40, Z0,  Z0,  Z0,  G44], axis=1) * invC[:, [4]]
    A_c = np.stack([A0, A1, A2, A3, A4], axis=1)

    # Inputs
    B_u  = np.zeros((Np_loc, 5), float); B_u[:, 3] = eta_h / Ch
    B_To = np.zeros((Np_loc, 5), float); B_To[:, 0] = 0.0*(1.0/Ci); B_To[:, 2] = gea*(1.0/Ce)
    B_Us = np.zeros((Np_loc, 5), float); B_Us[:, 0] = Aw *(1.0/Ci); B_Us[:, 2] = Ae *(1.0/Ce)

    # Discretize (Euler)
    Phi   = np.eye(5)[None, :, :] + A_c * dt_seconds
    Gam_u = B_u  * dt_seconds
    Gam_To= B_To * dt_seconds
    Gam_Us= B_Us * dt_seconds
    return Phi, Gam_u, Gam_To, Gam_Us

# ---------------- RBPF loop ----------------
const_ll = -0.5 * np.log(2*np.pi)
I5_batch = np.eye(5)[None, :, :]

for k in range(1, N):
    uk, Tok, Usk = u_arr[k-1], T_out_K[k-1], U_s_arr[k-1]
    yk = float(Y_meas[k])

    # Prior weights
    w_lin_prior = np.exp(logw - logsumexp(logw))

    # (A) Global SV: random walk on log_alpha (always active)
    sigma_eta_eff = sigma_eta_post
    log_alpha = log_alpha + rng.normal(0.0, sigma_eta_eff, size=Np)
    log_alpha = np.clip(log_alpha, np.log(alpha_min), np.log(alpha_max))
    alpha     = np.exp(log_alpha)

    # Effective α for gating: weighted median under PRIOR weights
    alpha_med_k = wquantile(alpha, w_lin_prior, [0.5])[0]

    # (B) α-based gating logic using an online histogram over log(alpha)
    # ------------------------------------------------------------------
    # 1) Compute log(alpha_med_k) and clamp to [log_alpha_min, log_alpha_max]
    log_alpha_med_k = np.log(np.clip(alpha_med_k, alpha_min, alpha_max))

    # 2) Find which bin contains log_alpha_med_k
    bin_idx = np.searchsorted(alpha_bin_edges, log_alpha_med_k, side='right') - 1
    bin_idx = np.clip(bin_idx, 0, n_bins_alpha - 1)

    # 3) Increment that bin's count (online histogram update)
    alpha_hist_counts[bin_idx] += 1.0

    # 4) Build CDF over bins and get F_k = P(log_alpha ≤ log_alpha_med_k)
    cdf_bins = np.cumsum(alpha_hist_counts)
    cdf_bins /= cdf_bins[-1]
    F_k = cdf_bins[bin_idx]

    # 5) Continuous gating rule in CDF-space:
    #    - If F_k <= F_quiet : clearly quiet  -> g_alpha = 1.0 (full learning)
    #    - If F_k >= F_burst : clearly burst  -> g_alpha = g_min (almost freeze)
    #    - Else              : intermediate   -> linearly interpolate between 1 and g_min
    if F_k <= F_quiet:
        g_alpha = 1.0
        regime_flag[k] = 0   # quiet / learning
    elif F_k >= F_burst:
        g_alpha = g_min
        regime_flag[k] = 1   # high-vol / burst
    else:
        # Linear interpolation: F_quiet -> 1.0, F_burst -> g_min
        r = (F_burst - F_k) / (F_burst - F_quiet + 1e-12)
        g_alpha = g_min + (1.0 - g_min) * r
        regime_flag[k] = 0   # treat as learning-ish

    # Final gate (safeguard; g_alpha should already be >= g_min)
    g_k = max(g_alpha, g_min)

    # (C) Liu–West on θ (soft-gated by g_k)
    phi = np.log(np.clip(theta, theta_eps, None))

    if free_idx.size > 0:
        # Effective shrinkage and jitter for this step
        a_k  = 1.0 - g_k * (1.0 - a_lw)
        h2_k = g_k * h2_lw

        # Weighted mean of free log-parameters (prior weights)
        phi_bar_free = np.sum(phi[:, free_idx] * w_lin_prior[:, None], axis=0)

        diff_free = phi[:, free_idx] - phi_bar_free[None, :]
        V_free    = diff_free.T @ (diff_free * w_lin_prior[:, None])
        V_free    = 0.5 * (V_free + V_free.T) + 1e-12 * np.eye(free_idx.size)

        # Jitter ~ N(0, h2_k * V_free)
        L_free   = np.linalg.cholesky(V_free)
        eps_free = rng.standard_normal((Np, free_idx.size)) @ (np.sqrt(h2_k) * L_free.T)

        # Shrink toward mean with a_k and add jitter
        phi[:, free_idx] = (
            a_k * phi[:, free_idx] +
            (1.0 - a_k) * phi_bar_free[None, :] +
            eps_free
        )

        # Enforce bounds in log-space
        phi[:, free_idx] = np.clip(
            phi[:, free_idx],
            phi_lo[None, free_idx],
            phi_hi[None, free_idx]
        )
    if fixed_idx.size > 0:
        phi[:, fixed_idx] = np.log(np.clip(theta_lo[fixed_idx], theta_eps, None))

    theta = np.exp(phi)

    # (D) Build per-particle matrices
    Phi_i, Gu_i, GTo_i, GUs_i = discrete_from_theta(theta)

    # (E) Kalman predict
    m_pred = np.einsum('ni,nji->nj', m, Phi_i)
    m_pred += uk  * Gu_i
    m_pred += Tok * GTo_i
    m_pred += Usk * GUs_i

    P_pred = np.einsum('nij,njk,nlk->nil', Phi_i, P, Phi_i)

    # Single dynamic scalar on Q (scaled by α)
    scale_sq = np.exp(2.0 * log_alpha)
    qdiag    = scale_sq[:, None] * Q0_diag[None, :]
    for s in range(5):
        P_pred[:, s, s] += qdiag[:, s]

    # (F) Prior predictive Y
    y_pred = (m_pred @ C_y.T).ravel()
    S      = np.einsum('ij,njk,kl->n', C_y, P_pred, C_y.T) + R[0, 0]
    S      = np.maximum(S, 1e-12)

    mu_k  = np.sum(w_lin_prior * y_pred)
    var_k = np.sum(w_lin_prior * (y_pred**2 + S)) - mu_k**2
    var_k = max(var_k, 1e-12)
    Y_pred_mean[k] = mu_k
    Y_pred_std[k]  = np.sqrt(var_k)

    z_k = (yk - mu_k) / np.sqrt(var_k)
    z_std_innov[k] = z_k

    # (G) Weights
    innov = yk - y_pred
    ll    = const_ll - 0.5*np.log(S) - 0.5*(innov**2)/S
    logw  = logw + ll
    logw  = logw - logsumexp(logw)
    w_lin_post = np.exp(logw)

    # (H) Kalman update
    K = (P_pred @ C_y.T) / S[:, None, None]
    m = m_pred + (K.reshape(Np, 5) * innov[:, None])
    KC = np.matmul(K, C_y)
    P  = np.matmul(I5_batch - KC, P_pred)

    # H-step forecasts
    if H >= 1:
        m_h = m.copy()
        P_h = P.copy()
        scale_sq_h = np.exp(2.0 * log_alpha)
        qdiag_h    = scale_sq_h[:, None] * Q0_diag[None, :]
        for h in range(1, H+1):
            kh   = min(k + h - 1, N-1)
            uk_h = u_arr[kh]
            Tok_h= T_out_K[kh]
            Usk_h= U_s_arr[kh]

            m_h = np.einsum('ni,nji->nj', m_h, Phi_i)
            m_h += uk_h  * Gu_i
            m_h += Tok_h * GTo_i
            m_h += Usk_h * GUs_i

            P_h = np.einsum('nij,njk,nlk->nil', Phi_i, P_h, Phi_i)
            for s in range(5):
                P_h[:, s, s] += qdiag_h[:, s]

            y_mean_i = (m_h @ C_y.T).ravel()
            S_i      = np.einsum('ij,njk,kl->n', C_y, P_h, C_y.T) + R[0, 0]
            S_i      = np.maximum(S_i, 1e-12)
            YH_pred_mean[k, h-1] = float(np.sum(w_lin_post * y_mean_i))

            Nsamp = Nsamp_mixture_predH
            cw = np.cumsum(w_lin_post)
            if cw[-1] > 0:
                cw = cw / cw[-1]
            else:
                cw = np.linspace(1/len(w_lin_post), 1, len(w_lin_post))
            u_unif = (rng.random(Nsamp) + np.arange(Nsamp)) / Nsamp
            idx = np.searchsorted(cw, u_unif, side='right')
            idx = np.clip(idx, 0, len(w_lin_post)-1)
            y_samps = y_mean_i[idx] + np.sqrt(S_i[idx]) * rng.standard_normal(Nsamp)
            YH_pred_lo[k, h-1], _, YH_pred_hi[k, h-1] = np.quantile(
                y_samps, [0.025, 0.5, 0.975]
            )

            Ti_means = m_h[:, 0]
            Ti_vars  = P_h[:, 0, 0]
            Ti_mean_mix_K = float(np.sum(w_lin_post * Ti_means))
            TiH_pred_mean[k, h-1] = Ti_mean_mix_K - 273.15
            Ti_samps_K = sample_from_weighted_gaussian_mixture(
                Ti_means, Ti_vars, w_lin_post, Nsamp_mixture_predH, rng
            )
            Ti_samps_C = Ti_samps_K - 273.15
            TiH_pred_lo[k, h-1], TiH_pred_md[k, h-1], TiH_pred_hi[k, h-1] = \
                np.quantile(Ti_samps_C, [0.025, 0.5, 0.975])

    # Summaries at time k
    Ti_draws = sample_from_weighted_gaussian_mixture(
        m[:, 0], P[:, 0, 0], w_lin_post, Nsamp_mixture_state, rng
    )
    TiC = Ti_draws - 273.15
    Ti_lo[k], Ti_md[k], Ti_hi[k] = np.quantile(TiC, [q_lo, q_md, q_hi])
    Alpha_lo[k], Alpha_md[k], Alpha_hi[k] = wquantile(alpha, w_lin_post, [q_lo, q_md, q_hi])

    for j in range(dθ):
        Th_lo[k, j], Th_md[k, j], Th_hi[k, j] = wquantile(
            theta[:, j], w_lin_post, [q_lo, q_md, q_hi]
        )

    for t_idx, (_, c_idx, g_idx, _) in enumerate(tau_defs):
        tau_vals = theta[:, c_idx] / np.maximum(theta[:, g_idx], 1e-300)
        Tau_lo[k, t_idx], Tau_md[k, t_idx], Tau_hi[k, t_idx] = \
            wquantile(tau_vals, w_lin_post, [q_lo, q_md, q_hi])

    # Resample if needed
    Neff = 1.0 / np.sum(w_lin_post * w_lin_post)
    if Neff < resample_frac * Np:
        idx = systematic_resample(w_lin_post, rng)
        m         = m[idx]
        P         = P[idx]
        log_alpha = log_alpha[idx]
        alpha     = alpha[idx]
        theta     = theta[idx]
        logw[:]   = -np.log(Np)

# ================================
# Frequency-domain convergence diagnostics


# How many RBPF steps to skip between TF evaluations.
SKIP_STEPS = 50

# Number of frequency points between DC and Nyquist
Nw = 300

# ------------------------------------------------------------
# 1) Offline LS parameter vector (your existing structure)
# ------------------------------------------------------------
theta_ls = np.array([
    Ci, Cm, Ce, Ch, Cs,
    g_im_hat, g_ie_hat, g_ih_hat, g_is, g_ea_hat
], float)
# If your theta has an extra entry (e.g. s_Q_scale), append it here
# so it matches theta_true and Th_md in length.

# ------------------------------------------------------------
# 2) Helpers: build SISO SS and compute H2-like energy error
# ------------------------------------------------------------

def build_siso_ss_from_theta(theta, channel):
    """
    Build a SISO discrete-time state-space model for a given input channel:
      'solar'   : U_s     -> Ti
      'heater'  : u       -> Ti
      'outside' : T_out   -> Ti
    """
    Phi, G_u, G_To, G_Us = discrete_from_theta_single(theta)

    if channel == 'solar':
        B = G_Us.reshape(-1, 1)
    elif channel == 'heater':
        B = G_u.reshape(-1, 1)
    elif channel == 'outside':
        B = G_To.reshape(-1, 1)
    else:
        raise ValueError(f"Unknown channel: {channel}")

    C = C_y.reshape(1, -1)   # Ti output
    D = np.zeros((1, 1))

    sys = control.ss(Phi, B, C, D, dt=dt_seconds)
    return sys


def tf_h2_error(theta_est, theta_true, channel, w_grid):
    """
    H2-like energy error between learned and true TF for one channel.

    We approximate:
        ||G_est - G_true||_H2 ≈ sqrt( mean_ω |G_est(e^{jw}) - G_true(e^{jw})|^2 )

    The constant factors from the continuous definition are irrelevant
    for *comparisons* (RBPF vs LS vs EKF/UKF), so we use RMS over the grid.
    """
    sys_true = build_siso_ss_from_theta(theta_true, channel)
    sys_est  = build_siso_ss_from_theta(theta_est,  channel)

    # python-control: mag, phase, omega
    mag_true, phase_true, _ = control.freqresp(sys_true, w_grid)
    mag_est,  phase_est,  _ = control.freqresp(sys_est,  w_grid)

    mag_true = mag_true.squeeze()
    mag_est  = mag_est.squeeze()
    phase_true = phase_true.squeeze()
    phase_est  = phase_est.squeeze()

    # Complex FRFs
    G_true = mag_true * np.exp(1j * phase_true)
    G_est  = mag_est  * np.exp(1j * phase_est)

    diff = G_est - G_true
    # RMS of complex error over frequency grid (H2-like)
    E = np.sqrt(np.mean(np.abs(diff)**2))

    return E


# ------------------------------------------------------------
# 3) Frequency grid (0 .. Nyquist)
#    For discrete-time system with sample time dt_seconds,
#    Nyquist angular frequency is pi / dt_seconds [rad/s].
# ------------------------------------------------------------
w_grid = np.linspace(0.0, np.pi / dt_seconds, Nw)

channels = ['solar', 'heater', 'outside']

# ------------------------------------------------------------
# 4) Baseline: offline LS vs true (constant per channel)
# ------------------------------------------------------------
baseline_errors = {}
for ch in channels:
    baseline_errors[ch] = tf_h2_error(
        theta_est=theta_ls,
        theta_true=theta_true,
        channel=ch,
        w_grid=w_grid
    )

print("Baseline offline LS H2-like TF energy errors:")
for ch in channels:
    print(f"  {ch:8s}: {baseline_errors[ch]:.6e}")


# ------------------------------------------------------------
# 5) RBPF: time-varying H2-like TF energy error vs true
#    Use parameter means if you have them; here we use Th_md.
# ------------------------------------------------------------
Theta_rbpf = Th_md   # shape (N_T, d_theta); swap to Th_mean if you compute it

N_T, d_theta = Theta_rbpf.shape

sample_indices = np.arange(0, N_T, SKIP_STEPS)
t_hours = sample_indices * dt_seconds / 3600.0

rbpf_errors = {ch: np.zeros_like(sample_indices, dtype=float) for ch in channels}

for idx, k in enumerate(sample_indices):
    theta_k = Theta_rbpf[k, :]  # RBPF parameters at time k

    for ch in channels:
        rbpf_errors[ch][idx] = tf_h2_error(
            theta_est=theta_k,
            theta_true=theta_true,
            channel=ch,
            w_grid=w_grid
        )

# Print final RBPF error (last TF evaluated) per channel
print("\nFinal RBPF H2-like TF energy errors (last evaluated time):")
for ch in channels:
    print(f"  {ch:8s}: {rbpf_errors[ch][-1]:.6e}")

def tf_h2_norm(theta, channel, w_grid):
    sys = build_siso_ss_from_theta(theta, channel)
    mag, phase, _ = control.freqresp(sys, w_grid)
    G = mag.squeeze() * np.exp(1j*phase.squeeze())
    return np.sqrt(np.mean(np.abs(G)**2))

for ch in channels:
    norm_true = tf_h2_norm(theta_true, ch, w_grid)
    err_ls    = baseline_errors[ch]
    err_rbpf  = rbpf_errors[ch][-2]
    print(f"{ch}: rel LS={err_ls/norm_true:.3e}, rel RBPF={err_rbpf/norm_true:.3e}")

from filterpy.kalman import ExtendedKalmanFilter
import numpy as np

# -----------------------------------------------
# 1) Parameter Setup (Linear Bounds → Log-Space)
# -----------------------------------------------
theta_eps = 1e-20
theta_lo = np.empty(len(theta_names), float)
theta_hi = np.empty(len(theta_names), float)
is_fixed = np.zeros(len(theta_names), dtype=bool)

for j, nm in enumerate(theta_names):
    spec = param_ranges[nm]
    if isinstance(spec, (tuple, list)) and len(spec) == 2:
        lo, hi = float(spec[0]), float(spec[1])
    else:
        lo = hi = float(spec)
    lo = max(lo, theta_eps); hi = max(hi, theta_eps)
    theta_lo[j] = lo
    theta_hi[j] = hi
    is_fixed[j] = (hi == lo)

free_idx  = np.nonzero(~is_fixed)[0]
fixed_idx = np.nonzero(is_fixed)[0]
n_free    = free_idx.size

# Helper: build full θ from free log-parameters
def theta_from_phi(phi_log, theta_base, free_idx):
    theta_full = theta_base.copy()
    theta_full[free_idx] = np.exp(phi_log)
    return theta_full

# -----------------------------------------------
# 2) Euler Discretization Helper
#    Computes x_{k+1} = (I + A*dt)x_k + (B*dt)u_k
# -----------------------------------------------
def discrete_system_euler(theta_full, dt):
    """
    Euler discretization to match data generation.
    Phi = I + A_c * dt
    Gamma = B_c * dt
    """
    Ci, Cm, Ce, Ch, Cs = theta_full[0], theta_full[1], theta_full[2], theta_full[3], theta_full[4]
    g_im, g_ie, g_ih, g_is, g_ea = theta_full[5], theta_full[6], theta_full[7], theta_full[8], theta_full[9]
    g_ia = 0.0

    invC = np.array([1.0/Ci, 1.0/Cm, 1.0/Ce, 1.0/Ch, 1.0/Cs])

    # --- Construct Continuous A matrix (5x5) ---
    d0 = -(g_im + g_ie + g_ih + g_is + g_ia)
    d1 = -g_im
    d2 = -(g_ie + g_ea)
    d3 = -g_ih
    d4 = -g_is

    A_c = np.zeros((5,5))
    A_c[0,:] = [d0, g_im, g_ie, g_ih, g_is]
    A_c[1,:] = [g_im, d1, 0, 0, 0]
    A_c[2,:] = [g_ie, 0, d2, 0, 0]
    A_c[3,:] = [g_ih, 0, 0, d3, 0]
    A_c[4,:] = [g_is, 0, 0, 0, d4]

    # Scale rows by 1/C
    A_c = (A_c.T * invC).T

    # --- Construct Continuous B matrices ---
    B_u  = np.zeros(5); B_u[3]  = eta_h * invC[3]
    B_To = np.zeros(5); B_To[2] = g_ea  * invC[2]
    B_Us = np.zeros(5); B_Us[0] = Aw * invC[0]; B_Us[2] = Ae * invC[2]

    # --- Euler Discretization ---
    Phi = np.eye(5) + A_c * dt
    Gu  = B_u  * dt
    GTo = B_To * dt
    GUs = B_Us * dt

    return Phi, Gu, GTo, GUs

# -----------------------------------------------
# 3) Data Setup
# -----------------------------------------------
Y_meas  = np.asarray(Y_meas, float).ravel()
u_arr   = np.asarray(u, float).ravel()
T_out_K = np.asarray(T_out_K, float).ravel()
U_s_arr = np.asarray(U_s, float).ravel()
N       = int(len(Y_meas))

R = np.array([[sigma_y_pf**2]], float)

# Process noise for STATES
q_states = np.array([0.03]*5, float)
Qx_base  = np.diag(q_states**2)

# Process noise for LOG-PARAMETERS
# std=0.002 in log space means ~0.2% multiplicative drift per step
sigma_log_theta_rw = 0.002
Q_log_theta = np.diag(np.full(n_free, sigma_log_theta_rw**2))

# -----------------------------------------------
# 4) Log-EKF Initialization (FilterPy)
# -----------------------------------------------
x0 = np.array([Y_meas[0]]*5, float)

# Init theta in Linear Space, convert to Log Space
theta0_full = theta_lo.copy()
theta0_full[free_idx] = 0.5 * (theta_lo[free_idx] + theta_hi[free_idx])
phi0_free = np.log(theta0_full[free_idx])

# Augmented State z = [x; phi]
z0 = np.concatenate([x0, phi0_free], axis=0)
nz = z0.size

# Initial covariance
P0 = np.zeros((nz, nz), float)
P0[:5, :5] = np.diag(np.full(5, 0.2**2))
P0[5:, 5:] = np.diag(np.full(n_free, 0.3**2))  # log-space variance

# Build augmented Q
Q_aug = np.zeros((nz, nz), float)
Q_aug[:5, :5] = Qx_base
Q_aug[5:, 5:] = Q_log_theta

# Set up FilterPy EKF
ekf = ExtendedKalmanFilter(dim_x=nz, dim_z=1)
ekf.x = z0.copy()
ekf.P = P0.copy()
ekf.Q = Q_aug.copy()
ekf.R = R.copy()

# Measurement functions (Ti only)
def hx(z):
    # measurement is indoor temperature Ti
    return np.array([z[0]])

def H_jacobian(z):
    H = np.zeros((1, nz))
    H[0, 0] = 1.0
    return H

# -----------------------------------------------
# 5) Storage
# -----------------------------------------------
Ti_mean_ekf   = np.zeros(N)
Ti_var_ekf    = np.zeros(N)
Yhat          = np.zeros(N)
S_arr         = np.zeros(N)
Theta_traj_ekf = np.zeros((N, len(theta_names)))  # linear θ

# t = 0 save
Ti_mean_ekf[0] = ekf.x[0]
Ti_var_ekf[0]  = ekf.P[0,0]
Yhat[0]        = ekf.x[0]
S_arr[0]       = ekf.P[0,0] + ekf.R[0,0]
Theta_traj_ekf[0] = theta0_full.copy()

# -----------------------------------------------
# 6) EKF Loop (Log-Space + Euler, using FilterPy)
# -----------------------------------------------
print("Running Log-Space EKF (Euler, FilterPy)...")

eps_fd = 1e-5

for k in range(1, N):
    uk  = u_arr[k-1]
    Tok = T_out_K[k-1]
    Usk = U_s_arr[k-1]
    yk  = float(Y_meas[k])

    # Unpack
    x_k   = ekf.x[:5].copy()
    phi_k = ekf.x[5:].copy()

    # 1. Physics in Linear Space
    theta_full = theta_from_phi(phi_k, theta0_full, free_idx)
    Phi_k, Gu_k, GTo_k, GUs_k = discrete_system_euler(theta_full, dt_seconds)

    # 2. Predict state (Euler)
    x_pred   = Phi_k @ x_k + uk*Gu_k + Tok*GTo_k + Usk*GUs_k
    phi_pred = phi_k
    z_pred   = np.concatenate([x_pred, phi_pred])

    # 3. Jacobian F = d(z_next)/d(z)
    F = np.eye(nz)
    F[:5, :5] = Phi_k

    # Jacobian d(x_next)/d(phi) via finite differences in log-space
    for i, idx_free in enumerate(free_idx):
        phi_pert = phi_k.copy()
        phi_pert[i] += eps_fd

        theta_full_p = theta_from_phi(phi_pert, theta0_full, free_idx)
        Phi_p, Gu_p, GTo_p, GUs_p = discrete_system_euler(theta_full_p, dt_seconds)
        x_pred_p = Phi_p @ x_k + uk*Gu_p + Tok*GTo_p + Usk*GUs_p

        dx_dphi = (x_pred_p - x_pred) / eps_fd
        F[:5, 5+i] = dx_dphi

    # 4. Predict covariance with F and Q
    P_pred = F @ ekf.P @ F.T + ekf.Q

    # Put prediction into the EKF object
    ekf.x = z_pred
    ekf.P = P_pred
    ekf.F = F  # optional, but keeps EKF state consistent

    # Predicted measurement and innovation variance (for logging)
    y_pred = hx(z_pred)[0]
    H_aug  = H_jacobian(z_pred)
    S      = (H_aug @ P_pred @ H_aug.T + ekf.R).item()

    # 5. Measurement update via FilterPy EKF
    z_meas = np.array([yk])
    ekf.update(z_meas, HJacobian=H_jacobian, Hx=hx)

    # 6. Store results
    Ti_mean_ekf[k] = ekf.x[0]
    Ti_var_ekf[k]  = ekf.P[0,0]
    Yhat[k]        = y_pred
    S_arr[k]       = S

    theta_k = theta_from_phi(ekf.x[5:], theta0_full, free_idx)
    Theta_traj_ekf[k] = theta_k

# Explicitly calculate bands for later
Ti_lo_ekf = (Ti_mean_ekf - 1.96*np.sqrt(Ti_var_ekf)) - 273.15
Ti_hi_ekf = (Ti_mean_ekf + 1.96*np.sqrt(Ti_var_ekf)) - 273.15

print("Log-Space EKF (FilterPy) Complete.")

# ==================== LOG-SPACE UKF (Euler Discretization) ====================
from filterpy.kalman import UnscentedKalmanFilter, MerweScaledSigmaPoints

# -----------------------------------------------
# 1) Parameter Setup (Log-Space Logic)
# -----------------------------------------------
theta_eps = 1e-20
theta_lo = np.empty(len(theta_names), float)
theta_hi = np.empty(len(theta_names), float)
is_fixed = np.zeros(len(theta_names), dtype=bool)

for j, nm in enumerate(theta_names):
    spec = param_ranges[nm]
    if isinstance(spec, (tuple, list)) and len(spec) == 2:
        lo, hi = float(spec[0]), float(spec[1])
    else:
        lo = hi = float(spec)
    lo = max(lo, theta_eps); hi = max(hi, theta_eps)
    theta_lo[j] = lo
    theta_hi[j] = hi
    is_fixed[j] = (hi == lo)

free_idx  = np.nonzero(~is_fixed)[0]
fixed_idx = np.nonzero(is_fixed)[0]
n_free    = free_idx.size

# -----------------------------------------------
# 2) Discretization Helper (Same as EKF: Euler via Control)
# -----------------------------------------------
def discrete_system_control(theta_full, dt):
    Ci, Cm, Ce, Ch, Cs = theta_full[0], theta_full[1], theta_full[2], theta_full[3], theta_full[4]
    g_im, g_ie, g_ih, g_is, g_ea = theta_full[5], theta_full[6], theta_full[7], theta_full[8], theta_full[9]
    g_ia = 0.0

    invC = np.array([1.0/Ci, 1.0/Cm, 1.0/Ce, 1.0/Ch, 1.0/Cs])

    # A Matrix
    A_c = np.zeros((5,5))
    d0 = -(g_im + g_ie + g_ih + g_is + g_ia)
    d1 = -g_im
    d2 = -(g_ie + g_ea)
    d3 = -g_ih
    d4 = -g_is

    A_c[0,:] = [d0, g_im, g_ie, g_ih, g_is]
    A_c[1,:] = [g_im, d1, 0, 0, 0]
    A_c[2,:] = [g_ie, 0, d2, 0, 0]
    A_c[3,:] = [g_ih, 0, 0, d3, 0]
    A_c[4,:] = [g_is, 0, 0, 0, d4]

    A_c = (A_c.T * invC).T

    # B Matrix
    B_c = np.zeros((5, 3))
    B_c[3, 0] = eta_h * invC[3] # u
    B_c[2, 1] = g_ea * invC[2]  # To
    B_c[0, 2] = Aw * invC[0]    # Us
    B_c[2, 2] = Ae * invC[2]    # Us

    # Discretize
    sys_c = control.ss(A_c, B_c, np.eye(5), np.zeros((5,3)))
    sys_d = sys_c.sample(dt, method='euler')

    return sys_d.A, sys_d.B[:, 0], sys_d.B[:, 1], sys_d.B[:, 2]

# -----------------------------------------------
# 3) Data Setup
# -----------------------------------------------
Y_meas  = np.asarray(Y_meas, float).ravel()
u_arr   = np.asarray(u, float).ravel()
T_out_K = np.asarray(T_out_K, float).ravel()
U_s_arr = np.asarray(U_s, float).ravel()
N       = int(len(Y_meas))

C_meas = np.zeros((1,5), float); C_meas[0,0] = 1.0
R      = np.array([[sigma_y_pf**2]], float)

# Process Noise
q_states = np.array([0.03]*5, float)
Qx_base  = np.diag(q_states**2)

sigma_log_theta_rw = 0.002
Q_log_theta = np.diag(np.full(n_free, sigma_log_theta_rw**2))

Hf = 1

# -----------------------------------------------
# 4) UKF Initialization (Augmented State)
# -----------------------------------------------
x0 = np.array([Y_meas[0]]*5, float)

# Init params
theta0_full = theta_lo.copy()
theta0_full[free_idx] = 0.5*(theta_lo[free_idx] + theta_hi[free_idx])
phi0_free = np.log(theta0_full[free_idx])

# Augmented State z
z0 = np.concatenate([x0, phi0_free], axis=0)
nz = z0.size

# Covariance
P0 = np.zeros((nz, nz), float)
P0[:5,:5] = np.diag(np.full(5, 0.2**2))
P0[5:,5:] = np.diag(np.full(n_free, 0.3**2)) # log variance

# Sigma Points
points = MerweScaledSigmaPoints(nz, alpha=0.1, beta=2.0, kappa=0.0)

# Global tracker for time index inside fx
_current_k_for_fx = 0

def fx_augmented(z, dt):
    k = _current_k_for_fx
    x = z[:5]
    phi_free = z[5:] # Log-params

    # Convert to Linear
    theta_lin_free = np.exp(phi_free)
    theta_full = theta0_full.copy()
    theta_full[free_idx] = theta_lin_free

    # Get Physics
    Phi, Gu, GTo, GUs = discrete_system_control(theta_full, dt)

    # Inputs
    uk  = u_arr[k]
    Tok = T_out_K[k]
    Usk = U_s_arr[k]

    # Predict State
    x_next = Phi @ x + uk*Gu + Tok*GTo + Usk*GUs

    # Params RW handled by Q
    phi_next = phi_free

    return np.concatenate([x_next, phi_next])

def hx_augmented(z):
    return np.array([z[0]])

# Initialize Filter
ukf = UnscentedKalmanFilter(dim_x=nz, dim_z=1, dt=dt_seconds,
                            fx=fx_augmented, hx=hx_augmented, points=points)
ukf.x = z0.copy()
ukf.P = P0.copy()

# Set Noise
Q_aug = np.zeros((nz, nz), float)
Q_aug[:5,:5] = Qx_base
Q_aug[5:,5:] = Q_log_theta
ukf.Q = Q_aug
ukf.R = R

# -----------------------------------------------
# 5) Storage (Renamed for Global Assessment)
# -----------------------------------------------
Ti_mean_ukf = np.zeros(N); Ti_var_ukf = np.zeros(N)
Yhat    = np.zeros(N); S_arr  = np.zeros(N)
Theta_traj_ukf = np.zeros((N, len(theta_names))) # Linear storage

# Multistep
YH_mean = np.full((N, Hf), np.nan); YH_sd = np.full((N, Hf), np.nan)
YH_lo   = np.full((N, Hf), np.nan); YH_hi = np.full((N, Hf), np.nan)
TiH_mean = np.full((N, Hf), np.nan); TiH_sd = np.full((N, Hf), np.nan)
TiH_lo   = np.full((N, Hf), np.nan); TiH_hi = np.full((N, Hf), np.nan)

# t=0
Ti_mean_ukf[0] = ukf.x[0]; Ti_var_ukf[0] = ukf.P[0,0]
Yhat[0] = ukf.x[0]; S_arr[0] = ukf.P[0,0] + R[0,0]
Theta_traj_ukf[0] = theta0_full

# -----------------------------------------------
# 6) UKF Loop
# -----------------------------------------------
print("Running Log-Space UKF (Euler)...")

for k in range(1, N):
    yk = float(Y_meas[k])

    # Predict
    _current_k_for_fx = k-1
    ukf.predict()

    # Pre-update storage
    y_pred = ukf.x[0]
    S      = ukf.P[0,0] + R[0,0]
    Yhat[k]  = y_pred
    S_arr[k] = S

    # Update
    ukf.update(np.array([yk]))

    # Post-update storage
    Ti_mean_ukf[k] = ukf.x[0]
    Ti_var_ukf[k]  = ukf.P[0,0]

    # Store Linear Params
    theta_full = theta0_full.copy()
    theta_full[free_idx] = np.exp(ukf.x[5:])
    Theta_traj_ukf[k] = theta_full

    # Multistep Forecast
    if Hf > 0:
        x_h = ukf.x[:5].copy()
        P_h = ukf.P[:5,:5].copy()

        # Use current physics
        Phi_f, Gu_f, GTo_f, GUs_f = discrete_system_control(theta_full, dt_seconds)

        for h in range(1, Hf+1):
            kh = min(k + h - 1, N-1)
            uk_h  = u_arr[kh]; Tok_h = T_out_K[kh]; Usk_h = U_s_arr[kh]

            # Predict State
            x_h = Phi_f @ x_h + uk_h*Gu_f + Tok_h*GTo_f + Usk_h*GUs_f
            # Predict Cov (Add Q)
            P_h = Phi_f @ P_h @ Phi_f.T + Qx_base

            # Output Stats
            y_h = x_h[0]
            S_h = P_h[0,0] + R[0,0]
            sd_y = np.sqrt(max(S_h, 0.0))
            sd_x = np.sqrt(max(P_h[0,0], 0.0))

            YH_mean[k, h-1] = y_h
            YH_sd[k, h-1]   = sd_y
            YH_lo[k, h-1]   = y_h - 1.96*sd_y
            YH_hi[k, h-1]   = y_h + 1.96*sd_y

            TiH_mean[k, h-1] = x_h[0]
            TiH_sd[k, h-1]   = sd_x
            TiH_lo[k, h-1]   = x_h[0] - 1.96*sd_x
            TiH_hi[k, h-1]   = x_h[0] + 1.96*sd_x

# Explicitly calculate bands for later
Ti_lo_ukf = (Ti_mean_ukf - 1.96*np.sqrt(Ti_var_ukf)) - 273.15
Ti_hi_ukf = (Ti_mean_ukf + 1.96*np.sqrt(Ti_var_ukf)) - 273.15

print("Log-Space UKF Complete.")

# -----------------------------------------------
# 7) Diagnostics
# -----------------------------------------------
def coverage(y, lo, hi):
    y, lo, hi = map(np.asarray, (y, lo, hi))
    ok = np.isfinite(y) & np.isfinite(lo) & np.isfinite(hi) & (lo <= hi)
    if not np.any(ok): return np.nan, 0, len(y)
    y, lo, hi = y[ok], lo[ok], hi[ok]
    return float(np.mean((y >= lo) & (y <= hi))), int(ok.size), int(len(y) - ok.size)

def mean_width(lo, hi):
    return float(np.nanmean(np.asarray(hi) - np.asarray(lo)))

# One-step Bands
S_sd = np.sqrt(np.maximum(S_arr, 0.0))
Y_lo_1 = Yhat - 1.96*S_sd
Y_hi_1 = Yhat + 1.96*S_sd

cov_pred, n2, d2 = coverage(Y_meas, Y_lo_1, Y_hi_1)

print("=========== LOG-SPACE UKF DIAGNOSTICS ===========\n")
print(f"[One-step Prediction Y] Coverage: {100*cov_pred:.1f}% | Width: {mean_width(Y_lo_1, Y_hi_1):.3f} K")

if Hf > 0:
    print("[Multi-step Prediction Y]")
    for h in range(1, Hf+1):
        idx_end = N - h
        if idx_end <= 0: continue

        y_true = Y_meas[h:]
        y_lo   = YH_lo[:idx_end, h-1]
        y_hi   = YH_hi[:idx_end, h-1]

        cov_h, _, _ = coverage(y_true, y_lo, y_hi)
        wid_h = mean_width(y_lo, y_hi)
        print(f"  Horizon {h}: Coverage={100*cov_h:.1f}% | Width={wid_h:.3f} K")

# ============================================
# DIAGNOSTICS: RMSE, TF Errors, Winkler, Calibration
# ============================================
import numpy as np
import math

# ------------------------
# Helper: Winkler score for 95% intervals
# ------------------------
def winkler_score(y, lo, hi, alpha=0.05):
    """
    Compute mean Winkler score for (1-alpha) central prediction intervals.
    y, lo, hi: 1D arrays (same length, same units).
    """
    y  = np.asarray(y,  float)
    lo = np.asarray(lo, float)
    hi = np.asarray(hi, float)

    ok = np.isfinite(y) & np.isfinite(lo) & np.isfinite(hi) & (lo <= hi)
    if not np.any(ok):
        return np.nan

    y, lo, hi = y[ok], lo[ok], hi[ok]
    width = hi - lo

    score = np.empty_like(width)
    inside = (y >= lo) & (y <= hi)
    below  = (y < lo)
    above  = (y > hi)

    # Inside interval
    score[inside] = width[inside]
    # Below
    score[below]  = width[below] + (2.0/alpha)*(lo[below] - y[below])
    # Above
    score[above]  = width[above] + (2.0/alpha)*(y[above] - hi[above])

    return float(np.mean(score))


# ------------------------
# Helper: TF error metrics (H2-like, H1-like, H∞-like)
# ------------------------
def tf_error_metrics(theta_est, theta_true, channel, w_grid):
    """
    Compute frequency-domain errors between TF(theta_est) and TF(theta_true)
    for a given input channel over the given frequency grid w_grid.
    Returns a dict with absolute and relative H2, H1, H∞-like errors.
    """
    sys_true = build_siso_ss_from_theta(theta_true, channel)
    sys_est  = build_siso_ss_from_theta(theta_est,  channel)

    mag_true, phase_true, _ = control.freqresp(sys_true, w_grid)
    mag_est,  phase_est,  _ = control.freqresp(sys_est,  w_grid)

    G_true = mag_true.squeeze() * np.exp(1j*phase_true.squeeze())
    G_est  = mag_est.squeeze()  * np.exp(1j*phase_est.squeeze())

    diff     = G_est - G_true
    abs_diff = np.abs(diff)
    abs_true = np.abs(G_true)

    # H2-like (RMS over freq)
    h2_err  = math.sqrt(np.mean(abs_diff**2))
    h2_norm = math.sqrt(np.mean(abs_true**2))

    # H1-like (mean abs error / mean abs magnitude)
    h1_err  = float(np.mean(abs_diff))
    h1_norm = float(np.mean(abs_true))

    # H∞-like (max abs error / max abs magnitude)
    hinf_err  = float(np.max(abs_diff))
    hinf_norm = float(np.max(abs_true))

    return {
        "H2_err":   h2_err,
        "H2_rel":   h2_err / h2_norm if h2_norm > 0 else np.nan,
        "H1_err":   h1_err,
        "H1_rel":   h1_err / h1_norm if h1_norm > 0 else np.nan,
        "Hinf_err": hinf_err,
        "Hinf_rel": hinf_err / hinf_norm if hinf_norm > 0 else np.nan,
    }


# ====================================================
# 1) RMSE of RBPF vs EKF vs UKF on indoor temperature
# ====================================================
# Prefer true Ti if available, otherwise fall back to measured Y_meas
if 'Ti_true_C' in globals():
    y_true_C = np.asarray(Ti_true_C, float).ravel()
    target_label = "Ti_true"
else:
    # Measurement (Kelvin) → Celsius
    y_true_C = np.asarray(Y_meas, float).ravel() - 273.15
    target_label = "Y_meas (no true Ti available)"

# RBPF: Ti_md is already in °C
Ti_rbpf_C = np.asarray(Ti_md, float).ravel()

# EKF / UKF: means are in Kelvin; convert to °C
Ti_ekf_C = np.asarray(Ti_mean_ekf, float).ravel() - 273.15
Ti_ukf_C = np.asarray(Ti_mean_ukf, float).ravel() - 273.15

def rmse(a, b):
    a = np.asarray(a, float).ravel()
    b = np.asarray(b, float).ravel()
    return float(np.sqrt(np.mean((a - b)**2)))

rmse_rbpf = rmse(Ti_rbpf_C, y_true_C)
rmse_ekf  = rmse(Ti_ekf_C,  y_true_C)
rmse_ukf  = rmse(Ti_ukf_C,  y_true_C)

print("=========== RMSE on indoor temperature (°C) ===========")
print(f"Target series: {target_label}")
print(f"RBPF RMSE: {rmse_rbpf:.4f} °C")
print(f"EKF  RMSE: {rmse_ekf:.4f} °C")
print(f"UKF  RMSE: {rmse_ukf:.4f} °C")


# ====================================================
# 2) TF errors (H2, H1, H∞) for last parameter state
# ====================================================
theta_last = {
    "LS":   theta_ls,                 # offline least-squares
    "RBPF": Theta_rbpf[-1, :],        # median RBPF at final time
    "EKF":  Theta_traj_ekf[-1, :],    # EKF final parameters
    "UKF":  Theta_traj_ukf[-1, :],    # UKF final parameters
}

print("\n=========== Transfer Function Errors (final θ) ===========")
for ch in ['solar', 'heater', 'outside']:
    print(f"\nChannel: {ch}")
    for method_name, theta_est in theta_last.items():
        metrics = tf_error_metrics(theta_est, theta_true, ch, w_grid)
        print(
            f"  {method_name:4s} | "
            f"H2_abs={metrics['H2_err']:.3e}, H2_rel={metrics['H2_rel']:.3e} | "
            f"H1_abs={metrics['H1_err']:.3e}, H1_rel={metrics['H1_rel']:.3e} | "
            f"Hinf_abs={metrics['Hinf_err']:.3e}, Hinf_rel={metrics['Hinf_rel']:.3e}"
        )


# ====================================================
# 3) Winkler scores & 95% calibration (quiet vs latent)
# ====================================================
# Intervals are in °C:
#   RBPF: Ti_lo, Ti_hi
#   EKF:  Ti_lo_ekf, Ti_hi_ekf
#   UKF:  Ti_lo_ukf, Ti_hi_ukf
intervals = {
    "RBPF": (np.asarray(Ti_lo,     float).ravel(),
             np.asarray(Ti_hi,     float).ravel()),
    "EKF":  (np.asarray(Ti_lo_ekf, float).ravel(),
             np.asarray(Ti_hi_ekf, float).ravel()),
    "UKF":  (np.asarray(Ti_lo_ukf, float).ravel(),
             np.asarray(Ti_hi_ukf, float).ravel()),
}

# 95% coverage function was defined earlier as `coverage(y, lo, hi)`.
# Here we just reuse it.

# Regime masks: quiet vs latent (if F_true is available)
has_F_true = 'F_true' in globals()
if has_F_true:
    F_arr = np.asarray(F_true, float).ravel()
    quiet_mask  = np.abs(F_arr) < 1e-8
    latent_mask = ~quiet_mask
else:
    quiet_mask  = None
    latent_mask = None

print("\n=========== Winkler Scores & 95% Calibration (Ti, 95% bands) ===========")
print("All scores in °C units; 95% intervals; Winkler lower is better.")

for method_name, (lo_C, hi_C) in intervals.items():
    ws_all   = winkler_score(y_true_C, lo_C, hi_C, alpha=0.05)
    cov_all, _, _ = coverage(y_true_C, lo_C, hi_C)

    print(f"\nMethod: {method_name}")
    print(f"  Overall  : Winkler={ws_all:.4f}, 95%-cov={100*cov_all:.2f}%")

    if has_F_true and np.any(quiet_mask):
        ws_quiet   = winkler_score(y_true_C[quiet_mask],
                                   lo_C[quiet_mask],
                                   hi_C[quiet_mask],
                                   alpha=0.05)
        cov_quiet, _, _ = coverage(y_true_C[quiet_mask],
                                   lo_C[quiet_mask],
                                   hi_C[quiet_mask])
        print(f"  Quiet    : Winkler={ws_quiet:.4f}, 95%-cov={100*cov_quiet:.2f}%")

    if has_F_true and np.any(latent_mask):
        ws_latent   = winkler_score(y_true_C[latent_mask],
                                    lo_C[latent_mask],
                                    hi_C[latent_mask],
                                    alpha=0.05)
        cov_latent, _, _ = coverage(y_true_C[latent_mask],
                                    lo_C[latent_mask],
                                    hi_C[latent_mask])
        print(f"  Latent F : Winkler={ws_latent:.4f}, 95%-cov={100*cov_latent:.2f}%")

print("\nDiagnostics block complete.")

import numpy as np

# ============================
# Quick correlation diagnostics (using notebook variable names)
# ============================

def corr(a, b):
    a = np.asarray(a, float).ravel()
    b = np.asarray(b, float).ravel()
    mask = np.isfinite(a) & np.isfinite(b)
    if not np.any(mask):
        return np.nan
    a = a[mask]
    b = b[mask]
    return float(np.corrcoef(a, b)[0, 1])

# 1) Regime indicator R_t (0 = quiet, 1 = latent)
#    F_true is the latent heat signal from the simulator.
R = (np.abs(F_true) > 1e-8).astype(float)

# 2) Errors in °C for each method
Ti_true_C = np.asarray(Ti_true_C, float).ravel()          # from notebook (Kelvin → °C already)
Ti_rbpf_C = np.asarray(Ti_md,       float).ravel()        # RBPF median (in °C)
Ti_ekf_C  = np.asarray(Ti_mean_ekf, float).ravel() - 273.15
Ti_ukf_C  = np.asarray(Ti_mean_ukf, float).ravel() - 273.15

e_rbpf = Ti_true_C - Ti_rbpf_C
e_ekf  = Ti_true_C - Ti_ekf_C
e_ukf  = Ti_true_C - Ti_ukf_C

print("=== corr(regime, |error|) ===")
print("RBPF:", corr(R, np.abs(e_rbpf)))
print("EKF :", corr(R, np.abs(e_ekf)))
print("UKF :", corr(R, np.abs(e_ukf)))

# 3) Regime vs volatility (RBPF)
# The RBPF stores α-quantiles as Alpha_lo, Alpha_md, Alpha_hi (per time step)
if 'Alpha_md' in globals():
    alpha_med = np.asarray(Alpha_md, float).ravel()
    print("\n=== corr(regime, alpha_median) (RBPF) ===")
    print("RBPF:", corr(R, alpha_med))
else:
    print("\n(No Alpha_md found; skip volatility correlation.)")

# 4) Regime vs hit of 95% bands (coverage sensitivity)
# RBPF bands (already in °C): Ti_lo, Ti_hi
# EKF / UKF bands (already in °C): Ti_lo_ekf, Ti_hi_ekf, Ti_lo_ukf, Ti_hi_ukf
def hit_indicator(y, lo, hi):
    y  = np.asarray(y,  float).ravel()
    lo = np.asarray(lo, float).ravel()
    hi = np.asarray(hi, float).ravel()
    mask = np.isfinite(y) & np.isfinite(lo) & np.isfinite(hi) & (lo <= hi)
    H = np.zeros_like(y, dtype=float)
    H[mask] = ((y[mask] >= lo[mask]) & (y[mask] <= hi[mask])).astype(float)
    return H

H_rbpf = hit_indicator(Ti_true_C, Ti_lo,     Ti_hi)
H_ekf  = hit_indicator(Ti_true_C, Ti_lo_ekf, Ti_hi_ekf)
H_ukf  = hit_indicator(Ti_true_C, Ti_lo_ukf, Ti_hi_ukf)

print("\n=== corr(regime, hit) for 95% bands ===")
print("RBPF:", corr(R, H_rbpf))
print("EKF :", corr(R, H_ekf))
print("UKF :", corr(R, H_ukf))

import os
import numpy as np
from datetime import datetime
from google.colab import drive

# ==============================================================================
# SAVE RESULTS TO GOOGLE DRIVE (RAW DATA & FORECASTS)
# ==============================================================================

# 1. Mount Google Drive
drive.mount('/content/drive')

# 2. Setup Directory: Drive -> RBPF_Simulations -> Date_Time
# This creates a unique folder for every run so you don't overwrite old experiments.
timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M")
base_dir = "/content/drive/My Drive/RBPF_Simulations"
save_path = os.path.join(base_dir, timestamp)
os.makedirs(save_path, exist_ok=True)

print(f" Saving simulation data to: {save_path}")

# 3. Consolidate and Save
# We use .npz (compressed) for efficiency.
output_file = os.path.join(save_path, "simulation_results.npz")

np.savez_compressed(
    output_file,

    # ---------------------------------------------------------
    # A. METADATA & SETUP
    # ---------------------------------------------------------
    time_seconds    = ts_grid,               # Grid in seconds (for math)
    time_timestamps = ts,                    # Datetime objects (for plotting)
    theta_names     = np.array(theta_names), # Names of params ['Ci', 'Cm'...]
    dt_step         = dt_seconds,            # Time step size (e.g., 120s)

    # ---------------------------------------------------------
    # B. GROUND TRUTH & INPUTS (The Reality)
    # ---------------------------------------------------------
    truth_Ti        = Ti_true_C,        # True Indoor Temp (Celsius)
    truth_Y_meas    = Y_meas,           # Noisy Measurements (Kelvin)
    truth_F_latent  = F_true,           # True Latent Heat Signal (Watts)
    truth_theta     = theta_true,       # True Parameter Vector

    # Forcing Inputs
    input_heater    = u,                # Heater (Watts)
    input_Tout      = T_out_K,          # Outside Temp (Kelvin)
    input_Solar     = U_s,              # Solar (W/m2)

    # ---------------------------------------------------------
    # C. RBPF RESULTS (The Main Model)
    # ---------------------------------------------------------
    # Parameters (N x 10) - Median and 95% Bounds
    rbpf_theta_med  = Th_md,
    rbpf_theta_low  = Th_lo,
    rbpf_theta_high = Th_hi,

    # State Estimates (Indoor Temp)
    rbpf_Ti_med     = Ti_md,
    rbpf_Ti_low     = Ti_lo,
    rbpf_Ti_high    = Ti_hi,

    # Internal Logic
    rbpf_alpha      = Alpha_md,         # Adaptive noise scaler trajectory
    rbpf_regime     = regime_flag,      # 0=Quiet, 1=Burst

    # ---------------------------------------------------------
    # D. BASELINE RESULTS (EKF & UKF)
    # ---------------------------------------------------------
    # EKF
    ekf_theta_mean  = Theta_traj_ekf,   # Parameter Means
    ekf_Ti_mean     = Ti_mean_ekf,      # State Mean
    ekf_Ti_var      = Ti_var_ekf,       # State Variance (use to compute CI)

    # UKF
    ukf_theta_mean  = Theta_traj_ukf,   # Parameter Means
    ukf_Ti_mean     = Ti_mean_ukf,      # State Mean
    ukf_Ti_var      = Ti_var_ukf,       # State Variance (use to compute CI)

    # ---------------------------------------------------------
    # E. STATIC FIT
    # ---------------------------------------------------------
    ls_theta_static = theta_ls,         # Offline Least Squares fit vector

    # ---------------------------------------------------------
    # F. MULTI-STEP FORECASTS (The "Planning" Data)
    # ---------------------------------------------------------
    # Horizon Metadata
    # We assume H is the horizon variable from your script
    forecast_horizon_steps = np.arange(1, H + 1),

    # RBPF Forecasts (Matrices: N x H)
    rbpf_forecast_med  = TiH_pred_md,
    rbpf_forecast_low  = TiH_pred_lo,
    rbpf_forecast_high = TiH_pred_hi,

    # UKF Forecasts (Matrices: N x H)
    # Note: Your UKF loop calculated these
    ukf_forecast_mean  = TiH_mean,
    ukf_forecast_std   = TiH_sd
)

print(f" File: {output_file}")